### ISSUE TITLE
Migration to Pydantic 2.0 in GDSFactory and Tidy3D

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#1007]
In GDSFactory, we are currently planning to migrate to Pydantic 2.0, and we wanted to inquire about the migration plan for Tidy3D.

some other projects like fastapi have already migrated

https://docs.pydantic.dev/2.0/migration/

**Comment by tylerflex** [comment]
Yea we will migrate once I have time to look into this, I will put it on my to do list for the next few weeks and will check back.

**Comment by tylerflex** [comment]
if tidy3d upgrades to 2.0, does that mean it will be incompatible with gdsfactory until gdsfactory upgrades too?

**Comment by joamatab** [comment]
KFactory plugin has already completed its migration to Pydantic 2.0

I have been also having issues porting gdsfactory to pydantic2
I've tried both migrating to the new [V2 models](https://github.com/gdsfactory/gdsfactory/tree/pydantic2) as well as using the [V1 old API](https://github.com/gdsfactory/gdsfactory/tree/pydantic2_v1)

https://github.com/gdsfactory/gdsfactory/issues/1591

@daquintero
@flaport
@sebastian-goeldi
@skandanc
@dmontagu

**Comment by joamatab** [comment]
We are finished porting gdsfactory to pydantic2 :tada: 

https://github.com/gdsfactory/gdsfactory/actions/runs/5593393008/jobs/10226984866

Now we are wating for the plugins to port

https://github.com/gdsfactory/gdsfactory/pull/1879

**Comment by momchil-flex** [comment]
Any tips that may be relevant? Seems like you had issues but have managed to resolve them.

**Comment by joamatab** [comment]
yes, just sent a new PR to tidy3d

this packaged that Ali suggested was great

https://github.com/pydantic/bump-pydantic#installation

**Comment by joamatab** [comment]
And yes Tyler, if we release gdsfactory with pydantic2 and you are still using the old pydantic the tidy3d pluging won't work, that's why im waiting for you to release a new tidy3d with compatible with pydantic > 2

**Comment by tylerflex** [comment]
Thanks I'll get to it whenever I can, have a few other things on my plate but hoping to give it a shot by tomorrow.
