### ISSUE TITLE
Replace some of the material library models with better ones found with the new fitter

### ISSUE THREAD

**Issue by momchil-flex** [flexcompute/tidy3d#1021]

**Comment by tomflexcompute** [comment]
@e-g-melo I think this issue can be closed now?

**Comment by momchil-flex** [comment]
@e-g-melo could you clarify status of this and #1022

**Comment by e-g-melo** [comment]
They were already merged into 2.4

**Comment by e-g-melo** [comment]
We can close them

**Comment by momchil-flex** [comment]
fixed in #1047 

Note that you can put a comment that includes `fixes #issue_number` in a PR to automatically close an issue.
