### ISSUE TITLE
Geometry.intersections_2dbox bug

### ISSUE THREAD

**Issue by alec-flexcompute** [flexcompute/tidy3d#1039]
When passing a plane to Geometry.intersections_2dbox(), this method replicates the plane with a shapely box, but uses xmin of the plane for both the xmin AND ymin of the shapely box, and xmax for both the xmax AND ymax of the shapely box - the ymin and ymax of the plane are not used. This causes the method to miss intersections.

**Screenshots**
![image](https://github.com/flexcompute/tidy3d/assets/139144665/fb00b01a-dfa5-4d5a-a93a-06cd2086d958)
Line 225 here has the original line, commented out. Line 226 here has a fix that includes ymin and ymax of the plane, and returns proper intersections.

**Comment by tylerflex** [comment]
Seems like a bug to me?

**Comment by momchil-flex** [comment]
Yikes. I'm surprised this hadn't reveled itself already in various ways.

**Comment by alec-flexcompute** [comment]
I think that's because most of these windows are probably squares centered at the origin

**Comment by tylerflex** [comment]
solved by #1040
