### ISSUE TITLE
Dispersion Fitter changes

### ISSUE THREAD

**Issue by momchil-flex** [flexcompute/tidy3d#104]
The public fitter may have changed in tidy3d-client-api since it was ported here. Once Weiliang wraps everything up, we should re-port it carefully, and also decide where to put the "private" fitter where things are handled extra carefully (the one that will be accessible through a web api).

- [x] Also, the `'Li1993_293K'` variant of cSi in the material library of old Tidy3D has changed, change it here too.

>>> Tyler

Also, add new features to the fitter, such as: 
- [ ] wavelength range specification
- [x] importing data from refractiveindex.info
- [ ] Update documentation to give lots of details on how to avoid dispersion practically in tidy3d.

**Comment by tylerflex** [comment]
@weiliangjin2021  @momchil-flex What are we still planning to get in before Monday's release?

**Comment by weiliangjin2021** [comment]
> The public fitter may have changed in tidy3d-client-api since it was ported here. Once Weiliang wraps everything up, we should re-port it carefully, and also decide where to put the "private" fitter where things are handled extra carefully (the one that will be accessible through a web api).
> 
> Also, the `'Li1993_293K'` variant of cSi in the material library of old Tidy3D has changed, change it here too.
> 
> > > > Tyler
> 
> Also, add new features to the fitter, such as:
> 
> * [ ]  wavelength range specification
> * [ ]  importing data from refractiveindex.info
> * [ ]  Update documentation to give lots of details on how to avoid dispersion practically in tidy3d.

The three TODOs will be handled in the next release.
