### ISSUE TITLE
Tidy3D Conversion script

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#1049]
Lumerical provides a Python API [link](https://optics.ansys.com/hc/en-us/articles/360037824513-Python-API-overview) that can be used to define more complex simulations and perform inverse design (Lumopt). It seems quite feasible that we can develop a Tidy3D plugin that takes a Lumerical .lsf file and convert it into a python script that defines the same Tidy3D simulation. 

The first step could be to convert the .lsf file into a python script by something similar to [this](https://optics.ansys.com/hc/en-us/articles/1500007185181-FDTD-Project-to-Script-Prototype). Then the python script can be parsed and converted to a Tidy3D script with the same structures, sources, monitors, boundary conditions, etc.

This plugin mainly serves two purposes: 

1. Many prospects would come to us with a Lumerical model they used previously and want to perform an accuracy and run time benchmark (either by themselves or by us). Currently the conversion of Lumerical model to Tidy3D model is done manually, which can be time consuming for more complex simulations; 

2. Most prospects are fluent in Lumerical and have many lumerical models they made before. Using this plugin accelerates their migration to Tidy3D.

Main deliverables:
- [ ] A method to convert numerical scripts to Tidy3d (either script or classes, to be determined)
- [ ] A notebook showcasing this conversion on a popular Lumerical example.

Any discussions regarding the design can be done in this GitHub issue before starting.
@tomflexcompute @momchil-flex

**Comment by momchil-flex** [comment]
Do we want to make a notebook about this? I think we could use the lumopt example since their docs are MIT license. I'm not sure if there are any other copyright concerns.

Or should we just close this?

**Comment by tomflexcompute** [comment]
No sure if it's easy to use one of their examples as they are designed for optimization. Maybe @alec-flexcompute can take a look [here](https://lumopt.readthedocs.io/en/latest/tutorial.html) and give it a try?

**Comment by momchil-flex** [comment]
That's the one Alec has already been using to test.

**Comment by alec-flexcompute** [comment]
Correct, this is the only lsf I was able to find on the internet

**Comment by tylerflex** [comment]
fixed by #1165
