### ISSUE TITLE
Particle swarm optimization

### ISSUE THREAD

**Issue by momchil-flex** [flexcompute/tidy3d#1107]
It would be great to add one or a few examples of particle swarm optimization to our notebooks. There is a lot of interest in that because I think it can be pretty good to find big improvement in designs that rely on a small number of parameters that are still too many to handle in a full parameter scan. I think we can even pick one of our existing PIC examples, ideally a single simulation should be small-ish, and we should optimize 3-5 global parameters so that the total number of simulations that have to be done is manageable for an example.

Any other thoughts @tomflexcompute @tylerflex?

**Comment by tomflexcompute** [comment]
Yeah I can work on it. In the next few weeks. 

A few customers have asked about PSO and pyswarms have been my recommendations for them as well. Should be relatively straightforward to incorporate it with Tidy3D I think. One question is can we simply use public packages like this in our published materials? I guess we have been using things like `pandas` and `scipy` but in general is it ok to directly use these for commercial purposes?

**Comment by tomflexcompute** [comment]
It's under MIT license which permits commercial use so it should be good to go?

**Comment by e-g-melo** [comment]
Nice! I've suggested including these global optimization features and Monte
Carlo simulations as new study types in GUI in the future. This notebook
will help a lot as a starting point.

**Comment by tylerflex** [comment]
Sounds good to me and I would reinforce that we should use external optimization packages (eg pyswarms) whenever possible. Just remember to add it here: https://github.com/flexcompute-readthedocs/tidy3d-docs/blob/develop/docs/requirements.txt

**Comment by tomflexcompute** [comment]
The PBS notebook has been merged and the bullseye extractor is about to be merged too. We can close this issue now.
