### ISSUE TITLE
Make default tidy3d dir configurable via environment variables

### ISSUE THREAD

**Issue by yaugenst** [flexcompute/tidy3d#1131]
I am trying to run tidy3d on serverless containers (e.g. Google Cloud Run). These containers have read-only file systems, with only `/tmp/` being writable. It would be nice if tidy3d's base/config directory could be configured via an environment variable such as `TIDY3D_DIR`.

Going a bit further, do you think it would be a good idea for tidy3d to adopt the [XDG base directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), which would mean putting tidy3d's configuration in `$HOME/.config/tidy3d/` by default? Resolving config directory via some precedence rules would also be cool, but probably overkill (see, e.g., [how conda does it](https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#searching-for-condarc)).

**Comment by tylerflex** [comment]
closing this as seems fixed by #1132
