### ISSUE TITLE
Group index step validators

### ISSUE THREAD

**Issue by dbochkov-flexcompute** [flexcompute/tidy3d#1143]
Current group index validator doesn't error on `ModeSpec(group_index_step=1)` https://github.com/flexcompute/tidy3d/blob/develop/tidy3d/components/mode.py#L133-L140. From what I understand, this happens because `1` is automatically converted into `True` given the field definition `group_index_step: Union[bool, pd.PositiveFloat]`. I tried changing it to `group_index_step: Union[pd.PositiveFloat, bool]` but in this case `True` gets converted into `1`. Not sure what would be the best way to resolve this issue. I guess one option is to just split this field into two :
- `group_index_step: pd.PositiveFloat = pd.Field(GROUP_INDEX_STEP, ...)` 
- `compute_group_index: bool = pd.Field(False, ...)`

What do you think, @lucas-flexcompute?

Also, root validator https://github.com/flexcompute/tidy3d/blob/develop/tidy3d/components/mode.py#L142 probably needs `skip_on_failure=True`. Otherwise, even if previous validators fail, it still gets executed and fails itself when trying to get `values["group_index_step"]`. So, instead of desired
```
           ERROR: Parameter 'group_index_step' must be less than 1.  mode.py:140
```
what gets displayed is:
```
>       if values["group_index_step"] > 0:
E       KeyError: 'group_index_step'

tidy3d/components/mode.py:146: KeyError
```

**Comment by lucas-flexcompute** [comment]
Fixed in #1152
