### ISSUE TITLE
Tidy3d favicon in docs

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#1173]
Our favicon looks like this: 
<img width="90" alt="image" src="https://github.com/flexcompute/tidy3d/assets/92756888/054ce807-322c-48e8-bc2c-f7ae8bd93b6d">
(readthedocs default?)

But I think we set it in our[ docs conf.py.](https://github.com/flexcompute-readthedocs/tidy3d-docs/blob/develop/docs/source/conf.py#L157C8-L157C8)

Would be good to figure out what's up here and fix it.

**Comment by daquintero** [comment]
Hi Tyler!

Maybe this is helpful: 

From https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_favicon :

> It should be a Windows-style icon file (.ico), which is 16x16 or 32x32 pixels large. Default: None.

Maybe it just needs to be converted to a correct `ico` file from the provided `svg`? [This website](https://cloudconvert.com/svg-to-ico) should help.

As soon as I get more time available and my things calm down, I'll begin PR-ing to get more involved and help sooner!

**Comment by tylerflex** [comment]
Thanks @daquintero ! Probably this is it. I might assign you to a few things related to our docs at the beginning because we need some help there, but no rush to get started until your official date!

**Comment by tylerflex** [comment]
Yea this seemed to work! I fixed it in this PR, thanks

https://github.com/flexcompute-readthedocs/tidy3d-docs/pull/295

**Comment by daquintero** [comment]
Great to hear! I am getting familiar with the codebase anyway so plan to go through some open issues when I get the chance

Glad it's going well!
