### ISSUE TITLE
Reduce simulation file size for mode solver

### ISSUE THREAD

**Issue by dbochkov-flexcompute** [flexcompute/tidy3d#1191]
In case of large simulations with custom media the total size of simulation file can be quite big. When calling server side mode solver, the entire simulation size is uploaded, however, typically only a small subset of data is required. Maybe we could introduce a way that uploads only the required data.

**Comment by tylerflex** [comment]
I wonder if (in the spirit of the `.to_gds` stuff) there could be some way to "export" part of a simulation. For example:
```
sim.subsection(region: Box) -> Simulation.   # generate a simulation containing only the `region`.
```

do you have something similar in heat solver?

**Comment by momchil-flex** [comment]
Assigning @dbochkov-flexcompute so that someone is responsible for this; it's a long-term thing though. I put it for 2.6 for now.

**Comment by dbochkov-flexcompute** [comment]
I have a working prototype and now thinking how to split it between `Simulation` and mode solver plugin
- First option is to just keep everything in mode solver plugin. In this case, since it is used for a very specific purpose, I would not actually care to change simulation dimensions, just remove irrelevant structures/custom medium points and ensure that the same discretization grid is used. This makes it easy to deal with symmetry options, since we are not changing simulation `center`/`size`.
- Second option is to implement a standalone `Simulation.subsection(region: Box) -> Simulation` per Tyler suggestion. This could be potentially useful elsewhere eventually, but requires ironing out a couple of things. First, do we just transfer boundary conditions directly? Perhaps, one way could be to have an optional argument to specify new boundary conditions if needed. Second, have to be careful while dealing with symmetry. The approach that I could see there is the following. If subsection box doesn't go inside symmetry regions, just return a new simulation without a symmetry and center/size taken from the subsection box. If the subsection box does go into symmetry region, automatically expand it symmetrically so that new simulation center coincides with the old simulation center.

Any thoughts @tylerflex @momchil-flex ?

**Comment by tylerflex** [comment]
I'd say overall just depends on how useful this Simulation.subsection would be and if it's worth your time.

Regarding the specific implementation of that:
> First, do we just transfer boundary conditions directly? Perhaps, one way could be to have an optional argument to specify new boundary conditions if needed.

I'd say transfer BCs with option to overwrite them yea.

> Second, have to be careful while dealing with symmetry. The approach that I could see there is the following. If subsection box doesn't go inside symmetry regions, just return a new simulation without a symmetry and center/size taken from the subsection box. 

That sounds reasonable on me.

> If the subsection box does go into symmetry region, automatically expand it symmetrically so that new simulation center coincides with the old simulation center.

I might suggest simplifying this: if the subsection box is exactly centered at the symmetry, then the new simulation ha the same symmetry. If the subsection box intersects the symmetry plane but isn't centered, error? What you suggest probably works, but might be an edge case we dont need to handle and it could indicate someone setting something up incorrectly?

**Comment by dbochkov-flexcompute** [comment]
> I might suggest simplifying this: if the subsection box is exactly centered at the symmetry, then the new simulation ha the same symmetry. If the subsection box intersects the symmetry plane but isn't centered, error? What you suggest probably works, but might be an edge case we dont need to handle and it could indicate someone setting something up incorrectly?

Yeah, I think this makes sense and is easier too, thanks!

**Comment by momchil-flex** [comment]
Should we close this now @dbochkov-flexcompute

**Comment by dbochkov-flexcompute** [comment]
yeah
