### ISSUE TITLE
Clarify `waist_difference` better in docstring.

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#1196]
the `td.GaussianBeam.waist_difference` [docstring](https://docs.flexcompute.com/projects/tidy3d/en/latest/_autosummary/tidy3d.GaussianBeam.html
) descriptions says the following 

"
Distance from the beam waist along the propagation direction. When direction is + and waist_distance is positive, the waist is on the - side (behind) the source plane. When direction is + and waist_distance``is negative, the waist is on the ``+ side (in front) of the source plane.
"

It wasn't really clear from this how the behavior should look for `direction="-"`, eg in a downward propagating beam incident on a grating coupler. If we want the beam to converge in the propagation direction (so on the "+" side of src for direction="+" and on the "-" side for direction="-"), it seems we always want a negative beam distance? I feel we should clarify this better in the docstring. 

Is my understanding correct and how should we rephrase this?

Also note, there's some misformatting of the quotes in the description as well.

**Comment by momchil-flex** [comment]
I might wait for @daquinteroflex 's updates before doing this - or maybe he has fixed it already?

**Comment by momchil-flex** [comment]
Yep sounds great!

**Comment by FilipeFcp** [comment]
Hi all. What do you think of something like this: 

![image](https://github.com/user-attachments/assets/da2a00a8-12d7-46f4-b192-c7e1908e8211)

**Comment by momchil-flex** [comment]
Looks good to me. Maybe for those who may still wonder why this choice: imagine that there's an axis in the direction of propagation and the beam center is at 0, then the beam distance is just the position of the plane along that axis.

That makes me wonder though, what happen when the beam is at an angle. Is the beam distance measured along the normal axis or the propagation axis? i.e. a difference of something like cos(theta). Maybe best to clarify this too?
