### ISSUE TITLE
Selective documentation of inherited attributes

### ISSUE THREAD

**Issue by momchil-flex** [flexcompute/tidy3d#1197]
Our documentation is becoming hard to search through and some class pages are becoming too crowded with attributes that are not too relevant, because currently all attributes of all parent classes are documented. Thus for example searching for `sidewall_angle` in the search bar returns many hits of sources and monitors, which have nothing to do with it, because they inherit from Box, which inherits from Geometry, which has some methods where `sidewall_angle` appears.

Conversely there are many cases in which we *do* want some of the inherited attributes to be documented, at least up to a given level. For example various sources and monitors inherit a lot from abstract source and monitor classes.

So it would be great if we can selectively choose which inherited classes to be included in the documentation for a given class, and which not.

**Comment by daquinteroflex** [comment]
I think this is fixed now in the next docs upgrade for all cases, and we have full control over customising relevant functionality for each class. Happy to help with that too when I get down to a deep docs review.

See live example at https://flexcompute-tidy3d-docs-demo.readthedocs-hosted.com/en/repo_merge_no_history/search.html?q=sidewall_angle

![Screenshot from 2023-11-24 15-15-19](https://github.com/flexcompute/tidy3d/assets/149674618/f174a8c7-4c50-4ee4-987b-cfd5d4f7d6fc)
![Screenshot from 2023-11-24 15-15-27](https://github.com/flexcompute/tidy3d/assets/149674618/42013508-fc09-495b-b031-578a118eac87)

**Comment by momchil-flex** [comment]
Awesome, this looks great now! Shall we still only close this when the new documentation goes to production?

**Comment by daquinteroflex** [comment]
Yep sounds good then!

**Comment by tylerflex** [comment]
can this be closed?

**Comment by daquinteroflex** [comment]
So should be properly fixed in pydantic v2 upgrade, but for now it is defacto patched so maybe we can reference this in the pydantic v2 port issue
