### ISSUE TITLE
Docs on physical constants have incorrect descriptions 

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#1213]
Somehow docs are not built correctly such that the descriptions for physical constants such as [td.C_0](https://docs.flexcompute.com/projects/tidy3d/en/latest/_autosummary/tidy3d.C_0.html) are incorrect. 

![image](https://github.com/flexcompute/tidy3d/assets/116006359/6a0cd06f-56a2-4700-99f0-d3b6e3703a13)

**Comment by tylerflex** [comment]
can this be closed?

**Comment by daquinteroflex** [comment]
So this is better now, but hard to fully add docs to these constants as it's an autosummary unimplemented feature. I've tried a few options. Maybe we can close it and see how https://github.com/sphinx-doc/sphinx/issues/6794 evaluates, or maybe post pydantic v2 probably easier to implement

**Comment by daquinteroflex** [comment]
Closing for now, as it's not giving a wrong docsting anymore, but not a good one either haha
