### ISSUE TITLE
Support "LO-TO form" of Lorentz

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#1222]
I think this has been in the plan for some time but I forgot the current status. Another user just asked if we can support this. @weiliangjin2021 is this feature ready or going to be ready very soon?

I don't remember if we have an issue for this already but I couldn't find it. If there is one already please feel free to close this one.

**Comment by weiliangjin2021** [comment]
Is it the one on jira involving multiplications? I found it complicated, and since no user is actively asking, I lowered its priority.

**Comment by tomflexcompute** [comment]
Oh yes it might have been a jira ticket of of github issue. From time to time some users asked about it. So far my recommendation has been using the analytical LOTO form to calculate the permittivity and then use FastDispersionFitter to do the fitting. It has been working pretty well but eventually I think it's beneficial to natively support it somehow without the fitting.

**Comment by momchil-flex** [comment]
Or just provide some sort of convenience for the fitting approach?

**Comment by weiliangjin2021** [comment]
maybe @caseyflex is more familiar with fraction decomposition? The dispersion is described by Eq. 8 in this [paper](https://journals.aps.org/prb/abstract/10.1103/PhysRevB.61.8187). It seems not so easy to convert product to sum.

**Comment by caseyflex** [comment]
It should be straightforward to evaluate partial fraction decomposition of
this, since the roots of the denominator are known. I think it’s somewhat
harder if we needed to factorize.

**Comment by weiliangjin2021** [comment]
@caseyflex do you want to give it a try?

**Comment by caseyflex** [comment]
yeah, I can give it a try.
