### ISSUE TITLE
Error in JaxCustomMedium plot when using plot_field.

### ISSUE THREAD

**Issue by e-g-melo** [flexcompute/tidy3d#1235]
When performing an optimization including two JaxCustomMedium objects with mirror symmetry about y = 0, an error occurs in `plot_field`, as shown below. If only one JaxCustomMedium is included in the simulation, the structure is correctly displayed. The error happens with and without simulation symmetry.

The error was observed in the quantum emitter light extractor notebook.

Error - Two JaxCustomMedium objects are included in the simulation.

`plot_eps`
![image](https://github.com/flexcompute/tidy3d/assets/125516370/badeb0f8-9afa-4462-9797-a79a37862043)

`plot_field`
![image](https://github.com/flexcompute/tidy3d/assets/125516370/61632ca7-7b00-4da5-a923-a643c0f63688)

No error - Only one JaxCustomMedium object is included in the simulation.

`plot_eps`
![image](https://github.com/flexcompute/tidy3d/assets/125516370/7ac8edc0-1516-4f2c-8c0f-3c3a15662d07)

`plot_field`
![image](https://github.com/flexcompute/tidy3d/assets/125516370/7260183e-9285-4dbe-9e8e-0335b5a37952)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 119.0.6045.106 (Official Build) (64-bit)

**Comment by tylerflex** [comment]
So there's a single custom medium at y>0 and then its mirror image at y<0?

And just to clarify, with symmetry off, you would also see this effect with both custom media (like in the image below but with no symmetry)?

<img width="802" alt="image" src="https://github.com/flexcompute/tidy3d/assets/92756888/5a8777c0-c683-4685-ba6b-42d28f35a428">

**Comment by e-g-melo** [comment]
So there's a single custom medium at y>0 and then its mirror image at y<0?
Yes

And just to clarify, with symmetry off, you would also see this effect with both custom media (like in the image below but with no symmetry)?
There was no difference in the image with and without symmetry.

**Comment by tylerflex** [comment]
Fixed by #1237
