### ISSUE TITLE
Higher level inverse design wrapper plugin

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#1244]
Writing down basic thoughts from some internal discussions.

Might make sense to provide a wrapper around `adjoint` plugin that gives users a more high level interface for performing inverse design. 

For example, define a `DesignRegion` with some fields like `parameters`, `eps_min`, `eps_max` as well as fabrication constraint fields `beta`, `filter_radius`, `num_projections`.   This object could be treated like a `CustomMedium`-containing `Structure` in this plugin, but under the hood it converts to a `JaxCustomMedium`-containing structure using `adjoint`.

lots of other avenues to explore, but this could improve the usability of inverse design.

Crucially, I like the idea of keeping the `adjoint` plugin as simply a `jax`-compatible wrapper around `tidy3d` and then building the inverse design plugin around `adjoint`, rather than mixing the two.

**Comment by e-g-melo** [comment]
Some thoughts about structuring a high-level interface around the adjoint plugin.

```
class DesignRegion(object):
	def __init__(
	        self,
	        center: list = [],  # Design region center. 
	        size: list = [],  # Design region size.
	        symmetry: list = [],  # Symmetry about the `x` and `y` design region axis. 
					fab_grid_size: float = None,  # Grid size of a finer mesh used to include fabrication constraints. The overall idea is to define the fabrication constraints in this finer mesh to get smoother structures.
	        medium_grid_size: float = None,  # Grid size of the mesh used to create the adjoint custom medium. Downsampled from the finer mesh.
					buffer_length: float = None,  # Buffer length around the design region to enhance fabrication constraints at interfaces. Here, we could have a function to automatically extend the external geometries into the buffer. The topology optimization buffer has been implemented in the GC notebook. The level set version, however, should be more involved and still needs implementation.
					eps_low: float = None,  # Lower permittivity value.
					eps_hight: float = None,  # Higher permittivity value.
					feature_size: float = 0.14  # Minimum fabrication feature size.
	    ):

	def export_to_GDS(filename):
			""" Function to export the generated design to GDS. 
					The idea is to use the finer mesh to generate the GDS within the design region, 
					hopefully obtaining smoother contours. 
			"""

class TopologyDesignRegion(DesignRegion):
	def __init__(
	        self,
	        eta: float = 0.5,  # Threshold value for the projection filter.
					params: jnp.ndarray = None,  # Initial parameters. Generated randomly if not provided.
	    ):

	def update_design(params: np.ndarray = None, beta: float = None)-> List[JaxStructure]:
		""" Function which includes all the machinery to project and filter the design parameters,
				build the interface buffer, convert the parameters to permittivities, and then return the JaxStructure.
		"""
		self.params = params

		return JaxStructure

class LevelSetDesignRegion(DesignRegion):
	def __init__(
	        self,
	        gap_par: float = 1.0,  # Parameter to minimum gap fabrication constraint.
					curve_par: float = 1.5,  # Parameter of minimum curvature fabrication constraint.
					sharpness: float = 4,  # Sharpness parameter to smoothed heaviside function used to project the level set surface into permittivity.
					init_struct: Tuple[Structure, ...] = None,  # Optional initial geometry to build the starting level set surface. If not provided, we can start from a randomly generated surface.
			    init_gap_penalty: float = None,  # Optional initial value of gap penalty function. If not provided, we need to calculate it after getting the initial level set surface.
			    init_curve_penalty: float = None,  # Optional initial value of curvature penalty function. If not provided, we need to calculate it after getting the initial level set surface.
			):

	def update_design(params: np.ndarray = None, beta: float = None)-> List[JaxStructure]:
		""" Function which includes all the machinery to project and filter the design parameters,
				build the interface buffer, convert the parameters to permittivities, and then return the JaxStructure.
		"""
		self.params = params

		return JaxStructure

	def get_penalty()-> Tuple(float, float):
		""" Function to calculate and return the gap and curvature penalty values. 
		"""
		return (gap_penalty, curvature_penalty)

	def plot_penalty():
		""" Function to plot the gap and curvature penalty values. 
		"""
```

**Comment by tylerflex** [comment]
Thanks @e-g-melo 

So the basic ideas are:
1.  the abstract class `DesignRegion` defines sort of the `td.Box` level fields + some extra things (like symmetry), and some interfaces for exporting the result to GDS. (This design region will have `@abstractmethod` templates for things like `get_penalty` and `update_design` eventually).
2. the subclasses (Topology, LevelSet) add their own specific fields and implement a function to return a `JaxStructure` given the design params. So the parameters never get stored directly in the DesignRegion, the `update_design()` function just defines how an array of parameters generates the structure?

So in practice, how would this be used? like this?

```py
sim_base = make_sim_base(...) # make a JaxSimulation without any input_structures
design_region = TopologyDesignRegion(...)

def make_sim(params):
    design_structure = design_region.update_design(params)
    return sim_base.updated_copy(input_structures=[design_structure])

# ... use make_sim in your objective fn?
```

*(by the way, to make the code snippets highlighted like this you just put ```py at the top triple quotes.)

**Comment by tylerflex** [comment]
I think the general approach that you wrote could be useful in making the process smoother. To me it seems like something we could put in `adjoint/utils` for now.

An alternative approach could be something like a `JaxStructure` subclass `JaxDesignRegion` that can be added into the `JaxSimulation` directly and stores it's `params` as a field.

I can also imagine an `td.plugins.invdes` wrapper that completely provides its own interface around tidy3d to make things even more streamlined (including optimizers for example, so instead of `Simulation` you might have `OptimizationProblem`). But this would be a much larger effort.

**Comment by e-g-melo** [comment]
Hi @tylerflex!

You have captured the idea very well, even though my draft is not that rigorous. Actually, I started it on a notion page and did a copy/paste here. 

We should also include a `get_penalty()` in the `TopologyDesignRegion` so that our objective function would be:

```py
sim_base = make_sim_base(...) # make a JaxSimulation without any input_structures
design_region = TopologyDesignRegion(...)

def make_sim(params, beta):
    design_structure = design_region.update_design(params, beta)
    return sim_base.updated_copy(input_structures=[design_structure])

def obj(params, beta: float = 1.0) -> float:
    sim = make_sim(params, beta)
    sim_data = run(sim, task_name=task_name)
    fom_val = fom(sim_data)
    feature_size_penalty = design_region.get_penalty()
    J = fom_val - feature_size_penalty
    return J, sim_data
```

Your ideas are pretty cool! If we have well-encapsulated components and something like an `OptimizationProblem`, maybe we can include the adjoint in GUI.
