### ISSUE TITLE
Better handling of "edge" cases in adjoint design regions

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#1245]
Based on how we do things in our docs, we tend to ignore the background of the device when optimizing a design region. This leads to weird discontinuities like

<img width="328" alt="image" src="https://github.com/flexcompute/tidy3d/assets/92756888/899495b8-645b-47c7-b5f4-2e919a554871">

Would be good to come up with some simple ways to solve this.

Some half-baked ideas:
1. Include a "static" buffer around design region when doing filter / projections. Don't update this buffer region, but do include it in penalty and filtering operations.
2. Add a penalty for the difference between the design region perimeter permittivity and the background permittivity just outside the design region.

Maybe @ianwilliamson knows some tricks? :D

**Comment by ianwilliamson** [comment]
Is your background geometry defined by a numpy density array or by simulation primitives like blocks or polygonal prisims? The most straightforward way of handling this is probably to define the entire simulation geometry using a filter + project parameterization in a numpy density array. In your optimization, you can mask your gradients / updates to the design region.

**Comment by tylerflex** [comment]
Simulation primitives.  Your suggestion makes sense and seems consistent with 1 above, so we could probably give that a try @e-g-melo . Thanks Ian

> nclude a "static" buffer around design region when doing filter / projections. Don't update this buffer region, but do include it in penalty and filtering operations.

**Comment by e-g-melo** [comment]
Yes, it should work. Thanks for the suggestion! I will plan a notebook to try it.

**Comment by tylerflex** [comment]
closing but when we do #1244 we can try to incorporate this
