### ISSUE TITLE
Convenience wrapper for loading data from hdf5 for specific monitors only

### ISSUE THREAD

**Issue by shashwat-sh** [flexcompute/tidy3d#1248]
Loading the data associated with all monitors in one go may be slow or crash-prone if there is a lot of data and/or a lot of monitors. In cases where only part of this data is needed, and is associated with specific monitors, it would help to be able to load the data for a specified monitor only.

There already seems to be a way to do this, as explained by @tylerflex :

>
    I just tested this and we can already load individual monitor data from hdf5 files.
    But it’s not through the monitor name, the syntax to load the i -th monitor data from a simulation data file filename is

        mnt_data = {MonitorData}.from_file(filename, group_path="data/{i}")

    and you need to use the right MonitorData class.
    Eg to load the data for the 3rd monitor, which happens to be FluxData, you’d do

        flux_data = td.FluxData.from_file(filename, group_path="data/2")

    it would be super simple to write a convenience method for this, perhaps with syntax

        flux_data = td.SimulationData.mnt_data_from_file(filname, mnt_name="flux")

    which would look up the right monitor from the mnt_name, figure out its index in the dataset and the proper data type and call the proper .from_file() method.

So looks like we just need a wrapper to provide the above behavior.

**Comment by tylerflex** [comment]
I can take a stab at this
