### ISSUE TITLE
improve the tidy3d to gdsfactory plugin

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#1254]
How can we improve the tidy3d to gdsfactory plugin?

- [x] support arbitrary layer stack
- [x] any mode to any mode Sparameters, for example a polarization splitter rotator
- [ ] implement file cache to avoid running same simulation twice https://github.com/flexcompute/tidy3d/issues/936
- [ ] improve docs
- [ ] deprecate old plugin

@jan-david-fischbach 
@daquinteroflex 
@yaugenst 

https://github.com/gdsfactory/gplugins/pull/138

**Comment by momchil-flex** [comment]
Hey @joamatab, could you elaborate on the second point? This is certainly possible in Tidy3D, we have many examples about polarization rotation ([e. g. this one](https://docs.flexcompute.com/projects/tidy3d/en/latest/notebooks/90BendPolarizationSplitterRotator.html)), so I guess it's a matter of opening it up in the gtidy3d API. Can you show us an example workflow that you want to work with Tidy3D? Maybe even set up a script that you wish would work and then we can make it work. :)

**Comment by joamatab** [comment]
ideally we expose the gdsfactory plugin to get the Sparameters from any mode to any mode,

at the moment it only supports the fundamental mode

https://gdsfactory.github.io/gplugins/_autosummary/gplugins.tidy3d.write_sparameters.html#gplugins.tidy3d.write_sparameters

**Comment by yaugenst** [comment]
Hey @joamatab, both arbitrary mode specifications and layer stacks are supported in the reworked tidy3d plugin. It uses the ComponentModeler under the hood.

**Comment by momchil-flex** [comment]
That's great @yaugenst ! When do you think this could be ready for a merge? Do you need any help?

**Comment by yaugenst** [comment]
Actually I just updated it, in principle gdsfactory/gplugins#138 is ready to merge, but examples and tests are still missing.

**Comment by joamatab** [comment]
I made some improvements

but the 2D simulations for a straight waveguide show 3dB loss

![image](https://github.com/flexcompute/tidy3d/assets/4514346/a65e71b8-357b-4a30-8460-3a406f9e24a1)

**Comment by momchil-flex** [comment]
Previously a common reason for this has been to not specifically set the z-direction boundaries to `Periodic`. This is so far only a warning. In the upcoming version, it will be an error (simulation 0 size + PML along that direction). See if that's the issue here.

**Comment by yaugenst** [comment]
@joamatab there is no waveguide in the simulation: 
![screenshot_20231120_160709](https://github.com/flexcompute/tidy3d/assets/1576526/5349cd22-99c8-467a-88fd-77d355fc58b4)

are you simulation the correct z slice?

@momchil-flex yes we are aware of this, this is handled correctly [here](https://github.com/gdsfactory/gplugins/blob/269691799d68129adb3149cd63cb154d233e6284/gplugins/tidy3d/component.py#L281)

**Comment by yaugenst** [comment]
@joamatab try setting [`center_z`](https://github.com/gdsfactory/gplugins/blob/c1f7ee554ffc11307d6cdbe8647e3876d73fd288/gplugins/tidy3d/component.py#L420) to the name of the layer you are trying to simulate

**Comment by joamatab** [comment]
i do see the waveguide

![image](https://github.com/flexcompute/tidy3d/assets/4514346/ecd34c99-2af6-4d08-b450-c47624e2386a)

**Comment by yaugenst** [comment]
i'm guessing this comes from `modeler.plot_sim(z=c.get_layer_center("core")[2], ax=ax[0])`? the layer center in z is explicitly passed here, which is why it shows up in the plot

**Comment by joamatab** [comment]
that worked great,

thank you Yannick!

![image](https://github.com/flexcompute/tidy3d/assets/4514346/e665140b-b096-48f1-aaa7-a560c5d9e3a7)

**Comment by yaugenst** [comment]
maybe this is a bit confusing, but i'm not sure how to automatically determine the "best" layer to simulate in a layer stack, since it is inherently a 3D thing, and there can be multiple layers that contain polygons. maybe we can automatically set z in a 2d simulation if there is only onw layer that contains (nontrivial) polygons...

**Comment by yaugenst** [comment]
maybe this is a bit confusing, but i'm not sure how to automatically determine the "best" layer to simulate in a layer stack, since it is inherently a 3D thing, and there can be multiple layers that contain polygons. maybe we can automatically set z in a 2d simulation if there is only onw layer that contains (nontrivial) polygons...
