### ISSUE TITLE
ValidationError: 1 validation error for PolySlab

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#1257]
How can we merge polygons in Component modeller?

im trying to simulate a coupler and because it's made of different polygons

![image](https://github.com/flexcompute/tidy3d/assets/4514346/3be38fd3-911e-446e-80a2-fad26fefad8e)

```
ValidationError: 1 validation error for PolySlab
vertices
  Sidewall angle or structure thickness is so large that the polygon is self-intersecting during extrusion. Please either reduce structure thickness to be < 2.847e+00, or use our plugin 'ComplexPolySlab' to divide
 the complex polyslab into a list of simple polyslabs. (type=value_error.setup)

```

**Comment by momchil-flex** [comment]
Try using `td.Geometry.from_gds`. It should automatically handle everything. For example (at the end of this [tutorial](https://docs.flexcompute.com/projects/tidy3d/en/v2.5.0rc2/notebooks/SelfIntersectingPolyslab.html)):

```
geo = td.Geometry.from_gds(
    cell,
    gds_layer=0,
    axis=2,
    slab_bounds=(0, 1),
    sidewall_angle=np.pi / 4,
    reference_plane="top",
)
```

**Comment by momchil-flex** [comment]
Let me know if this works and we can close the issue!

**Comment by joamatab** [comment]
yes, fixed by https://github.com/gdsfactory/gplugins/pull/239
