### ISSUE TITLE
Plot EPS not showing JaxStructures

### ISSUE THREAD

**Issue by txdai** [flexcompute/tidy3d#1258]
**Describe the bug**
When calling plot eps for simulations that contains Jax structures, these structures are not shown

**To Reproduce**
Run the code from [https://www.flexcompute.com/tidy3d/learning-center/inverse-design/Inverse-Design-in-Photonics-Lecture-4-Fabrication-Constraints/](url) up to input6, and see the plot

**Expected behavior**

![](https://www.flexcompute.com/assets/images/inverse-design/Lecture_04/Python_Tutorial_04_1.png)

**Screenshots**
<img width="734" alt="image" src="https://github.com/flexcompute/tidy3d/assets/110982256/b5b36f0e-164f-4064-a775-fe25d47f5044">

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by tylerflex** [comment]
@txdai could you also let me know what version of matplotlib and shapely you are using? You could either paste the results of `pip freeze` or just find them through `pip show matplotlib` and `pip show shapely`. Thank you!

**Comment by txdai** [comment]
Thanks, I was using matplotlib 3.4.3. I have upgraded to 3.8.0 and it works now.
