### ISSUE TITLE
Add a phase parameter to frequency-domain monitor data.

### ISSUE THREAD

**Issue by e-g-melo** [flexcompute/tidy3d#1261]
**Is your feature request related to a problem? Please describe.**
In our meetings with professors interested in the teaching program, they frequently ask how to create field animations using Tidy3d. 

**Describe the solution you'd like**
Currently, we have the FieldTimeMonitor, which allows us to create time-domain animations easily. However, animating the frequency-domain fields would be nice and less memory-intensive for teaching purposes. For example, to show how the waves propagate from a point-dipole source, we could animate the field phase, like below:

![dip_anim](https://github.com/flexcompute/tidy3d/assets/125516370/867310bf-3d85-4e8e-8a3c-4a2413955064)

**Describe alternatives you've considered**
It is possible to get the field components from the FieldData object, change the phase, and create an animation. However, a built-in feature would help Tidy3D beginners.

**Additional context**
Other field animation example from mode data:
![mode_anim](https://github.com/flexcompute/tidy3d/assets/125516370/d82a04e4-58a5-4338-bf93-de0e424ea850)

**Comment by momchil-flex** [comment]
I am a bit confused by the title of this issue vs. what it's asking for. Are you suggesting a convenience method to create the entire animation, like a `FieldData.animate(...)`? Or what do you mean by "add a phase parameter"?

**Comment by momchil-flex** [comment]
Assigning @tylerflex so that someone is on this, but feel free to reassign if you want.

**Comment by tylerflex** [comment]
@e-g-melo could you explain what the API should look like for adding a phase parameter? like 

```py
field_data = field_data.apply_phase(phase)
```
or something directly stored in the field data? like `FieldData(..., phase=1.0)` that we can modify with `updated_copy()`?

**Comment by e-g-melo** [comment]
We could include a phase parameter in the `plot_field` function for both FDTD and ModeSolver data, like below:

```
sim_data.plot_field("field", "Ex", "real", y=0.0, f=200e12, eps_alpha=0.2, phase=phase)
```

```
mode_solver.plot_field("Ex", "real", mode_index=0, f=freq0, ax=ax, phase=phase)
```

And include a function like the `apply_phase(phase)` as well to allow for custom plots or whatever the user wants to do.

```
mode_data_1 = mode_data.apply_phase(phase)
mode_data_1.Ex.isel(mode_index=0, f=freq0)).real.plot(x="x", y="z", ax=ax, cmap="RdBu")
```

```
field_data_1 = field_data.apply_phase(phase)
Ez_data = field_data_1.Ez.isel(y=0).interp(f=freq0)
Ez_data.real.plot(x="x", y="z", cmap="bwr", ax=ax)
```

**Comment by tylerflex** [comment]
@e-g-melo I made a solution here, please give it a test when you get a chance thanks.
https://github.com/flexcompute/tidy3d/pull/1271

**Comment by e-g-melo** [comment]
Wow! That was fast! 

I will try it. Thanks!

**Comment by tylerflex** [comment]
actually need to fix one thing, give me a sec

**Comment by tylerflex** [comment]
should be working now

**Comment by tylerflex** [comment]
Fixed by https://github.com/flexcompute/tidy3d/pull/1271
