### ISSUE TITLE
add `ComponentModeler.plot_eps()`

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#1264]
I find the epsilon plots more useful than current plots in ComponentModeller

before you can see nitride above

![image](https://github.com/gdsfactory/gplugins/assets/4514346/246c45cb-7927-484b-8f2c-16ef40748755)

now you can see one or the other

![image](https://github.com/gdsfactory/gplugins/assets/4514346/87c06d4c-b80b-4c3f-9fc4-58cdd7ddf82e)

the main issue is that td.ComponentModeler does not have `plot_eps` method

How about adding `ComponentModeler.plot_eps`?

https://github.com/gdsfactory/gplugins/issues/243

**Comment by momchil-flex** [comment]
I think you're looking at the wrong side, your second plot is at x = -3.8 where you have only one waveguide.

Still, we could add `.plot_eps` for convenience @tylerflex @lucas-flexcompute ?

**Comment by joamatab** [comment]
yes, im showing different ports in each simulation :)

i was trying to show that i find epsilon is more useful in some cases

**Comment by momchil-flex** [comment]
Oh you mean you just wanted to show that you can visually identify the media? Yeah that's nice.

**Comment by momchil-flex** [comment]
But your comment does sound like you're saying you can see "one or the other". Even with .plot you can see both if you plot a cross section in which there's both.

**Comment by joamatab** [comment]
yes, this is a simple example from the gdsfactory generic PDK, with only 3 materials (silicon, nitride, oxide)

but if you add a complex foundry layerStack is nice to see that the refractive index numbers look correct

**Comment by tylerflex** [comment]
So just this method but an epsilon version?

https://github.com/flexcompute/tidy3d/blob/develop/tidy3d/plugins/smatrix/smatrix.py#L299C1-L309C51

**Comment by tylerflex** [comment]
see https://github.com/flexcompute/tidy3d/pull/1269
