### ISSUE TITLE
Requests for material library

### ISSUE THREAD

**Issue by Frank-DingYC** [flexcompute/tidy3d#1268]
## Request1: Add 2 material in material library
- Current: When user search material library for "Vacuum" and "Air", he/she will find there is no such thing in our material library.
-  Expect: add 2 materials in material library
- [x] "Vacuum" (permittivity = 1, conductivity = 0)
- [x] "Air"(permittivity = 1.0002, conductivity = 0) 

## Request2: Rename material in material library
- Current: When user search for “Silicon”, they expect to see “Silicon” as the first letter, however they usually find other materials such as Silicon Dioxide, etc., instead of silicon materials
- Expect:
- [ ] Amorphous Silicon (“aSi”) → Silicon (Amorphous) (“aSi”)
- [ ] Crystalline Silicon (“cSi”) → Silicon (Crystalline) (“cSi”)

![image](https://github.com/flexcompute/tidy3d/assets/150003482/45da829a-33a8-4c17-aaee-35e3bc6ee984)

**Comment by Frank-DingYC** [comment]
Hello @weiliangjin2021 @tylerflex ~ There is a small request for material library change to better our gui client user experience. Hopefully, you can help with us.

**Comment by weiliangjin2021** [comment]
Good point @Frank-DingYC! I can work on it if @tylerflex hasn't started.

**Comment by tylerflex** [comment]
I have not, thanks @Frank-DingYC and @weiliangjin2021

**Comment by Frank-DingYC** [comment]
OK~ if you have finished this part, please inform us~ thx~ @weiliangjin2021

**Comment by weiliangjin2021** [comment]
@Frank-DingYC do you have a reference for air? I only find [this one](https://www.engineeringtoolbox.com/relative-permittivity-d_1660.html) where the air permittivity is 1.000536. I also wonder what frequency range should be.

**Comment by Frank-DingYC** [comment]
@weiliangjin2021 I talked with xin and we thought request1 should be added in web client. Since the library in python client contains complex dispersive materials, there is no need to add "air" and "vacuum" in python library~
