### ISSUE TITLE
threading issues

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#1276]
using the new tidy3d-gdsfactory plugin for the multi-job submission we get submission failures that trigger 180 seconds (3 min) waiting times
we believe the threading from tidy3d is interfering with the gplugins threading

How can we make sure retrieving the simulations does not time out?

You can reproduce by running this [notebook](https://gdsfactory.github.io/gplugins/notebooks/workflow_3_cascaded_mzi.html) and all relevant plugin code is [here](https://github.com/gdsfactory/gplugins/blob/main/gplugins/tidy3d/component.py)

The problematic part of the notebook is here

```python

sims = gt.write_sparameters_batch(
    [
        {
            "component": coupler_sc(gap=gap, length=length),
            "filepath": PATH.sparameters_repo / f"dc_{length}.npz",
        }
        for length in lengths
    ],
    layer_stack=layer_stack,
    # overwrite=True,
)

s_params_list = [sim.result() for sim in sims]
```

@yaugenst 
@lucas-flexcompute 
@momchil-flex 
@tylerflex

**Comment by yaugenst** [comment]
![screenshot_20231129_164327](https://github.com/flexcompute/tidy3d/assets/1576526/1999e32f-06dc-4898-a2d8-fd99a96c34c0)

**Comment by joamatab** [comment]
this seems to avoid the issue

```python

sims = gt.write_sparameters_batch(
    [
        {
            "component": coupler_sc(gap=gap, length=length),
            "filepath": PATH.sparameters_repo / f"dc_{length}.npz",
        }
        for length in lengths
    ],
    layer_stack=layer_stack,
)

s_params_list = [[]]
for sim in sims:
    time.sleep(0.1)
    s_params_list.append(sim.result())
```

**Comment by joamatab** [comment]
this makes it so that simulations can take very long time, see one here that should finish in 1 minute is still running after 75minutes

![image](https://github.com/flexcompute/tidy3d/assets/4514346/89d49957-337e-4735-820e-f7cc67cfd567)

**Comment by joamatab** [comment]
this is another error that happens sometimes

![image](https://github.com/flexcompute/tidy3d/assets/4514346/a5957a4f-629e-47d7-b2ad-88c53d7c3ca0)

**Comment by tylerflex** [comment]
I think I encountered some weirdness like this when implementing `run_async` with `asyncio` and `multithreading`, adding `sleep()` did help. I think it's ultimately related to how our files are uploaded with `boto3`, there must be something causing an issue.

Can you provide us with some details about how you're doing the multithreading with the gdsfactory plugin? and what you're using for the webapi? You might want to consider using `[tidy3d.web.run_async](https://docs.flexcompute.com/projects/tidy3d/en/latest/_autosummary/tidy3d.web.run_async.html)` if possible

**Comment by joamatab** [comment]
Im using your component modeler,

can you add `run_async` to it?

[Here](https://github.com/gdsfactory/gplugins/blob/main/gplugins/tidy3d/component.py) is all the relevant code on the gdsfactory plugins side

**Comment by yaugenst** [comment]
what is happening is that we have a bunch of componentmodelers that are being submitted via threading here: https://github.com/gdsfactory/gplugins/blob/3f615c905cf8a4d91e8a7708ff4dd79d79eef064/gplugins/tidy3d/get_results.py#L17

the componentmodelers each assemble their own batch to submit. is there another way to submit batches of batches?

**Comment by joamatab** [comment]
i added sleep statement after each threaded submission and does not really help

another thing that may be causing issues is that we call the batch differently?

**Comment by tylerflex** [comment]
My feeling is that the issue might be that if two tasks are submitted at close to exactly the same time, it could be confusing our web API handling.

**Comment by tylerflex** [comment]
if you can nail down a very simple test (outside of gdsfactory) that reproduces the issue I can pass it onto the people who work on the web API to investigate. In the meantime, we could look into generalizing the batch handling more. This is on our roadmap but we could bump the priority
