### ISSUE TITLE
Enabling medium index option for field projection monitors

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#1287]
Current field projection assumes the medium of the projected region has the same index as that at the location of the monitor. Some users would like to have the option to manually define the refractive index for the projected region. This is not physically rigorous but can be convenient to have as a good approximation in some cases.

**Comment by momchil-flex** [comment]
How would this work practically? For example, after computing the far field in the homogeneous medium, we can apply a single interface scattering matrix (i.e. disregarding back-reflections that could in practice happen)? This can even be done by the user already fairly straightforwardly I think, if they need it right now?

**Comment by momchil-flex** [comment]
FYI: https://optics.ansys.com/hc/en-us/articles/360034395194

**Comment by tomflexcompute** [comment]
> How would this work practically? For example, after computing the far field in the homogeneous medium, we can apply a single interface scattering matrix (i.e. disregarding back-reflections that could in practice happen)? This can even be done by the user already fairly straightforwardly I think, if they need it right now?

Something like this is even better. I was just thinking about something more rudimentary, which is what the user was asking for. See [here](https://optics.ansys.com/hc/en-us/articles/360034410214-farfieldexact-Script-command).

**Comment by momchil-flex** [comment]
Actually the link I sent above discusses the difference between the two approaches mentioned here. :)

**Comment by tomflexcompute** [comment]
Artificially setting the index to a different value certainly will cause some artificial results. In some cases however, it can still be a good approximation. For example, imagine a large grating coupler with a few microns of oxide cladding. The simulation domain can only contain oxide to save cost but when projecting the near field field to far away, say hundreds of microns, setting the `background_index=1` will be much more accurate then `background_index=n_oxide`. Sure there will be some small offset due to the finite oxide thickness and some intensity difference due to reflection, but for a quick estimation for the beam spot position and size it's actually pretty good.

**Comment by momchil-flex** [comment]
Yeah, so let's just do that change which should be pretty small and not worry about the "Fresnel correction" for now (which can be a post-processing script eventually).

**Comment by tomflexcompute** [comment]
> Yeah, so let's just do that change which should be pretty small and not worry about the "Fresnel correction" for now (which can be a post-processing script eventually).

Sounds good. One user is waiting to use it so would be great if we can get it in a near future release. Thanks @shashwat-sh in advance!
