### ISSUE TITLE
Mode solver data support

### ISSUE THREAD

**Issue by Frank-DingYC** [flexcompute/tidy3d#1294]
## Current
Our mode solver only support the following data:
- Mode field
- Effective index
- Group index
## Expect
We hope the solver can offer the following data:
- Group velocity [from Lukas book]:
  - $v_p(\lambda)=\frac{c}{n_{eff}}$, $v_g(\lambda)=\frac{c}{n_g}$
- Group velocity dispersion parameter $D$ [from Lukas book]:
  - $D(\lambda)=-\frac{\lambda}{c}\frac{d^2n_{eff}}{d\lambda^2}$
- Group velocity dispersion parameter $\beta_2$ [from Agrawal book]:
  - $\beta_2=\frac{1}{c}\left(2\frac{dn}{d\omega}+\omega\frac{d^2n}{d \omega^2} \right)$
  - $D=\frac{\beta_1}{\lambda}=-\frac{2\pi c}{\lambda^2}\beta_2=-\frac{\lambda}{c}\frac{d^2n}{d\lambda^2}$

**Comment by momchil-flex** [comment]
- Group velocity: this is simply a matter of `td.C_0 / mode_data.ng`, so it's readily available. I don't think we should do anything about this except maybe add it in our examples somewhere.

Regarding the other two, @lucas-flexcompute would I be correct to say that we can store the second derivative of `n_eff` essentially for free whenever we're doing an `n_g` calculation? We already do a centered derivative right? So we could also use the finite difference formula for second derivative without extra solves?

**Comment by lucas-flexcompute** [comment]
In principle, yes, and it should have the same degree of accuracy. I can't say in practice. I often have to help users who find our results too different from other software and instruct them to greatly increase mesh refinement.

**Comment by Superwbb1999** [comment]
> * Group velocity: this is simply a matter of `td.C_0 / mode_data.ng`, so it's readily available. I don't think we should do anything about this except maybe add it in our examples somewhere.组速度：这只是 `td 的问题。C_0 / mode_data.ng`，因此它很容易获得。我认为我们不应该对此做任何事情，除了可能将它添加到我们的例子中的某个地方。
> 
> Regarding the other two, [@lucas-flexcompute](https://github.com/lucas-flexcompute) would I be correct to say that we can store the second derivative of `n_eff` essentially for free whenever we're doing an `n_g` calculation? We already do a centered derivative right? So we could also use the finite difference formula for second derivative without extra solves?关于其他两个，我是否可以说，每当我们进行 `n_g` 计算时，我们基本上可以免费存储 `n_eff` 的二阶导数？我们已经做了一个中心导数，对吧？那么我们也可以对二阶导数使用有限差分公式，而无需额外的求解？

May I ask if the 'n_g' here is the 'n_group.data' in the 'mode_data'?

**Comment by momchil-flex** [comment]
That's right.
