### ISSUE TITLE
Proofread docs

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#130]
Please go through the [docs](https://flexcompute-tidy3ddocumentation.readthedocs-hosted.com/en/latest/) and note if there are any typos, things not explained well, mistakes.

Some notes so far.
- [ ] "How do I" needs a bit of proofreading (.json and hdf5 use sometimes inconsistent)

**Comment by tylerflex** [comment]
This is great, thank you!  I'm embarrassed there were so many typos..

**Comment by shashwat-sh** [comment]
They're pretty negligible relative to how thorough the docs are!
