### ISSUE TITLE
pip install tidy3d failing on M1 Mac

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#1301]
due to gdstk not working on M1 or M2, tidy3d does not work on Mac M1 or M2

https://github.com/heitzmann/gdstk/issues/199

@tylerflex 
@lucas-flexcompute

**Comment by tylerflex** [comment]
For reference, I am using `gdstk == 0.9.37` on a Mac M2 and it works for me. Any version after that seems to break. Also `tidy3d` will generally work as long as you aren't using any methods that require `gdstk`.

Perhaps we should pin a `gdstk <= 0.9.37` requirement for Mac users until it gets sorted out. @daquinteroflex what do you think?

**Comment by joamatab** [comment]
I think pinning an old version of a tool is bad practice :) For example, in gdsfactory we use some of the new gdstk features that were released post 0.9.37, such as remapping layers.

can you guys try this solution on gdstk and see if we can make it work on the latest versions?

 https://blog.tim-smith.us/2015/09/python-extension-modules-os-x/

**Comment by tylerflex** [comment]
@joamatab just to clarify, `pip install tidy3d` should work on M2, just not `pip install tidy3d[gdstk]`, correct?

**Comment by tylerflex** [comment]
Fixed in gdstk 0.9.49

**Comment by tylerflex** [comment]
@daquinteroflex let's pin that version or above in our upcoming 2.6 releases? thanks!
