### ISSUE TITLE
Lazy import of heavy dependencies

### ISSUE THREAD

**Issue by momchil-flex** [flexcompute/tidy3d#1304]
Currently, a lot of packages are imported that in many cases are not needed. This can, among other things, hurt our server throughput, especially for very large numbers of very small jobs. We should set up a way to only import such packages when needed. For some packages, we currently check if they are *installed*, and avoid errors if they are not, but they are not needed for a given task. However, that means that when they *are* installed, they still get imported and slow everything down.

In #1300, @dbochkov introduced such lazy import of `vtk`. We need to probably polish this a bit further, and then start doing that for a number of other packages too: scipy, trimesh, gdspy, gdstk, jax, and maybe more.

**Comment by daquinteroflex** [comment]
Is this priority for the 2.5 release? I can jump on this now if urgent

**Comment by momchil-flex** [comment]
It's not blocking (can get in a patch) but I see it as fairly important in our overall effort to speed up small job throughput.

**Comment by tylerflex** [comment]
can this be closed?
