### ISSUE TITLE
Invalid link for `from_url` example in docs

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#1336]
In the [docs page](https://docs.flexcompute.com/projects/tidy3d/en/latest/_autosummary/tidy3d.plugins.dispersion.FastDispersionFitter.html?highlight=from_url#tidy3d.plugins.dispersion.FastDispersionFitter.from_url) about the `from_url` class method, it lists an example page 
<img width="320" alt="image" src="https://github.com/flexcompute/tidy3d/assets/116006359/799acf22-8147-4b00-a7b4-bc11fc97e697">

This page can not be open in the browser, nor does it work when using it in the code 
<img width="631" alt="image" src="https://github.com/flexcompute/tidy3d/assets/116006359/9ed36db8-2985-43e2-86e6-bc3677f9a765">

I'm a bit confused about where to find the correct link from refractiveindex.io in general. I can find links like https://refractiveindex.info/database/data-nk/main/Fe/Johnson.yml but it doesn't work for `from_url` either.

**Comment by tomflexcompute** [comment]
I see that there is a test for `from_url` in test_dispersion_fitter.py using some mock data. Maybe it's worth it to have another test using data directly from refractiveindex.io?

**Comment by weiliangjin2021** [comment]
The link in the doc page is outdated: it should be https://refractiveindex.info/data_csv.php?datafile=database/data-nk/main/Ag/Johnson.yml

> I'm a bit confused about where to find the correct link from refractiveindex.io in general. I can find links like https://refractiveindex.info/database/data-nk/main/Fe/Johnson.yml but it doesn't work for from_url either.

So the url is the link to a csv/txt file. For your Fe case, the url is https://refractiveindex.info/data_csv.php?datafile=database/data-nk/main/Fe/Johnson.yml

**Comment by tomflexcompute** [comment]
It seems like refractiveindex.io updates their website links from time to time.

**Comment by tomflexcompute** [comment]
When I click this `[CSV - comma separated]` button it directly downloads the csv file without opening a new page. Clicking the `[Full database record]` button does open a webpage with data. Does `from_url work` with this page?

<img width="343" alt="image" src="https://github.com/flexcompute/tidy3d/assets/116006359/334b9b3d-4a16-4331-89ec-b03d08d3d6b1">

<img width="1252" alt="image" src="https://github.com/flexcompute/tidy3d/assets/116006359/949fffce-55cd-4626-9e08-589a172aca54">

**Comment by weiliangjin2021** [comment]
> When I click this [CSV - comma separated] button it directly downloads the csv file without opening a new page. Clicking the [Full database record] button does open a webpage with data. Does from_url work with this page?

The webpage you mentioned seems to be in yml format. So `from_url` doesn't work with it directly. Let me think about it how to support it.

**Comment by tylerflex** [comment]
just going through open issues. was this one ever fixed?

**Comment by weiliangjin2021** [comment]
> just going through open issues. was this one ever fixed?

not yet, let me push a fix to update the URL
