### ISSUE TITLE
add `ModeSolver.plot`

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#1397]
Would be nice to have a simple method to visualize the `ModeSolver` plane within the simulation, perhaps with a different color than a regular monitor or source.

**Comment by momchil-flex** [comment]
Also to visualize the plane cross-section (media/epsilon)

**Comment by momchil-flex** [comment]
@e-g-melo this is related to you working on a 2D plot of the mode solver that also shows the PML right?

**Comment by e-g-melo** [comment]
Hi @momchil-flex! Yes, it is.

**Comment by tylerflex** [comment]
@e-g-melo did your PR fix this issue? just checking in

**Comment by e-g-melo** [comment]
That PR allows you to plot the mode plane defined on `ModeSolver`. However, it won't include plotting the mode plane within the `Simulation` domain.

**Comment by e-g-melo** [comment]
Not sure if that is necessary, right?

**Comment by tylerflex** [comment]
I think it's ok and we can reopen if it's requested.
