### ISSUE TITLE
validate no nans in CustomMedium

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#1402]
Seems like we should catch this before it gets uploaded.

Also, we might want to consider simply validating it out of any DataArray values?

**Comment by momchil-flex** [comment]
> Also, we might want to consider simply validating it out of any DataArray values?

Yeah I think that makes sense.

**Comment by tylerflex** [comment]
It might break some notebooks if they contain nan in the diffraction data. So I'm a little worried about doing it generally like this

**Comment by tylerflex** [comment]
But definitely we should exclude them in custom medium (which is what silently passed and led to this error).

**Comment by momchil-flex** [comment]
> It might break some notebooks if they contain nan in the diffraction data. So I'm a little worried about doing it generally like this

Oh I see good point currently diffraction data can often contain nan. What about just excluding it in all custom components, CustomMedium, CustomFieldSource, CustomCurrentSource? They will likely lead to errors.

**Comment by tylerflex** [comment]
yea, I think in all custom components would be the best

**Comment by momchil-flex** [comment]
This can be closed?
