### ISSUE TITLE
questionnaire feedback

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#1408]
- [x] #1409
- [x] #1410
- [x] #1411
- [x] #1412
- [x] #1413
- [ ] #1414
- [x] #1415
- [x] #1416
- [x] #1417
- [x] #1418

**Comment by tylerflex** [comment]
since only #1414 is left, doesn't make sense to leave both open

**Comment by ozzymarley** [comment]
@tylerflex Hi, may I know is it support permeability now? I also wanna define a permeability tensor. Thanks.

**Comment by tylerflex** [comment]
Hi @ozzymarley I'll direct you to #1415 , @weiliangjin2021 can provide some context there.

**Comment by ozzymarley** [comment]
Thanks for your reply. I will follow #1415.

> Hi [@ozzymarley](https://github.com/ozzymarley) I'll direct you to [#1415](https://github.com/flexcompute/tidy3d/issues/1415) , [@weiliangjin2021](https://github.com/weiliangjin2021) can provide some context there.
