### ISSUE TITLE
Test the UI

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#141]
Need to make sure the UI is a decent state before releasing the URL. Ask me for url so it's not public here.

Please mess around there a bit and see if you notice any bugs you can report them here.

https://flow360.atlassian.net/jira/software/c/projects/SCEM/issues

Let's just put our comment here.

**Comment by shashwat-sh** [comment]
I've requested access to jira, but in the mean time, I'll just put stuff here:

- [ ] I think the visibility checkmark for "sources" is inverted - the green rectangle appears by default even though "sources" is unchecked, but disappears when "sources" is checked
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/97917222/151878738-afaf6d68-59d2-441e-82e2-54bc999f1045.png">

**Comment by tylerflex** [comment]
Yea, known issue unfortunately. thanks.  I'll report it again.

**Comment by weiliangjin2021** [comment]
A 2D simulation can look horrible in the interative 3D. It will take some efforts to lock the view to that 2D plane. Should we switch to interative 2D if the simulation is found to be 2D.
