### ISSUE TITLE
Permeability support?

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#1415]

**Comment by weiliangjin2021** [comment]
We might eventually support permeability in the context of RF

**Comment by xiaohan-phys** [comment]
@weiliangjin2021 Hi, may I know is it support permeability now? I hope to define a permeability tensor in an anisotropic material.

**Comment by weiliangjin2021** [comment]
> Hi, may I know is it support permeability now? I hope to define a permeability tensor in an anisotropic material.

Hi @xiaohan-phys, it's on our roadmap. Is the permeability tensor diagonally anisotropic, or fully anisotropic?

**Comment by xiaohan-phys** [comment]
> > Hi, may I know is it support permeability now? I hope to define a permeability tensor in an anisotropic material.
> 
> Hi [@xiaohan-phys](https://github.com/xiaohan-phys), it's on our roadmap. Is the permeability tensor diagonally anisotropic, or fully anisotropic?

@weiliangjin2021 Thanks a lot. Gyromagnetic tensor with off-diagonal terms.

**Comment by weiliangjin2021** [comment]
> [@weiliangjin2021](https://github.com/weiliangjin2021) Thanks a lot. Gyromagnetic tensor with off-diagonal terms.

We are planning to support regular magnetic materials (isotropic and then diagonally anisotropic response; and both non-dispersive and dispersive) first; and after that gyrotropic.
