### ISSUE TITLE
Example with scattering in simple hydrodynamic fluid motion with small particles

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#1432]

**Comment by tylerflex** [comment]
@tomflexcompute if this is simply not achievable, we can just close it.

**Comment by tomflexcompute** [comment]
> @tomflexcompute if this is simply not achievable, we can just close it.

Thanks. Need to do a bit research on it. Maybe it's doable.

**Comment by tomflexcompute** [comment]
Couldn't really find much information on this topic. Should be a very niche problem. I'll close the issue for now but we can reconsider it if we get more reference.

**Comment by tylerflex** [comment]
I think that's reasonable
