### ISSUE TITLE
Old documentation in website causing errors (links?)

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#1433]
users switching between 2.6 and previous get errors I think in the website URLs but maybe also in the class definition links?

**Comment by daquinteroflex** [comment]
So there's a few things here:
* The new docs is a completely new website structure, so actually old links won't be equivalent to new links. I'm afraid I can't fix this but we have improved the 404 now with a link to make a Github issue of what happened.
* I've been hunting down broken links but nontrivial to be sure all are sorted, so am doing it progressively now throughout the docs. Before we release I intend to do a full website sweep manually

**Comment by tylerflex** [comment]
closing this since it's probably not a big issue anymore now that we're > 2.6
