### ISSUE TITLE
sim.plot_structures no longer plotting right.

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#1442]
A user found that in 2.5.2, sim.plot_structures no longer finds the right bounds while sim.plot works well. 

According to Weiliang, it's potentially related to the introduction of `scene`. Do you think it's the case @dbochkov-flexcompute ? If so, can we fix it in the next version?

**Comment by dbochkov-flexcompute** [comment]
wanted to double check one thing: before 2.5.0 (when scene was introduced), `.plot_structures()` and `.plot_structures_eps()` would select plotting domain as simulation size + PLOT_BUFFER (the same default buffer when we plot individual geometries). However, I am not sure if this was intended as I see that default plot bounds are set to simulation size + PML size when this line is executed https://github.com/flexcompute/tidy3d/blob/f60bf47f84264bc622e548fa41dfc344fb85ceaf/tidy3d/components/simulation.py#L1587
but then this is overwritten a few lines later which sets plotting bounds as simulation size + PLOT_BUFFER https://github.com/flexcompute/tidy3d/blob/f60bf47f84264bc622e548fa41dfc344fb85ceaf/tidy3d/components/simulation.py#L1591

The difference is very minor, but still wanted to double check what I should set the default plotting domain to? I guess options are:
- simulation size + PLOT_BUFFER
- simulation size + PML size
- simulation size

**Comment by tomflexcompute** [comment]
Thanks @dbochkov-flexcompute . I don't have a very strong opinion on this but simulation size + PML size makes sense to me but I'll have @momchil-flex and others share their thoughts.

**Comment by momchil-flex** [comment]
I don't really remember what the `PLOT_BUFFER` was for - maybe @tylerflex does. size + PML size also makes sense to me.

**Comment by tylerflex** [comment]
yea I think blot buffer was from way long ago and we can just do size + PML
