### ISSUE TITLE
FieldProjectionKSpaceMonitor has limited ux and uy ranges

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#1476]
When defining a FieldProjectionKSpaceMonitor, one needs to specify ux and uy. Over often users would like to plot the far-field scattering as a function of ux and uy for the range of -1 to 1. However we currently have a limit that ux*2 + uy*2 <1, which makes sense but it causes some usability inconvenience as one couldn't explore the entire accessible k space in one monitor. 

Would it be possible to allow ux*2 + uy*2 >1 so that users can define ux = np.linspace(-1,1) and uy=np.linspace(-1,1)? Any points with ux*2 + uy*2 >1 will have zero field values.

**Comment by momchil-flex** [comment]
I don't think we limit it in this way. [This validator](https://github.com/flexcompute/tidy3d/blob/722ebe641a0faaff6cd6f56cb2349a3d5adc7430/tidy3d/components/monitor.py#L1009-L1019) just checks that each of ux and uy is betweehn -1 and 1 as requested. Is there some other issue that users are experiencing for the points outside the light cone?

**Comment by tomflexcompute** [comment]
So I set the monitor this way

```
k_monitor = td.FieldProjectionKSpaceMonitor(
    center=(0,0,1.2*h),
    size=(inf_eff,inf_eff,0),
    freqs=[freq0],
    name='k_monitor',
    proj_axis=2,
    ux=np.linspace(-0.99,0.99,100),
    uy=np.linspace(-0.99,0.99,100),
    )
```
and got the following:

RuntimeWarning: invalid value encountered in arcsin
  theta_local = np.arcsin(np.sqrt(ux**2 + uy**2))

**Comment by momchil-flex** [comment]
Ok, thanks, this is a bug rather than something we're explicitly validating. I'll fix.

**Comment by tomflexcompute** [comment]
Oh good to know... Thanks.

**Comment by momchil-flex** [comment]
I don't have your whole script but I tried this and got no error

```
k_monitor = td.FieldProjectionKSpaceMonitor(
    center=(0,0,1.2),
    size=(1, 1, 0),
    freqs=[1e14],
    name='k_monitor',
    proj_axis=2,
    ux=np.linspace(-0.99,0.99,100),
    uy=np.linspace(-0.99,0.99,100),
)
```
