### ISSUE TITLE
Direct user towards `tidy3d.log` if there are warnings or errors

### ISSUE THREAD

**Issue by momchil-flex** [flexcompute/tidy3d#1483]
In 2.6 `tidy3d.log` has been refactored to include all warnings raised by simulation validators, as well as extra backend warnings if applicable, e.g. in the case of diverged simulations. We should:

- [ ] After simulation run, display a warning to the user to check the log if any WARNING messages are found in the log.
- [ ] Make sure this also works for a diverged case. Consider directly displaying the log if diverged.
- [ ] Download and display the log (or ask user to have a look at it) in the case of an erroring simulation. In some cases there could be an error that the user could act on.
- [ ] Add tidy3d.log to the divergence email @tomflexcompute

**Comment by tomflexcompute** [comment]
Will all these be included in 2.6? When are we planning to release 2.6?
