### ISSUE TITLE
Automatically open tidy3d signup pages if auth fails

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#1487]
I think in addition to erroring, we could automatically open the signup page if the user isn't authenticated:

```
import webbrowser
webbrowser.open("https://tidy3d.simulation.cloud/signup")
```

additionally, there might be times we want to automatically open the web client
```
import webbrowser
webbrowser.open("https://tidy3d.simulation.cloud")
```

**Comment by momchil-flex** [comment]
Eh.. at first sight sounds a bit intrusive to me.

**Comment by tylerflex** [comment]
fair enough. When I was playing with the prefab notebook, they have this approach and it seemed pretty good but it was also just hardcoded into the notebook, maybe in the web API directly would be indeed a bit annoying.
