### ISSUE TITLE
Sort out `numpy` 2.0 release

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#1563]
Numpy version is currently not specified in our `pyproject.toml`. So the version will be largely determined by our dependencies.  Maybe a few potential pitfalls:
1. One of our dependencies wants numpy 2 and the other only works with numpy 1. In this case, I assume poetry / pip will just resolve this and install the lower versions such that numpy 1 versions are installed?
2. User upgrades to numpy 2 and some of our internal numpy code breaks?

I assume we really only need to worry about 2. There are some articles about upgrading
https://numpy.org/devdocs/numpy_2_0_migration_guide.html
https://pythonspeed.com/articles/numpy-2/#:~:text=NumPy%202%20is%20a%20new,might%20be%20required%20to%20upgrade.

We can go through and see if anything needs to get updated.

**Comment by momchil-flex** [comment]
What did we decide about this again?

**Comment by daquinteroflex** [comment]
I understand the plan is that we've fixed itn <2 until all our dependencies upgrade, and then upgrade ourselves
https://github.com/flexcompute/tidy3d/blob/14dcf5b953776e6b87624a7423e85bd4e56ea930/pyproject.toml#L30

**Comment by tylerflex** [comment]
Yea that's my understanding too. I think many of our dependencies don't  support numpy 2 so there's not much point in us supporting it yet.

**Comment by momchil-flex** [comment]
Ah ok we already did this so we can close this for now?

**Comment by daquinteroflex** [comment]
Sure, sounds good. We can reopen a new one for the proper migration
