### ISSUE TITLE
Adjoint mehod for metal optics

### ISSUE THREAD

**Issue by Guizhixing** [flexcompute/tidy3d#1567]
I tried to design a metal photonic device by using the adjoint method, but I found that few applid FDTD-based adjoint method for metal optics. 

Does the tidy3d project consider adding the adjoint sensitivity analysis code for metal photonics? 

FDTD is known to be inaccurate along interfaces (this has been remedied in the case of smooth dielectric boundaries but not for corners or metal-dielectric interfaces). Furthermore, the electromagnetic field at a sharp metal corner diverges, and divergent fields cannot be accurately represented by FDTD. The order of the divergence directly limits the rate of convergence of the field calculation, and the error is largest along interfaces between metals and dielectrics. Unfortunately, the adjoint sensitivity calculation for perturbing interfaces depends solely upon the interface electromagnetic fields. 

In my humble opinion, this is a challenging problem for which there are no neat solutions available. Do you all have any thoughts on how to solve this problem?

**Comment by tylerflex** [comment]
Hi @Guizhixing this is an important feature that we are working on currently, eg #1548 and https://github.com/flexcompute/tidy3d/pull/1333

In terms of the FDTD modeling of metallic interfaces, we have approaches to handle this more accurately through sub-pixel averaging. There is also much work on improving our absorbing boundaries to prevent divergence in such simulations. @weiliangjin2021 may be able to share more information.

In terms of adjoint, our shifting boundary approach to adjoint uses the fields at the interface. While it is working well for dielectric materials, it can be modified to metallic and dispersive materials. There are important technical issues in handling the dispersion in the adjoint method that we are still working through and testing, but I anticipate it should be completed in Q2 of 2024.

**Comment by Guizhixing** [comment]
@tylerflex I'm really looking forward to this feature and hope to try it soon.

**Comment by weiliangjin2021** [comment]
Hi @Guizhixing, you are right about the challenges for FDTD in terms of metallic boundary modeling. In Tidy3d, while we have accurate subpixel averaging around dielectric interfaces, the metallic interface is just staircased right now. So this year, we are working on more accurate metallic--dielectric interface modeling. In the upcoming 2.7.0, please expect better subpixel support for PEC boundary. In the next quarter, we'll probably roll out subpixel for good conductors as well.

**Comment by tylerflex** [comment]
Closing this issue as it is already tracked. But feel free to continue discussion

**Comment by Guizhixing** [comment]
> Hi @Guizhixing, you are right about the challenges for FDTD in terms of metallic boundary modeling. In Tidy3d, while we have accurate subpixel averaging around dielectric interfaces, the metallic interface is just staircased right now. So this year, we are working on more accurate metallic--dielectric interface modeling. In the upcoming 2.7.0, please expect better subpixel support for PEC boundary. In the next quarter, we'll probably roll out subpixel for good conductors as well.

Hi, @weiliangjin2021, I am wondering, does the subpixel method of PEC in the upcoming 2.7.0 version apply in adjoint sensitivity analysis of metal microwave structure?
