### ISSUE TITLE
improve mode_solver

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#1599]
At the moment the mode solver `RectangularDielectric` in tidy3d is somewhat to strip/rib

How can we use tidy3d mode solver to ?

- [ ] solve waveguides with varying refractive index
- [ ] solve multi-layer waveguides
- [ ] compute mode leakage to substrate
- [ ] plot lines corresponding to the interfaces between layers and sidewalls, so the mode profile is overlaid with the layer stack and geometry

**Comment by momchil-flex** [comment]
Related to #1628 

Generally all of those are possible now but not with the `RectangularDielectric` plugin. Not sure how much bandwidth Lucas will have but he's promised to implement some of these in the plugin.

**Comment by lucas-flexcompute** [comment]
The only request not covered by the PRs is mode leakage calculation, because that seems to be problem-dependent. I don't think we can provide a general and **robust** solution covering all cases for layered media…
