### ISSUE TITLE
add InGaAsP to material library

### ISSUE THREAD

**Issue by alec-flexcompute** [flexcompute/tidy3d#1621]
**Is your feature request related to a problem? Please describe.**
A user just asked if we can add InGaAsP to our material library, and supplied a paper with the data, found here: https://flow360.atlassian.net/browse/TID-652

**Comment by momchil-flex** [comment]
@alec-flexcompute I assigned you here, could you just try to do this yourself?

**Comment by alec-flexcompute** [comment]
sure

**Comment by alec-flexcompute** [comment]
Variable composition plays a big part in the dispersive behavior of this material, so I just wrote back to the customer how to do this on their own.
