### ISSUE TITLE
support upgrading .gz file

### ISSUE THREAD

**Issue by QingengWei** [flexcompute/tidy3d#1624]
Could you support upgrading .gz file?
https://github.com/flexcompute/tidy3d/blob/develop/tidy3d/updater.py#L86-L112

@tylerflex

**Comment by tylerflex** [comment]
Fixed by #1641. @magiWei  could you test that branch to see if it works for your use case?

**Comment by QingengWei** [comment]
@tylerflex  Yeah, I tested with your branch, and it works. If there are any wrong cases later, I will let you know.

**Comment by tylerflex** [comment]
great!
