### ISSUE TITLE
Multilayer waveguide plugin

### ISSUE THREAD

**Issue by smgitrep** [flexcompute/tidy3d#1628]
Tidy3d has strip and rib waveguide plugins that can be used with the modesolver, but are somewhat limited in scope.

Could these plugins be modified to include air and substrate media above and below the cladding and box, respectively?

A plugin that supports multilayer waveguides with the ability to overlay the mode plofile with the layer stack including lines indicating the interfaces and sidewalls would be great too.

**Comment by momchil-flex** [comment]
Since Lucas already has a lot on his plate, maybe extending our waveguide plugin is a good starter project for one of the new people joining us soon? I mean, I know that there are some projects already planned for them, but this should be not too hard to do and should also help familiarize with our API.

**Comment by tylerflex** [comment]
I have some other projects in mind for the people joining in the near future (Yannick, Matt) that I think will target more directly what they'll be working on. But feel free to reassign to someone else.

**Comment by lucas-flexcompute** [comment]
If this is not high priority, I can implement it relatively quickly probably by next week.

**Comment by smgitrep** [comment]
Just wondering:
1) when the geometry edges over field plots will be released
2) if the multilayer waveguide option will be implemented

**Comment by lucas-flexcompute** [comment]
Hi @smgitrep, both features should be out in our next release.
