### ISSUE TITLE
Replace black with ruff format

### ISSUE THREAD

**Issue by yaugenst-flex** [flexcompute/tidy3d#1662]
Since [ruff format](https://docs.astral.sh/ruff/formatter/#:~:text=The%20Ruff%20formatter%20is%20an,1.2.) has had feature parity with black for a while now, it might be nice to move away from black because 1. speed and 2. one less dependency.

**Comment by so-rose** [comment]
A **humble perspective from the wilds**: It's very, very good. `ruff fmt` also allows single-quote/tabs; subjectively, that's already reason enough, before the speed comes into play.

Just mind the conflicting rules leading to non-deterministic output. The docs recommend all kinds of stuff, generally I've found these are sufficient:
```
ignore = [
	"COM812",  # Conflicts w/Formatter
	"ISC001",  # Conflicts w/Formatter
	"Q000",  # Conflicts w/Formatter
	"Q001",  # Conflicts w/Formatter
	"Q002",  # Conflicts w/Formatter
	"Q003",  # Conflicts w/Formatter
	"D206", # Conflicts w/Formatter
...
]
```
Here's [my current pyproject.toml ignorelist](https://git.sofus.io/so-rose/blender_maxwell/src/commit/929fb2dae92e92544b157c2a7262aeecb45d857e/pyproject.toml#L110) for reference.

Hope it can help!

**Comment by tylerflex** [comment]
Thanks @so-rose !

**Comment by tylerflex** [comment]
think we can close this?
