### ISSUE TITLE
Strange PML plotting in 2D

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#1708]
<img width="307" alt="image" src="https://github.com/flexcompute/tidy3d/assets/92756888/4ac0dca2-fa1d-4a95-ab77-9fcc7fbec4e4">

for more details refer to https://flow360.atlassian.net/browse/SCEM-6289

**Comment by momchil-flex** [comment]
Off the top of my head this is probably something to do with 2D simulations still being assigned a non-zero `dl` along the 0-dim, while PMLs are just plotted with effectively 0 width.

**Comment by Frank-DingYC** [comment]
Yes, the problem is exactly what you describe. However, the structures are with 0-dim too while they still have some width. Could we just make the PML and structures look the same?
