### ISSUE TITLE
Deprecation warning in old tidy3d

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#171]
Put deprecation warnings while importing package, suggesting users can pip install new version if they want and warning them that this version won't be updated.

**Comment by An-Li-magicloud** [comment]
When user is importing lagcy tidy3d, we could check latest version by leveraging github release api,

curl \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/repos/flexcompute/tidy3d/releases
