### ISSUE TITLE
#1684 broke autograd tests

### ISSUE THREAD

**Issue by yaugenst-flex** [flexcompute/tidy3d#1734]
The new interp validator in #1684 broke autograd tests, as arrays of dtype object (during bw pass?) can not be interpolated. @marc-flex

**Comment by momchil-flex** [comment]
Oh, yikes, I guess the CI only passed before the autograd PR was merged. Can we just avoid the validator for that dtype?

**Comment by tylerflex** [comment]
>  Can we just avoid the validator for that dtype?

That would be fine
