### ISSUE TITLE
Bent Waveguide Modes Effective Index

### ISSUE THREAD

**Issue by smgitrep** [flexcompute/tidy3d#1750]
I noticed the ModeSolver always finds real effective indices for bent waveguide modes.  I expected the effective indices to be complex to account for radiation loss.  Can the ModeSolver compute complex effective indices?

**Comment by momchil-flex** [comment]
By default the mode solver uses PEC boundaries, so there is no loss in the simulation. To capture radiative loss, you need to add PML instead by setting e.g. `num_pml = (12, 12)` in the `ModeSpec`. There are a few things to note:

- Unlike FDTD simulations, the pml in the mode solver come *into* the simulation domain, so make sure you have enough distance between the structure and the mode plane boundaries.
- You will probably get some unphysical modes localized in the PML regions. Make sure you examine the mode fields to know you're looking at the right mode, and increase `num_modes` if needed to find it (or use `target_neff`).
- In 2.7.0rc2 we made some improvements on the mode solver PML which may produce better results. We will be releasing the official 2.7.0 soon, but in the meantime it may be best to do e.g. `pip install tidy3d==2.7.0rc2`. 
- In some cases, there can be noticeable dependence on things like simulation domain size, resolution, etc. The imaginary part should still be an OK estimate of the physical loss but convergence may be tricky.
-

**Comment by smgitrep** [comment]
Thank you for the detailed response. Could you clarify if the boundary_spec parameter in td.Simulation is used by the ModeSolver?

**Comment by momchil-flex** [comment]
No, `Simulation.boundary_spec` does not affect the mode solver, it is only for FDTD simulations. In principle, the mode solver boundary (as defined by the mode plane) can be (and often is) much smaller than the enclosing simulation domain boundary. We need to truncate the mode solve differently than the FDTD simulation. For lossless fields that decay by the mode plane boundaries, using the default PEC works very well and avoids some of the PML complications. However, if you want to capture the losses, then you have to set the `num_pml` in the `mode_spec` of the mode solver.
