### ISSUE TITLE
Issue on page /api/_autosummary/tidy3d.Simulation.html

### ISSUE THREAD

**Issue by qt-thomas** [flexcompute/tidy3d#1766]
I am a bit confused by the Courant factor definition. I think the factor is inverted. It should read  $c \Delta t / \Delta x \leq 1 $, instead of $\Delta x /c \Delta t \leq 1 $.

I am hoping this is just a documentation issue, since you bound it to 1.0. Please let me know otherwise.

**Comment by weiliangjin2021** [comment]
Yeah, it's an documentation issue. I think it's coming from FDTD 101 slides [here](https://www.flexcompute.com/fdtd101/Lecture-7-Time-step-size-and-CFL-condition-in-FDTD/). The formula on the slides are correct (perhaps some early version has a typo here). @tylerflex do you know where the image in the doc is coming from?

**Comment by weiliangjin2021** [comment]
Oh sorry, it's not from the image, but typed. I'll correct that now.

**Comment by qt-thomas** [comment]
Thanks @weiliangjin2021 . Nice to hear from you! What a small world.

**Comment by weiliangjin2021** [comment]
> Thanks @weiliangjin2021 . Nice to hear from you! What a small world.

Haha, just found out it's you! Glad to meet you here

**Comment by qt-thomas** [comment]
Please close out the ticket once you've worked on it. That said, can you also clarify in the documentation what is the actual step size used in the FDTD in all dimentions? For example, if I give C=0.6 in a 3D simulation, will it actually normalize to $0.6/\sqrt 3$ or will it cap at $1/\sqrt 3$? Thanks again!

**Comment by weiliangjin2021** [comment]
The Courant number defined in the simulation object is always normalized so that CFL condition is met when it's no larger than 1. E.g. in 3D uniform grids, it's defined as "sqrt{3} c dt/dx".

**Comment by weiliangjin2021** [comment]
Here are the new doc and docstring. In most cases, you don't need to adjust normalized Courant number from the default value 0.99.
![image](https://github.com/flexcompute/tidy3d/assets/92755338/623f9267-eed5-489f-8800-4e8ec26485fe)
![image](https://github.com/flexcompute/tidy3d/assets/92755338/83b6e3b3-cf2f-473b-8601-c63fd49a1cef)
