### ISSUE TITLE
Add `estimate_cost()` and `delete()` methods for `DesignSpace`

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#1781]
Our `Batch` supports `estimate_cost()` and `delete()` to estimate the cost for the entire batch and delete the tasks in the batch. This prevents users from accidentally running large batches. Even when a batch of simulations is submitted by mistake, they can be deleted quickly to avoid getting charged. 

`DesignSpace` however doesn't seem to have similar methods so new users can make mistakes and waste credits. Can we add similar methods?

**Comment by m-bone** [comment]
Hi Tom,

I've implemented an `estimate_cost()` method for `DesignSpace` that has as few limitations as we can manage given the complexity of the user inputs. It calculates a maximum possible cost for the whole `DesignSpace.run`: if the user is running optimizers they may converge and stop early but this will lead to a lower real cost, never higher than the estimate.

For the `delete()` method I'm not sure what the desirable output should be. `DesignSpace` doesn't queue anything when initialised and once `DesignSpace.run` is called the Batch objects that are created are immediately run so `web.abort` would be needed to stop them. What do you suggest as the ideal behaviour?

Just so you know this will be coming out within the larger redesign of the Design API planned for 2.8.

**Comment by tomflexcompute** [comment]
Thanks @m-bone ! `estimate_cost()` for `DesignSpace` is super useful.

For delete/abort, ideally all currently running tasks associated with the DesignSpace and batch can be stopped/deleted.
