### ISSUE TITLE
Remove "No sources in simulation" INFO

### ISSUE THREAD

**Issue by e-g-melo** [flexcompute/tidy3d#1788]
# Description
When running Mode solver in GUI the log message "No sources in simulation" shows up. It is confusing for users as there is no need to include sources in Mode simulations.
![image](https://github.com/flexcompute/tidy3d/assets/125516370/34e7e157-97ba-4f0f-be95-64b95e07a0b8)
 

# Solution
Comment out this line in the code until we have a long term solution. Maybe separate FDTD and Mode in v3.0.

**Comment by momchil-flex** [comment]
Done in #1784
