### ISSUE TITLE
Switch web access between Dev and Prod

### ISSUE THREAD

**Issue by weiliangjin2021** [flexcompute/tidy3d#179]
- [ ] Instead of modifying `Default_CONFIG` in `config.py` manually, define some function e.g. called `def _set_config()` to enable the switch

**Comment by tylerflex** [comment]
Let's push this until next release as it's not clear to me how to handle it right now. We probably want to also move all of our webapi to the new web service.

**Comment by momchil-flex** [comment]
With PR #248, you can now do e.g. `export TIDY3D_ENV="dev"`, or set `os.environ["TIDY3D_ENV"] = "dev"` directly in the script. Is that good enough to close this?
