### ISSUE TITLE
Check credit balance and daily free sim balance from Python API

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#1815]
Users have reported the desire to check their credit balance and daily free simulation balance directly in the Python API, i.e. something like web.credit_balance() and web.free_sim_balance(). Right now they need to log in to the GUI and check the balance in the account center.

**Comment by momchil-flex** [comment]
@QimingFlex can you help with this? Not sure which endpoints to call.

**Comment by momchil-flex** [comment]
Sorry. I did not mean @QimingFlex. I meant to ask @magiWei .

**Comment by QingengWei** [comment]
> Sorry. I did not mean @QimingFlex. I meant to ask @magiWei .

Ok, I will create one ticket to follow up.

**Comment by daquinteroflex** [comment]
Just thought to say this is a great feature idea

**Comment by momchil-flex** [comment]
Fixed in #1843
