### ISSUE TITLE
Fitting creates active material

### ISSUE THREAD

**Issue by alec-flexcompute** [flexcompute/tidy3d#1878]
**Describe the bug**
When fitting 3 refractive index values, I get a material that has a negative k value, and diverges.

**To Reproduce**
To reproduce, see the attached example notebook: 
![image](https://github.com/user-attachments/assets/f30c3d97-2a7f-4174-80b9-821b2e526083)

**Comment by momchil-flex** [comment]
Thanks @alec-flexcompute . Could you post code snippets rather than images so it's easy to just copy paste.

**Comment by alec-flexcompute** [comment]
```python
import numpy as np
import tidy3d as td

wvls = np.array([275e-3, 260e-3, 255e-3])
n_nAlGaN = np.array([2.72, 2.68, 2.53])

from tidy3d.plugins.dispersion import FastDispersionFitter, AdvancedFastFitterParam

nAlGaN_fitter = FastDispersionFitter(wvl_um=wvls, n_data=n_nAlGaN)
nAlGaN_mat, _ = nAlGaN_fitter.fit()

freq_list = nAlGaN_mat.angular_freq_to_Hz(nAlGaN_mat._imag_ep_extrema_with_samples())
ep = nAlGaN_mat.eps_model(freq_list)
for e in ep:
    print(e.imag)
```
