### ISSUE TITLE
Documentation 404

### ISSUE THREAD

**Issue by bstrekha** [flexcompute/tidy3d#1908]
- Clicking "For more details, see the corresponding [tutorial]" in https://docs.flexcompute.com/projects/tidy3d/en/latest/notebooks/Primer.html leads to a 404 - Page not found view. It tries to direct to https://docs.flexcompute.com/projects/tidy3d/en/latest/notebooks/AdjointPlugin_1_Intro.html
- On https://www.flexcompute.com/fdtd101/Lecture-4-Prelude-to-Integrated-Photonics-Simulation-Mode-Injection/ "In this waveguide example, we are interested in exciting a selected mode. This can be achieved with our in-built Mode Source feature (Detals can be found [here])" leads to a 
broken page on https://docs.flexcompute.com/projects/tidy3d/en/latest/notebooks/Modal_sources_monitors.html

**Comment by daquinteroflex** [comment]
Hi @bstrekha, thanks for raising this! 

I will open a PR to fix these links, and we have some functionality we're writing in the pipeline to avoid them in the first place.

Much appreciated.

Related to https://flow360.atlassian.net/browse/MKTG-368
