### ISSUE TITLE
Field Projection Data throws error for example notebook

### ISSUE THREAD

**Issue by alec-flexcompute** [flexcompute/tidy3d#1910]
**Describe the bug**
When running [this notebook](https://www.flexcompute.com/tidy3d/examples/notebooks/VortexMetasurface/) (without any modifications), this error pops up:
![image](https://github.com/user-attachments/assets/47482398-5f3a-4b1f-95d7-ecb76e3ad4bc)

Maybe something with field projection got lost in an update? Presumably this notebook ran at some point, and according to a customer, they were able to run this before.

**Comment by momchil-flex** [comment]
Thanks @alec-flexcompute . I assume this was encountered using version 2.7.1? It seems that there was some mismatch in the solver version of the frontend submodule in the corresponding solver. It should be fixed now.

On a separate note I was looking at this notebook and had some thoughts that I put [here](https://github.com/flexcompute/tidy3d-notebooks/pull/160)

**Comment by momchil-flex** [comment]
By the way it would be helpful in the future if you can always provide (ask user for) a task id.

Will not close this for now until we can confirm it's resolved.

**Comment by alec-flexcompute** [comment]
User confirmed that updating Tidy3D removed the error

**Comment by alec-flexcompute** [comment]
Ok, so the person _just_ emailed me that the error is reappearing after it disappeared for a bit. Did another update go through?

**Comment by momchil-flex** [comment]
They upgraded to 2.7.2 and are still hitting the error?

**Comment by alec-flexcompute** [comment]
Apparently they updated, avoided the error, and now the error is happening again. I asked about multiple python environments and other details - I'm not sure what would cause this behavior though

**Comment by momchil-flex** [comment]
Yeah I would think 2.7.2 should be safe... Otherwise I'm very confused.
