### ISSUE TITLE
`plot` at the end of a `PolySlab` returns incorrect result

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#1921]
When a circular bend is created using `gdstk`, the 2D plotting at the beginning or end of the bend shows incorrect waveguide width. 

For example, if I create a waveguide of width 1um. The xy plot looks correct.

<img width="289" alt="image" src="https://github.com/user-attachments/assets/05f5e7f4-7a58-486a-8bef-205df73ceaba">

Plotting at x=0 however shows the waveguide width is only 0.5 um.
<img width="297" alt="image" src="https://github.com/user-attachments/assets/a4de67f3-f707-4314-ac84-291f5d14afd4">

Offsetting x just a tiny bit to x=0.001um shows the correct width.
<img width="486" alt="image" src="https://github.com/user-attachments/assets/f2371a31-582f-447c-8a56-118495dabbd4">

Simple notebook to reproduce the issue.
[circular band test.zip](https://github.com/user-attachments/files/16755569/circular.band.test.zip)

**Comment by tylerflex** [comment]
Is there a sidewall angle? could this be an artifact of that?

**Comment by tomflexcompute** [comment]
Sidewall angle is zero here. 

After thinking about it a bit more, I suspect the issue is for a circular bend created in gdstk, the tangent at the beginning of the bend is not exactly zero due to some small numerical error. That is, the surface of the waveguide is not perfectly perpendicular to the xz plane but at a tiny angle. Then when you plot x=0 cross section, the plane only intersects with half the waveguide.

<img width="131" alt="image" src="https://github.com/user-attachments/assets/1e511d77-297c-4f18-b645-38bb1e725eaf">

**Comment by lucas-flexcompute** [comment]
@tomflexcompute is correct. If I'm not mistaken, RobustPath will give better results than FlexPath in this case, because the gradients are analytical.

**Comment by tomflexcompute** [comment]
Ok thanks for confirming @lucas-flexcompute . In that case we can close this issue since it's not really a bug.
