### ISSUE TITLE
TFSF doesn't inject anything into simulation in certain 2D cases

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#1922]
In some 2D cases, TFSF source doesn't inject anything into the simulation so field_decay stays at 0 and monitor data are all 0. Setting the z grid to uniform resolves the issue. 

@momchil-flex is already aware of this issue but just open an issue here to keep track of it.

**Comment by momchil-flex** [comment]
Will be fixed in 2.7.3
