### ISSUE TITLE
`.to_source` methods does not accept the `num_freqs` argument.

### ISSUE THREAD

**Issue by FilipeFcp** [flexcompute/tidy3d#1926]
A user pointed out that the `.to_source`  method for the ComponentModeler class does not accept the `num_freqs` argument. 
The same goes for the `ModeSolver.to_source`.

It is possible to use the `updated_copy` and to set the `num_freqs`, but maybe it would be good to add this option to the `to_source` methods.

Priority: small

**Comment by tylerflex** [comment]
Would be a good first issue. @FilipeFcp not sure if you want to try it to get more used to the development process?
