### ISSUE TITLE
PMC or peiodic boundary conditions in mode solver

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#1927]
Currently the mode solver only supports PEC or PEC with PML inside. It is fine for most cases but in the particular case of doing mode analysis for infinite slab waveguides, it is problematic. 

![image](https://github.com/user-attachments/assets/aeabee83-7fe0-4d7f-8dbf-d4f61dd41bd1)

The PEC boundary forces the TE modeS with Ey polarization. There is no good way to solve for TM modes.

**Comment by momchil-flex** [comment]
If the waveguide is infinite, then just use 0D simulation along the inifnite dimension? Our 1D mode solver (i.e. when one of the simultion dims is 0) is effectively periodic boundary conditions for that dimension. Maybe I'm misunderstanding something, I just want to understand if there are any real use cases.

**Comment by tomflexcompute** [comment]
Didn't know that when the size is 0, the boundary becomes periodic. If that's the case, it's indeed not an issue anymore. I'll test it.

**Comment by momchil-flex** [comment]
This is also true for FDTD, any time we do a 2D sim (e.g. https://docs.flexcompute.com/projects/tidy3d/en/latest/notebooks/RingResonator.html) we set the third boundary condition to Periodic, right? The mode solver just does it automatically.

**Comment by tomflexcompute** [comment]
Yeah I just didn't know we automatically set the boundary to periodic in mode solver when the size is 0. I thought it always applies PEC boundary regardless. That's good to know. We can close this issue.

**Comment by momchil-flex** [comment]
Actually there's a [related one](https://github.com/flexcompute/tidy3d/issues/955) that we kept open because we thought it may still be good to improve on this at some point. Just seems like it's really not high priority...

**Comment by tomflexcompute** [comment]
> Actually there's a [related one](https://github.com/flexcompute/tidy3d/issues/955) that we kept open because we thought it may still be good to improve on this at some point. Just seems like it's really not high priority...

Interesting. The user said we have the PMC option as well. Is that true?

**Comment by momchil-flex** [comment]
I *think* he was confused by the FDTD boundaries, but maybe at some point we actually supported PMC too? The issue is quite old. I think it actually shouldn't be too hard to enable: we support symmetry = 1 which is effectively PMC boundary on one side, the handling is exactly the same. It just requires some reorganization of the mode solver internals, like passing a proper BoundarySpec.

**Comment by tomflexcompute** [comment]
Yeah sounds good.
