### ISSUE TITLE
Claryfing units for TFSF source.

### ISSUE THREAD

**Issue by FilipeFcp** [flexcompute/tidy3d#1949]
The documentation of the TFSF says that the source injects $1W/um^2$ of power, but the units are in Intensity, not power, right? So seems that the intensity is constant, but the Power varies with the source size, am I correct?

I had to get the $|E|^2$ and got a bit confused if I should multiply by the source area or not. Maybe would be interesting to clarify that according to the Poyting theorem. $I = (1/2)c n \epsilon_0 |E_0|^2 = 1$.

**Comment by momchil-flex** [comment]
> The documentation of the TFSF says that the source injects 1 W / u m 2 of power, but the units are in Intensity, not power, right? So seems that the intensity is constant, but the Power varies with the source size, am I correct?

Correct. I guess the proper wording would be something like the source injects 1W of power per square micron of  the source injection area, so the power injected by the source in W is given by the area of the injection plane in units of um**2. Or something like that. You want to have a go at rephrasing it?

**Comment by FilipeFcp** [comment]
I think you are right. I just tested it and this is what I got for a plane wave:
