### ISSUE TITLE
Add interpolation option for `SimulationData.plot_field` method.

### ISSUE THREAD

**Issue by FilipeFcp** [flexcompute/tidy3d#1952]
I would suggest implementing a variable for interpolation in the `SimulationData.plot_field` method, so the user has an easy way to plot a smooth field profile.

Without interpolation:

![image](https://github.com/user-attachments/assets/27f5a070-bf4b-43c6-9c17-aa022af6481f)

With interpolation:

![image](https://github.com/user-attachments/assets/922629f1-ec77-42e6-9937-33b249312aea)

In the graph above, the `.interp` method for the Xarray field data object was used to increase the density of points from the original grid points to 1000.

small priority

**Comment by tylerflex** [comment]
Hi @FilipeFcp could you implement this when you get time? should be pretty straightforward, like the last one. thanks!
