### ISSUE TITLE
Make `BatchData` more `dict`-like

### ISSUE THREAD

**Issue by yaugenst-flex** [flexcompute/tidy3d#1955]
[`BatchData`](https://docs.flexcompute.com/projects/tidy3d/en/v2.0.2/_autosummary/tidy3d.web.BatchData.html#tidy3d.web.BatchData) currently defines an `.items()` method with which one can iterate (`for k, v in batch_data.items()`). This suggests to the users that `BatchData` behaves like a dictionary (actually, the `.dict_from_xxx` classmethods suggest that too), but the `.keys()` method returns unexpected results (`dict_keys(['attrs', 'type', 'simulations', 'folder_name', ...])` instead of the simulation id's) and there is no `.values()` method.

**Comment by tylerflex** [comment]
maybe to do this more systematically, we could experiment with making `BatchData` a `collections.abc.MutableMapping` and implementing the various methods there.

https://realpython.com/python-mappings/

**Comment by yaugenst-flex** [comment]
Hmm does it need to be a `MutableMapping`? How do we deal with immutable `Tidy3dBaseModel` in that case?

**Comment by tylerflex** [comment]
yea not sure, we could make it immutable too. I guess the point is that we might want to be more systematic about making it dict-like in case something else pops up. but yea overall agree re: values and other keys at the least

**Comment by tylerflex** [comment]
https://stackoverflow.com/a/3387975

**Comment by tylerflex** [comment]
(first time I'm hearing about these things but seem convenient for this)
