### ISSUE TITLE
Issue w/ autograd in optimization simulations with multi-frequency monitor

### ISSUE THREAD

**Issue by jhu9566** [flexcompute/tidy3d#1963]
**Description**
WARNING: Autograd compatible 'web.run()' failed, running original  
             'web.run()'. If you received this warning, please file an issue at 
             the tidy3d front end with this message pasted in and we will       
             investigate.                                                       
                                                                                
              ['https://github.com/flexcompute/tidy3d/issues/new?assignees=tylerf](https://github.com/flexcompute/tidy3d/issues/new?assignees=tylerflex&labels=adjoint&projects=&template=autograd_bug.md)
             [lex&labels=adjoint&projects=&template=autograd_bug.md'](https://github.com/flexcompute/tidy3d/issues/new?assignees=tylerflex&labels=adjoint&projects=&template=autograd_bug.md).            
                                                                                
             ValueError('Only the same, single frequency is supported in all    
             monitors when using autograd differentiation. Found 51 distinct    
             frequencies in the monitors.')   File                              
             "/opt/conda/lib/python3.10/site-packages/tidy3d/web/api/autograd/au
             tograd.py", line 174, in run                                       
                 return _run(                                                   
               File                                                             
             "/opt/conda/lib/python3.10/site-packages/tidy3d/web/api/autograd/au
             tograd.py", line 303, in _run                                      
                 traced_fields_data = _run_primitive(                           
               File                                                             
             "/opt/conda/lib/python3.10/site-packages/autograd/tracer.py", line 
             44, in f_wrapped                                                   
                 ans = f_wrapped(*argvals, **kwargs)                            
               File                                                             
             "/opt/conda/lib/python3.10/site-packages/autograd/tracer.py", line 
             48, in f_wrapped                                                   
                 return f_raw(*args, **kwargs)                                  
               File                                                             
             "/opt/conda/lib/python3.10/site-packages/tidy3d/web/api/autograd/au
             tograd.py", line 382, in _run_primitive                            
                 sim_combined = setup_fwd(sim_fields=sim_fields,                
             sim_original=sim_original)                                         
               File                                                             
             "/opt/conda/lib/python3.10/site-packages/tidy3d/web/api/autograd/au
             tograd.py", line 422, in setup_fwd                                 
                 return sim_original.with_adjoint_monitors(sim_fields)          
               File                                                             
             "/opt/conda/lib/python3.10/site-packages/tidy3d/components/simulati
             on.py", line 3225, in with_adjoint_monitors                        
                 mnts_fld, mnts_eps =                                           
             self.make_adjoint_monitors(structure_indices=structure_indices)    
               File                                                             
             "/opt/conda/lib/python3.10/site-packages/tidy3d/components/simulati
             on.py", line 3232, in make_adjoint_monitors                        
                 freqs = self.freqs_adjoint                                     
               File                                                             
             "/opt/conda/lib/python3.10/site-packages/tidy3d/components/simulati
             on.py", line 3259, in freqs_adjoint                                
                 raise ValueError(                                              
             .
**Simulation Setup**

Running the autograd bandpass filter tutorial: https://www.flexcompute.com/tidy3d/examples/notebooks/Autograd17BandPassFilter/

Also please include what options were passed to the `web` function.

**Other information**
Anything else you'd like to add to help us look into it?

**Comment by yaugenst-flex** [comment]
Hi @jhu9566, thanks for raising an issue! Could you provide some details on your setup, in particular which version of tidy3d you're using? And are you running the unmodified notebook? Generally these are all tested before release, so they _should_ run (at least on the latest tidy3d version).

**Comment by tylerflex** [comment]
@jhu9566 

I am guessing you're using version `2.7.1` because I get this same error when running from that version. Could you try `print(td.__version__)` to see? 

This notebook uses the broadband adjoint feature introduced in 2.7.2, to get the recommended version `pip install --upgrade tidy3d` and it should work as I just verified locally

Please feel free to re-open the issue if you still encounter an issue or anything else comes up!

**Comment by jhu9566** [comment]
Hello,

Thank you! Yes it seems to have just been a version problem. Updating the
version of tidy3d resolved this issue.

Best,
Jack
