### ISSUE TITLE
Documentation page about auto shutoff

### ISSUE THREAD

**Issue by momchil-flex** [flexcompute/tidy3d#199]
We should explain the implications of fields not decaying sufficiently (FreqMonitors may be wrong) and link the warning that is produced when you load the simulation data to that page for more info.

**Comment by tylerflex** [comment]
Note: have a [property](https://github.com/flexcompute/tidy3d/blob/main/tidy3d/components/data.py#L825) to grab the final decay value for a `SimulationData`.
Also have a [warning](https://github.com/flexcompute/tidy3d/blob/main/tidy3d/web/webapi.py#L306) if the decay value did not get below `shutoff` when `web.load`ing:

So to close this issue, we just need to edit that warning string?

note also we can remove [this comment](https://github.com/flexcompute/tidy3d/blob/main/tidy3d/components/data.py#L20) as part of this

**Comment by momchil-flex** [comment]
I think what I had in mind about this is to add some explanation in the docs, and link to that explanation in the warning.

Specifically, explain that frequency-domain monitors may be inaccurate if the shutoff value is not reached, since we are doing a time domain simulation, and the equivalent frequency response is only obtained in the limit in which there are no fields before or after the recording time. On the other hand, time monitors are accurate, in case users are looking for a limited time response. We could also explain here that in some cases with long-lived resonances, it is unfeasible to wait for the full field decay. In that case users may want to consider a tool like harminv to analyze the resonances.

**Comment by tylerflex** [comment]
This would probably be good in FAQ perhaps, then just add the link to it in the warning message I linked above.

**Comment by momchil-flex** [comment]
Added discussion in the FAQ.
