### ISSUE TITLE
simulation subsection to include lumped elements

### ISSUE THREAD

**Issue by weiliangjin2021** [flexcompute/tidy3d#1991]
The following code will error at the last line.
```
# From https://docs.flexcompute.com/projects/tidy3d/en/latest/notebooks/ModeSolver.html
# Only modification: add a 2D material
import numpy as np
import matplotlib.pylab as plt

import tidy3d as td
from tidy3d.constants import C_0
import tidy3d.web as web
from tidy3d.plugins.mode import ModeSolver

# size of simulation domain
Lx, Ly, Lz = 8, 6, 6
dl = 0.05

# waveguide information
wg_width = 1.5
wg_height = 1.0
wg_permittivity = 4.0

# automatic grid specification
grid_spec = td.GridSpec.auto(min_steps_per_wvl=20, wavelength=1.0)

resistor = td.LumpedResistor(
	center=(2,1,0),
	size=(0, 1, 1),
	name="port",
	num_grid_cells=3,
	resistance=50.0,
	voltage_axis=2,
)

sim = td.Simulation(
    size=(Lx, Ly, Lz),
    grid_spec=grid_spec,
    lumped_elements=[resistor],
    run_time=1e-20,
    boundary_spec=td.BoundarySpec.all_sides(boundary=td.Periodic()),
)

plane = td.Box(center=(0, 0, 0), size=(4, 0, 3.5))


mode_spec = td.ModeSpec(
    num_modes=1,
    target_neff=2.0,
)


mode_solver = ModeSolver(
    simulation=sim,
    plane=plane,
    mode_spec=mode_spec,
    freqs=[1e14],
)

mode_solver.reduced_simulation_copy.simulation.volumetric_structures
```

This is because mode solver is using a reduced simulation (https://github.com/flexcompute/tidy3d/blob/ce648575a8c218e4a6a259ec406bd09446b40493/tidy3d/plugins/mode/mode_solver.py#L350), which comes from https://github.com/flexcompute/tidy3d/blob/ce648575a8c218e4a6a259ec406bd09446b40493/tidy3d/components/simulation.py#L1349-L1361. Lumped element outside the reduced simulation domain should be excluded.

**Comment by momchil-flex** [comment]
Note that in his recent PR (merged in develop) Casey introduced a try-except for the reduced simulation copy in the mode solver to avoid unexpected issues like this (something like that popped up for nonlinear materials too). This would fix this in principle but always better to fix properly? https://github.com/flexcompute/tidy3d/pull/1977/files#diff-4d80d757aca9b68f3a9557ad726b40390e2b2185302fcfbf162b1cf3e874e79cR345-R357

**Comment by weiliangjin2021** [comment]
> Note that in his recent PR (merged in develop) Casey introduced a try-except for the reduced simulation copy in the mode solver to avoid unexpected issues like this (something like that popped up for nonlinear materials too). This would fix this in principle but always better to fix properly? https://github.com/flexcompute/tidy3d/pull/1977/files#diff-4d80d757aca9b68f3a9557ad726b40390e2b2185302fcfbf162b1cf3e874e79cR345-R357

Well, try-except won't catch this because reduced simulation is generated fine, but only error if simulation.volumetric_structures is called.

**Comment by weiliangjin2021** [comment]
An easy fix (but not ideal) using try-except idea is to add a line to invoke the error,

> try:
>      solver = self.reduced_simulation_copy
>      solver.simulation.volumetric_structures

**Comment by momchil-flex** [comment]
Oh I see. That makes sense if there's no obvious better fix.

**Comment by weiliangjin2021** [comment]
@dmarek-flex if we can just exclude lumped element outside the reduced domain, a better fix would be:

- each lumped element has a `bounds` property
- Similar to https://github.com/flexcompute/tidy3d/blob/ce648575a8c218e4a6a259ec406bd09446b40493/tidy3d/components/simulation.py#L1465, exclude lumped elements that are outside.

**Comment by dmarek-flex** [comment]
> @dmarek-flex if we can just exclude lumped element outside the reduced domain, a better fix would be:
> 
> * each lumped element has a `bounds` property
> * Similar to https://github.com/flexcompute/tidy3d/blob/ce648575a8c218e4a6a259ec406bd09446b40493/tidy3d/components/simulation.py#L1465
>   , exclude lumped elements that are outside.

Yes, each lumped element has an associated geometry that we can check. Shouldn't be hard
