### ISSUE TITLE
`ModeSolver.reduced_simulation_copy` error when `run_time` is a `RunTimeSpec`

### ISSUE THREAD

**Issue by momchil-flex** [flexcompute/tidy3d#2078]
So this is once again a testament to how poor the mode solver design to take a `Simulation` is, because the mode solver should have nothing to do with sources and simulation run time. However we have what we have, and @lucas-flexcompute stumbled upon the error described in the title. The underlying issue is that [reduced_simulation_copy removes the simulation sources](https://github.com/flexcompute/tidy3d/blob/efdc698eddc61bc7d43a1020699be9ed2328a8cc/tidy3d/plugins/mode/mode_solver.py#L1569) while [these lines](https://github.com/flexcompute/tidy3d/blob/efdc698eddc61bc7d43a1020699be9ed2328a8cc/tidy3d/components/simulation.py#L3735-L3738) in `Simulation._run_time`, when defined through a RunTimeSpec assume that there is at least one source present, otherwise you get an error that there's no default defined for the minimum operation over an empty list.

I think we could fix both but I wanted to discuss
@dbochkov - was there a reason to exclude sources in the reduced simulation copy (e.g. some validators may be triggered that we don't want) or was it just to keep things minimal?
@tylerflex - should we put a default index of 1 if that list is empty?

**Comment by tylerflex** [comment]
I think default index of 1 makes sense. and this sounds like it might be a general bug?

Also what's the status of https://github.com/flexcompute/tidy3d/pull/1838 @caseyflex ?

**Comment by caseyflex** [comment]
> I think default index of 1 makes sense. and this sounds like it might be a general bug?
> 
> Also what's the status of #1838 @caseyflex ?

on hold probably until next Feb

**Comment by dbochkov-flexcompute** [comment]
> @dbochkov - was there a reason to exclude sources in the reduced simulation copy (e.g. some validators may be triggered that we don't want) or was it just to keep things minimal?

yeah, to keep everything minimal + avoid additional data transfer in case of custom sources

**Comment by tylerflex** [comment]
did this ever get resolved? feel free to reassign @momchil-flex or if you have a PR that fixes/fixed it, you can link or close this.

**Comment by momchil-flex** [comment]
Yeah fixed in #2081
