### ISSUE TITLE
Override structures support cylinder, sphere, polyslab causing confusion

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#2105]
Our mesh override structure supports geometries besides Box such as Cylinder, Sphere, and PolySlab. This causes some confusion for users. For example, when using a Cylinder in the mesh override, the user thinks only the region within the cylinder will have a fine grid. However effectively we are only using the bounding box for the mesh override. Should we only allow Box as override?

**Comment by momchil-flex** [comment]
So the thinking of allowing any structure is to make it very simple to refine in the use case in which I want to refine around a specific structure, say I have a gold sphere and I want to put a custom mesh there, I can just create an override structure with the same geometry and a specific `dl`.

If this causes confusion, we could restrict to `Box`. One thing is that generally we are refraining from making breaking changes until v3. What do you think?

**Comment by tylerflex** [comment]
suppose one thing we could do is warn if a `not Box` is supplied, and then just put the bounding `Box` for that geometry

**Comment by tomflexcompute** [comment]
Yes giving a warning might be a better approach for now to not break any compatibility.

**Comment by tylerflex** [comment]
I can take care of it
