### ISSUE TITLE
S3 upload issue

### ISSUE THREAD

**Issue by An-Li-magicloud** [flexcompute/tidy3d#223]
Below code needs to check the response of put_object method to determin whether uploading was successful or failed.

https://github.com/flexcompute/tidy3d/blob/ef8f5e1ccd87d926095cb6084ee074749d1ed36a/tidy3d/web/webapi.py#L459-L464

**Comment by momchil-flex** [comment]
Should we retry if it was failed?

**Comment by An-Li-magicloud** [comment]
Adding an automatic retry logic is a feasible change for Feb release. It could increase success rate a lot. 

For long term, we need a failure logic design.

**Comment by tylerflex** [comment]
@momchil-flex @An-Li-magicloud  is this still an issue?
