### ISSUE TITLE
add opacity to from_gds

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#226]
Something that would be nice is to add opacity to `td.PolySlab.from_gds` method

See for example this grating coupler simulation, 

how can we get the slab with a different color?

![image](https://user-images.githubusercontent.com/4514346/155759477-434f9cde-e686-4972-b1e1-ab09ab179056.png)

**Comment by tylerflex** [comment]
What exactly are you trying to do?  Change the opacity of one of the structures in the `Simulation.plot()` call?
If so, there is currently no direct way to do that, but you can try:
* Editing the `matplotlib.Axes` returned from the plot function to select the patch and apply the color you want.
* Manually plot each structure in the simulation by looping through `sim.structures` and calling `.plot()`, which accepts kwargs (like "alpha") that get passed to matplotlib's patch plotting.

Take a look at this [notebook](https://docs.simulation.cloud/projects/tidy3d/en/latest/notebooks/VizSimulation.html) for more details.  And feel free to clarify so we can help.

**Comment by tylerflex** [comment]
I will work on this #227 when I get bandwidth, which is unfortunately in short supply these days :D

**Comment by joamatab** [comment]
no worries, this is just an improvement suggestion and not super critical on my side :)
