### ISSUE TITLE
Make sim.size elements of 0.0 mean one grid cell

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#233]

**Comment by momchil-flex** [comment]
That actually works, although you still need to define a dl in the 0-size direction. I would think that any reasonable dl should produce the same results, but for the time being I think this is OK as is? (it's also been noted here: https://docs.simulation.cloud/projects/tidy3d/en/latest/notebooks/RingResonator.html)

**Comment by tylerflex** [comment]
Looks good to me
