### ISSUE TITLE
update docs

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#237]
How can we update the [docs](https://docs.simulation.cloud/projects/tidy3d/en/latest/notebooks/ModeSolver.html)

to the latest version 1.1.0?

for example

```
from tidy3d.plugins import ModeSolver

mode_solver = ModeSolver(
    simulation=sim,
    plane=plane,
    freq=freq_hz
)
```

does not work anymore for 1.1.0

**Comment by tylerflex** [comment]
That's strange, it works for me
<img width="363" alt="image" src="https://user-images.githubusercontent.com/92756888/156440182-607f91c1-aa99-4369-8b18-e6584c52a0e0.png">

**Comment by tylerflex** [comment]
The only thing that doesn't work right now is
```python
tidy3d.plugins.ModeSolver
```
<img width="544" alt="image" src="https://user-images.githubusercontent.com/92756888/156440585-4f95ef96-8794-4e07-ada5-3b4901517ec7.png">
Can you confirm?

**Comment by tylerflex** [comment]
Note this is pip installed tidy3d-beta on a clean environment and from a working directory outside of `tidy3d`

**Comment by tylerflex** [comment]
Also note, I just pushed a change to `develop` branch to include the `from . import plugins` import again.
So it should go back to the way it was before after the next patch release.
If it seems to break anything (I can't reproduce) in the docs I will release the patch asap.
https://github.com/flexcompute/tidy3d/blob/develop/tidy3d/__init__.py#L50

**Comment by tylerflex** [comment]
If you have an issue with the mode solver itself, could you paste the output and the contents of Simulation, Plane, and freq_hz?

**Comment by joamatab** [comment]
Hi Tyler

i think the latest tidy3d version `1.1.0`  has some import issues

![image](https://user-images.githubusercontent.com/4514346/156470912-515e47a9-96fc-4d56-b5a7-48e3ebd3bed6.png)

**Comment by tylerflex** [comment]
Can you try uncommenting the line in tidy3d/__init__.py that says
```
from . import plugins
```
and see if it fixes your import error?  it's strange that I can't reproduce

**Comment by tylerflex** [comment]
Also, can you provide some more details about this?  Is it pip installed from PyPI? or local version?  What is the python version?
Can you paste the output of `ls ~/mambaforge/lib/python3.9/site-packages/tidy3d/plugins`?
<img width="348" alt="image" src="https://user-images.githubusercontent.com/92756888/156474446-ed9e415e-299f-4bdc-a25e-c22ca1581045.png">

**Comment by joamatab** [comment]
python3.9

i installed it with pip
`pip install tidy3d-beta --upgrade`

![image](https://user-images.githubusercontent.com/4514346/156475772-a6997011-e56c-4244-aede-f816ba4ba158.png)


Here is the `ls ~/mambaforge/lib/python3.9/site-packages/tidy3d/plugins`  output
```
dispersion  __init__.py  mode  near2far  __pycache__
```

**Comment by joamatab** [comment]
uncommenting the line

`from . import plugins` does not solve the error

**Comment by tylerflex** [comment]
Very strange, it looks like the new `smatrix` directory never got uploaded to PyPI.  I'll look into it, thanks!  Expect a 1.1.1 soon.

**Comment by joamatab** [comment]
awesome,

you can download the files i see from https://pypi.org/project/tidy3d-beta/

**Comment by tylerflex** [comment]
I found the error.  Was missing an __init__.py file.  Running the tests and will be uploaded in a few minutes for you to `pip install --upgrade` thanks for catching the bug.  I still dont understand why I couldn't reproduce on my end.

**Comment by tylerflex** [comment]
OK, pushed a fix in version `1.1.1`.  Please upgrade and confirm by closing the issue or commenting if it's still a problem (hopefully not!)

**Comment by joamatab** [comment]
awesome

thank you Tyler!

**Comment by tylerflex** [comment]
Thank you! For catching the problem ;)
