### ISSUE TITLE
Manually set integer type if there's a danger it could overflow with 32 bit

### ISSUE THREAD

**Issue by momchil-flex** [flexcompute/tidy3d#247]
`simulation.num_cells` should be set to `numpy.int64` type to avoid overflow issues on machines running 32 bit numpy. Are there any other variables where we should be careful and set the type?

**Comment by tylerflex** [comment]
none that I can think of.  Frequency might be getting large in some cases, but not sure how large is an issue.

**Comment by momchil-flex** [comment]
Floats should be fine, there it's a matter of precision.
