### ISSUE TITLE
Delay the `~/.tidy3d` folder creation to inside the `get_credentials` function.

### ISSUE THREAD

**Issue by zeyueN** [flexcompute/tidy3d#275]
The `mkdir` line for the `~/.tidy3d` below gets executed at import which is before the `get_credential` function checks for credentials in environment variables, in which case the folder is not needed.
https://github.com/flexcompute/tidy3d/blob/7e1be86a19b185e3b1d3c6c4e6a9c5d53982190e/tidy3d/web/auth.py#L17

More importantly, under certain containerization scenarios the access to the home folder is not guaranteed, in this case that line will always throw an error.

## Suggestion:
To move the whole folder creation block above to inside the [if block](https://github.com/flexcompute/tidy3d/blob/7e1be86a19b185e3b1d3c6c4e6a9c5d53982190e/tidy3d/web/auth.py#L99) in the while loop just before the folder is really needed.

As a side note, it would also be great if:
- users can control when to get authenticated, instead of forcing it at import
- there's a `max_attempt` or `timeout` for the while True loop to prevent getting trapped inside the loop

**Comment by momchil-flex** [comment]
We have fixed this and addressed your other suggestions in v1.2.1. The authentication now happens only in functions where it is needed (e.g. `web.run`, `web.load`...). There is a little bit of overhead in that it is called every time such a function is called, but it should be negligible. This is also temporary, we are working on a more major overhaul of the webapi where we're going to address this better.

**Comment by zeyueN** [comment]
Thanks so much for such a quick turnaround @momchil-flex !
