### ISSUE TITLE
Avoid modifying the default boto3 session at top level.

### ISSUE THREAD

**Issue by zeyueN** [flexcompute/tidy3d#284]
https://github.com/flexcompute/tidy3d/blob/07784cc3966d71c3461a9ae370b5595aca67bed5/tidy3d/web/auth.py#L22
https://github.com/flexcompute/tidy3d/blob/07784cc3966d71c3461a9ae370b5595aca67bed5/tidy3d/web/webapi.py#L16

In version 1.2.1, the combination of the above lines modifies boto3's default session's region at import for webapi, which is an undesired silent side effect that took us some time to spot and debug. The issue is now patched on our side and not very urgent, but it would be great if such modifications can be avoided, at least at the top level. Ideally, isolated `boto3.Session()` could be used to do all things aws related that's tidy3d specific so that users' environments are not affected.

**Comment by lei-flex** [comment]
s3 don't have the concept of default region. we can just remove it.
