### ISSUE TITLE
Optional `dash` dependencies for headless installs

### ISSUE THREAD

**Issue by zeyueN** [flexcompute/tidy3d#322]
In version 1.2.2 [`dash` and `jupyter_dash` were added ](https://github.com/flexcompute/tidy3d/blob/48a70df356720cf66e164e6b44c666061e111932/requirements.txt#L15) as dependencies which themselves require quite a few further dependencies for the new frontend app.

We see value in having such interactivity, but as mandatory dependencies they make our images a bit bloated for our headless installations of the package. It would be great if they can be specified as extra installs to give users some freedom in terms of the installation footprint 🙏

**Comment by tylerflex** [comment]
@zeyueN I implemented something in this PR: it works for me but we will continue to test a bit before merging it in.  Should be live in our next release, likely early next week.

https://github.com/flexcompute/tidy3d/pull/326

**Comment by zeyueN** [comment]
Hi @tylerflex, really happy to see such a prompt response. Thanks a lot! 🥇

**Comment by tylerflex** [comment]
alsolutely
