### ISSUE TITLE
web.monitor exits with an abstruse error if solver errors

### ISSUE THREAD

**Issue by momchil-flex** [flexcompute/tidy3d#336]
If a simulation errors e.g. on preprocessing, `web.monitor` exits with an abstruse and unrelated error. I am thinking of generally reorganizing internal logging such that hopefully the error message at any stage is caught and written in tidy3d.log. We need to also reorganize some of the frontend to deliver that to the user. For starters, web.monitor should be rewritten to check at every stage if the status is error, and if so, to try and download `tidy3d.log` and display it to the user. I think this can be a part of `get_status()`?

More generally we should also think where else this should be done - probably in `web.load`, `web.get_info`... So we may move `get_status()` outside of `web.monitor`?

**Comment by tylerflex** [comment]
I think all of this makes sense.  (making part of get status, moving get_status outside of `web.monitor()`).

**Comment by tylerflex** [comment]
consolidating in #544
