### ISSUE TITLE
Boundary Conditions API

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#345]
### Nothing, just periodic
```python
# dont specify anything (default `BoundarySpec()`)
```

### PML on one or more sides
```python
boundaries = BoundarySpec(x=None, y=td.PML(num_layers=20), z=td.PML()) # pml customizable
boundaries = BoundarySpec.pml(y=True, z=True) #shortcut, default PML only
```

### PML different on + and -
```python
boundaries = BoundarySpec(
    z=td.PML(
        plus=td.PMLSide(num_layers=10),
        minus=td.PMLSide(num_layers=20)
    )
) # note, redefining td.PML() here
```

### Symmetry on one or more sides
```python
boundaries = BoundarySpec(
    x=None,
    y=td.PML(),
    z=td.Symmetry(eigenvalue=1, absorber=td.PML()
)

```
### Bloch boundaries
```python
boundaries = BoundarySpec.bloch(kx=0.5, ky=0.2, z=td.PML()) # actually not sure about this one
```

## Architecture?

```python

BoundarySide(Tidy3dBaseModel):
    """ Defines boundary on one side (PBC, PML, PEC, etc.)."""

class Periodic(BoundarySide):
    """periodic BC"""

BoundarySpec1D(Tidy3dBaseModel):
     plus : BoundarySide = Periodic()
     minus : BoundarySide = Periodic()

BoundarySpec(Tidy3dBaseModel):

   x: BoundarySpec1D = BoundarySpec1D()
   y: BoundarySpec1D = BoundarySpec1D()
   z: BoundarySpec1D = BoundarySpec1D()
```

**Comment by shashwat-sh** [comment]
For a given dimension, the following plus and minus pairs are possible:

> _minus_, _plus_:
Bloch, Bloch
Symmetry, PEC
Symmetry, PMC
Symmetry, PBC
PML, PML
PML, PEC
PML, PMC
PEC, PML
PMC, PML
P(E/M/B)C, P(E/M/B)C

The following are forbidden:
> _minus_, _plus_:
Bloch, not Bloch
not Bloch, Bloch
any, Symmetry (i.e. symmetry allowed on minus side only)
PML, PBC
PBC, PML

**Comment by tylerflex** [comment]
Cool, thanks.  are there any forbidden combinations of x, y, z boundary conditions?

**Comment by shashwat-sh** [comment]
> Cool, thanks. are there any forbidden combinations of x, y, z boundary conditions?

Not really. The only consideration is that if one uses `BlochBoundary.from_source()` along, say `x` and `y`, they should be careful that the same source and background medium should be used along both dimensions. We could add this as a validator if needed.

**Comment by tylerflex** [comment]
Some ideas

## Global (`BoundarySpec`)

* `BoundarySpec() = BoundarySpec(x=Periodic, y=Periodic, z=Periodic)`      # default periodic on all sides
* `BoundarySpec.bloch_from_source(source, opposite_side=PMLSide())`
* `BoundarySpec.pml(x=True, z=True)`

## One Dimension (eg. `BoundarySpec.x`)

* `Bloch, Bloch` -> `BlochBoundary(phase=0.3)`
* `PML, PML` -> `PML()`
* `PBC, PBC` -> `Periodic`
* `Symmetry, PEC` ->` Symmetry(eigenvalue=±1, opposite_side=PEC)`
* `Symmetry, PMC` ->` Symmetry(eigenvalue=±1, opposite_side=PMC)`
* `Symmetry, PBC` -> `Symmetry(eigenvalue=±1)`
* `Symmetry, PML` -> `Symmetry(eigenvalue=±1, opposite_side=PMLSide())`

## Different on each side
* `PML, PEC` -> `Boundary1D(minus=PMLSide(), plus=PEC)`
* `PML, PMC` -> `Boundary1D(minus=PMLSide(), plus=PMC)`
* `PML, PML` -> `Boundary1D(minus=PMLSide(num_layers=10), plus=PMLSide(num_layers=20))`
* `PBC, P*C` -> `Boundary1D(plus=P*C)` # default of minus and plus is `PeriodicSide`

**Comment by shashwat-sh** [comment]
Here's a possible architecture, based on all the comments above.
```python
Boundary(Tidy3dBaseModel):
    #""" Defines boundary on one side (PBC, PML, PEC, etc.)."""

class Periodic(Boundary):
    #"""periodic BC"""

class Bloch(Boundary):
    #"""Bloch BC"""

class PECBoundary(Boundary):
    #"""Perfect electric conductor BC"""

class PMCBoundary(Boundary):
   """Perfect magnetic conductor BC"""

# PML, StablePML, Absorber etc. as previously defined

Boundary1D(Tidy3dBaseModel):
     plus : Boundary = Periodic()
     minus : Boundary = Periodic()

PML1D(Boundary1D, PML):
    #"""Set plus and minus to the same PML, defined as usual"""

Bloch1D(Boundary1D, Bloch):
    #"""Set plus and minus to the same Bloch BC, defined as usual"""

PEC1D(Boundary1D, PECBoundary):
    #"""Set plus and minus to PEC"""

PMC1D(Boundary1D, PMCBoundary):
    #"""Set plus and minus to PMC"""

BoundarySpec(Tidy3dBaseModel):

   x: Boundary1D = Boundary1D()
   y: Boundary1D = Boundary1D()
   z: Boundary1D = Boundary1D()

   @property
   def to_list(self):
   #"""Returns list of list used in internals"""

   @classmethod
   def pml(cls, x: bool = False, y: bool = False, z: bool = False):
   #"""Default PML along specified directions
   #Default all true? Or all false?
   #Latter seems safer but why would anyone call .pml() if they don't want all sides to be PML?"""

   @classmethod
   def pec(cls, x: bool = False, y: bool = False, z: bool = False):
   #"""PEC along specified directions - need to decide on default true or false"""

   @classmethod
   def pmc(cls, x: bool = False, y: bool = False, z: bool = False):
   #"""PMC along specified directions - need to decide on default true or false"""

```
Then the examples from Tyler's first comment (and some additional ones) become:

## Common Use Cases

### Nothing, just periodic
```python
# dont specify anything (default `BoundarySpec()`)
```

### PML on one or more sides
```python
boundaries = BoundarySpec(x=None, y=td.PML1D(num_layers=20), z=td.PML1D()) # pml customizable
boundaries = BoundarySpec.pml(y=True, z=True) #shortcut, default PML only, OR
boundaries = BoundarySpec.pml(x=False) # depending on which is the default
```

### PEC, PMC on one or more sides
```python
boundaries = BoundarySpec(x=td.PEC1D, y=td.PML1D()) # z = td.Periodic() by default
boundaries = BoundarySpec.pec(y=True, z=True) # shortcut for PEC with PBC
boundaries = BoundarySpec.pmc(x=True) # shortcut for PMC with PBC
```

### PML different on + and -
```python
boundaries = BoundarySpec(
    z=td.PML1D(
        plus=td.PML(num_layers=10),
        minus=td.PML(num_layers=20)
    )
)
```

### Symmetry on one or more sides
```python
boundaries = BoundarySpec(
    x=None,
    y=td.PML1D(),
    z=td.PML1D()
)
symmetry = (0, 0, 1) # same as before, with warning to remind user that the minus side BC is overridden by symmetry

```
### Bloch boundaries - not sure about this yet
```python
boundaries = BoundarySpec.bloch(kx=0.5, ky=0.2, z=td.PML1D()) # yeah, this one is tricky, I'll have to think on it some more
```
## Notes
The inheritance in `PML1D(Boundary1D, PML)` might require further thought. It would be nice to be able to initialize `PML1D` with either `num_layers` or by specifying `plus` and `minus` directly, e.g.
```python
pml1d = td.PML1D(plus=td.PML(num_layers=10), minus=td.PML(num_layers=20))
# OR
pml1d = td.PML1D(num_layers=10)
```
I'm not sure if that breaks any OOP / pydantic rules though.

**Comment by tylerflex** [comment]
This looks pretty good.  A few general comments:
* Probably the `Boundary1D` will be used a lot more than the `Boundary`.  So I wonder if these things should drop the `1D` in their name. For example `PEC` could be a `Boundary1D` and then `PECBoundary` could remain a `Boundary`?  Same for PML?
* I feel like defaults of `False` make sense in those class methods. basically to create `.pml()` you need to switch them "on" rather than off.
* About the last note, I'm not really sure, one way is to make `num_layers` a `Field()` and validate so that it only is accepted if `plus` and `minus` are not defined?  Perhaps a class method might be a better way to do it though. `td.PML1D.from_specs(num_layers=10)`?

**Comment by shashwat-sh** [comment]
>     * Probably the `Boundary1D` will be used a lot more than the `Boundary`.  So I wonder if these things should drop the `1D` in their name. For example `PEC` could be a `Boundary1D` and then `PECBoundary` could remain a `Boundary`?  Same for PML?

Yeah that's true. I have two hesitations about this though:
1. The names will conflict with the existing `PML()` class and `PEC` instance of `PECMedium`. We could change those original names, but that would be a pretty major change which will propagate everywhere that `PML()` and `PEC` are used.
2. There's a nice consistency in that `PML1D` => `Boundary1D`, same for the other `*1D` classes. It's not a big deal, but it does seem like a useful reminder that it's a class containing boundary conditions for both plus and minus sides.

The second point is not too important I guess, but I think the first one is worth thinking about.

**Comment by shashwat-sh** [comment]
Ok, I think I've actually found a better solution which addresses that last note and also my concern above, while getting rid of the "1D" in the names. Basically, those convenience 1D classes may be better off being classmethods of Boundary1D:

```python
class Boundary1D(Tidy3dBaseModel):
    """Boundary conditions at the minus and plus extents along a dimension

    Example
    -------
    >>> boundary1d = Boundary1D(plus = PML(), minus = PECBoundary())
    """

    plus: Boundary = pd.Field(
        Periodic(),
        title="Plus BC",
        description="Boundary condition on the plus side along a dimension."
        )

    minus: Boundary = pd.Field(
        Periodic(),
        title="Minus BC",
        description="Boundary condition on the minus side along a dimension."
        )

    @classmethod
    def pml(cls, num_layers: pd.NonNegativeInt = 12, parameters: PMLParams = DefaultPMLParameters):
        """PML boundary specification on both sides along a dimension.

        Parameters
        ----------
        num_layers : int
            Number of layers of standard PML to add to + and - boundaries.
        parameters : :class:`PMLParams`
            Parameters of the complex frequency-shifted absorption poles.

        Example
        -------
        >>> pml1d = Boundary1D.pml(num_layers=20)
        """
        plus = PML(num_layers=num_layers, parameters=parameters)
        minus = PML(num_layers=num_layers, parameters=parameters)
        return cls(plus=plus, minus=minus)

    @classmethod
    def bloch(cls, bloch_vec: Complex):
        """Bloch boundary specification on both sides along a dimension.

        Parameters
        ----------
        bloch_vec : `Complex`
            Normalized component of the Bloch vector in units of 2 * pi / (size along dimension)
            in the background medium, along the dimension in which the boundary is specified.

        Example
        -------
        >>> bloch1d = Boundary1D.bloch(bloch_vec=1)
        """
        plus = BlochBoundary(bloch_vec=bloch_vec)
        minus = BlochBoundary(bloch_vec=bloch_vec)
        return cls(plus=plus, minus=minus)

    @classmethod
    def bloch_from_source(
        cls, source: BlochSourceType, domain_size: float, axis: Axis, medium: Medium = None
        ):
        """Bloch boundary specification on both sides along a dimension based on a given source.

        Parameters
        ----------
        source : Union[:class:`GaussianBeam`, :class:`ModeSource`, :class:`PlaneWave`]
            Angled source.
        domain_size: float
            Size of the domain in the direction normal to the Bloch boundary
        axis: int
            Axis normal to the Bloch boundary
        medium : :class:`.Medium`
            Background medium associated with the Bloch vector.
            Default: free space.
        """
        plus = BlochBoundary.from_source(
            source=source, domain_size=domain_size, axis=axis, medium=medium)
        minus = BlochBoundary.from_source(
            source=source, domain_size=domain_size, axis=axis, medium=medium)
        return cls(plus=plus, minus=minus)

    @classmethod
    def pec(cls):
        """PEC boundary specification on both sides along a dimension.

        Example
        -------
        >>> pec1d = Boundary1D.pec()
        """
        plus = PECBoundary()
        minus = PECBoundary()
        return cls(plus=plus, minus=minus)

    @classmethod
    def pmc(cls):
        """PMC boundary specification on both sides along a dimension.

        Example
        -------
        >>> pmc1d = Boundary1D.pmc()
        """
        plus = PMCBoundary()
        minus = PMCBoundary()
        return cls(plus=plus, minus=minus)

class BoundarySpec(Tidy3dBaseModel):

   x: Boundary1D = Boundary1D()
   y: Boundary1D = Boundary1D()
   z: Boundary1D = Boundary1D()

   @property
   def to_list(self):
   #"""Returns list of list used in internals"""

   @classmethod
   def pml(cls, x: bool = False, y: bool = False, z: bool = False):
   #"""Default PML along specified directions"""

   @classmethod
   def pec(cls, x: bool = False, y: bool = False, z: bool = False):
   #"""PEC along specified directions"""

   @classmethod
   def pmc(cls, x: bool = False, y: bool = False, z: bool = False):
   #"""PMC along specified directions"""
```
This has the added advantages that:
- it's much easier to keep adding these convenience classmethods as needs arise
- it's consistent with the convenience classmethods included in `BoundarySpec`.
What do you think?

**Comment by tylerflex** [comment]
This seems like a good solution!  I'm wondering if somehow we can get rid of the 1D in the `Boundary1D`.  For example, 

`BoundarySpec` (global) -> `Boundary` (1D) -> `BoundaryEdge` (one side).

does that make sense or does it throw everything off?

**Comment by shashwat-sh** [comment]
I think that makes sense
