### ISSUE TITLE
Updater enhancements

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#399]

**Comment by momchil-flex** [comment]
- [ ] Call updater upon `web.load()`
- [ ] Or - call the updater for every simulation loading function like `from_file` and `parse_raw`?
- [ ] Currently, updater requires that a dummy function is created for every minor bump, e.g. 2.0 -> 2.1. This is fine, but if we want to not have to require that and only provide functions when there is a change, then we need to modify it.

**Comment by tylerflex** [comment]
I dont understand the 3rd point, in the current updater it will update from one version to any other version specified in the decorator, ie.
```py
@updates_to_version("1.3.x", "1.4.0")
def update_1_3(sim_dict: dict) -> dict:
    """Updates version 1.3 to 1.4."""
    pass
```

so if we come out with a new version (ie, `1.5`) we would simply need to change the 2nd argument to `@updates_to_version`. At least this is my understanding, am I not understanding something?

**Comment by momchil-flex** [comment]
If you do that and you give it a version 1.4 json, it won't find where to start from.

**Comment by momchil-flex** [comment]
Yeah something like that. It's not really needed right now so up to you whether to try to put in now or leave for next major update.

**Comment by tylerflex** [comment]
if 1.4.0 is imminent, let's just put this off for the next major release.  There are a few subtleties that came up when I tried to define it.

One strategy:
* Only tag the "from" version in each update function.
* Implied that if the "from" update functions are v1, v2, v3, then the update functions perfom
* v1 updates from v1 => v2
* v2 updates from v2 => v3
* v3 updates from v3 => __version__
* If updater initialized with version "v", find the highest tagged update function with version <= "v" and start the update chain.

Edge cases:
* supplied v < v1.  Will fail (expected).
* supplied v > v3.  Will do nothing but change version tag to __version__.

Any thoughts?

**Comment by momchil-flex** [comment]
I think that makes sense. We can put it off for now though yeah.
