### ISSUE TITLE
Error running task

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#414]
Why are some tasks have errors when running?

```
[19:14:53] INFO     Auto meshing using wavelength 1.5500 defined from        [grid_spec.py](file:///home/jmatres/mambaforge/lib/python3.9/site-packages/tidy3d/components/grid/grid_spec.py):[478](file:///home/jmatres/mambaforge/lib/python3.9/site-packages/tidy3d/components/grid/grid_spec.py#478)
                    sources.                                                                 
           INFO     Uploaded task '3ee3404ce695f61cf7390c2475aa0e84' with       [webapi.py](file:///home/jmatres/mambaforge/lib/python3.9/site-packages/tidy3d/web/webapi.py):[120](file:///home/jmatres/mambaforge/lib/python3.9/site-packages/tidy3d/web/webapi.py#120)
                    task_id 'b31563f9-62a2-4c2e-b136-c0966fef63dd'.                          
[19:14:56] INFO     Uploaded task 'ec25b3cb1697f0d58981a9e035e6a09d' with       [webapi.py](file:///home/jmatres/mambaforge/lib/python3.9/site-packages/tidy3d/web/webapi.py):[120](file:///home/jmatres/mambaforge/lib/python3.9/site-packages/tidy3d/web/webapi.py#120)
                    task_id 'a5a962a5-61d8-42f9-b63b-72f67ddd1d33'.                          
[19:14:57] ERROR    Error running task!

```

(WebError(...), 'Error running task!')

**Comment by momchil-flex** [comment]
I really don't understand what's happening, all of your recent tasks have success status but somehow at some point the `web.monitor` function seems to decide that they error. I'll try to reproduce this and figure out what's going on, but meanwhile you may want to add a functionality to the gdsfactory plugin to try and download the simulations on demand. Basically what happens currently is that the `monitor` function that waits for them to finish breaks, but if you try to download now you will succeed.

Note that you could try using our [Batch](https://docs.flexcompute.com/projects/tidy3d/en/latest/notebooks/WebAPI.html#Batch-Processing) container. It seems that currently you are using a pool executor to parallelize the job submission, but maybe that's producing some strange interference. Our native Batch provides a better way to access a group of simulations, and can be loaded at a later time, and even saved to be loaded in a latter session.

**Comment by momchil-flex** [comment]
I sent a [gdsfactory PR](https://github.com/gdsfactory/gdsfactory/pull/455) with the initial work on introducing our own Batch rather than the pool executor. I suspect that this should fix this issue, but let me know if it doesn't.

**Comment by joamatab** [comment]
Awesome, just released a new gdsfactory version with your improvements. Thank you Momchil
