### ISSUE TITLE
environment credentials check

### ISSUE THREAD

**Issue by venkatkorapaty** [flexcompute/tidy3d#437]
We get a "Error: Failed to log in with environment credentials." from the `get_credentials` function in `tidy3d/web/auth.py`.
We set environment variables for `TIDY3D_USER` and `TIDY3D_PASS` before using tidy3d (in a jupyter notebook).

They are set as fallback placeholders with empty strings for users with a cached password file in their home directory, leading to this condition https://github.com/flexcompute/tidy3d/blob/7cf222e3e799fcec34a4d97daebdee78541d6e50/tidy3d/web/auth.py#L55
which will fail. This leads to accumulated failed attempts.

We do have a fix on our end, but it is not ideal the way we are handling the credentials.

It would help if the condition there changed to `os.environ.get("TIDY3D_USER") and (os.environ.get("TIDY3D_PASS") or os.environ.get("TIDY3D_PASS_HASH"))` as an empty string will evaluate the condition to `False` in python.

**Comment by momchil-flex** [comment]
Thanks for the suggestion, will be part of next release!
