### ISSUE TITLE
m1 install issue

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#441]
When installing tidy3d-beta on M1 macOs there is an issue installing nlopt

To reproduce:

- install [mamba](https://gdsfactory.github.io/gdsfactory/notebooks/_2_install.html)
- run pip install tidy3d-beta

<img width="1137" alt="Screen Shot 2022-07-22 at 14 13 44" src="https://user-images.githubusercontent.com/4514346/180437239-e915dc17-5515-48cd-b026-0654763bb33a.png">

<img width="1393" alt="Screen Shot 2022-07-22 at 14 18 48" src="https://user-images.githubusercontent.com/4514346/180437774-3fd0d030-d55b-4d9f-a46d-1b46f792a59f.png">

## to fix

1. mamba install nlopt
2. pip install tidy3d-beta

ideas to fix this:
- provide a conda package for tidy3d
- make nlopt an optional dependency
- publish nlopt wheels to pypi with no architecture

**Comment by joamatab** [comment]
related to https://github.com/stevengj/nlopt/issues/439

**Comment by momchil-flex** [comment]
Thanks! I think we should make `nlopt` optional. This goes together with something we discussed with @tylerflex recently, which is not importing the plugins in the main `tidy3d.__init__`. `nlopt` is only used in the dispersive material fitter.
