### ISSUE TITLE
launcher for binder and colab

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#468]
How could we add a launch button for binder and colab in the docs?

See for example in [sax](https://flaport.github.io/sax/)

https://jupyterbook.org/en/stable/interactive/launchbuttons.html

**Comment by tylerflex** [comment]
We don't have a binderhub yet, but you can launch from binder using the link at the top of each notebook. It would be good to set up a binderhub some time: https://binderhub.readthedocs.io/en/latest/zero-to-binderhub/setup-prerequisites.html

**Comment by tylerflex** [comment]
@xin-flex @lei-flex do you have thoughts on this? with browser based python hosting, does binder become irrelevant? or should we still work on this?

**Comment by xin-flex** [comment]
I believe the browser based python hosting serves this same purpose, so we can close this issue.
