### ISSUE TITLE
Issue on page /changelog.html load data question

### ISSUE THREAD

**Issue by chenyudong92** [flexcompute/tidy3d#495]
When I want to load data. using below script:
flux_src = []
flux_fcl = []

for case_name, sim_data in batch_data.items():          ###         path_dir=tsk_Name + '/Data' 
    flux_fcl.append( sim_data['flux_at_focal']   )
    flux_src.append(  sim_data['flux_at_source']    )
    print(case_name + '\n')
    print(sim_data.log)
####end

It shows problem:
TypeError: 'method' object is not subscriptable

how to solve it?

**Comment by momchil-flex** [comment]
I am not sure just from this script. Can you `print(type(sim_data))`?

By the way: note that in version >= 1.6, you need to add an extra `.flux` to get the actual flux data array of flux monitors. So instead of `sim_data['flux_at_focal']` you may want to do `sim_data['flux_at_focal'].flux`. This was introduced in unifying the data structures and is in accordance with everything else (e.g. `.Ex` for field data, `.amps` for mode amplitude data). I don't think this is the cause of your error though.

**Comment by chenyudong92** [comment]
> 

![image](https://user-images.githubusercontent.com/57641431/187989386-49addf1a-b5bc-4770-a9fe-0cfdd67906b2.png)

**Comment by chenyudong92** [comment]
> .flux

![image](https://user-images.githubusercontent.com/57641431/187989570-b6e14b0c-8988-48f0-a776-2fc8ca0ed356.png)

this is check sim_data directly. sim_data.log didn't work also

**Comment by momchil-flex** [comment]
It's a bit hard for me to deconstruct what exactly went wrong for you. How is `batch_data` loaded?

**Comment by chenyudong92** [comment]
> It's a bit hard for me to deconstruct what exactly went wrong for you. How is `batch_data` loaded?

####################     Load a simulation from hdf5 file       #####################
# batch_data = batch.load(path_dir=tsk_Name + '/Data')

######## load the task id from txt file
data_dict = dict()
tsk_id_read = np.genfromtxt( tsk_Name + '/Data/' + 'Task_IDs.txt', delimiter='\t', dtype='str')
inf_dict = dict()
for ii in tsk_id_read:
    inf_dict[ii[0]] = ii[1]
####end

######## load data by task id 
for case_name in sim_dict.keys():
    tsk_id = inf_dict[case_name]
    data_dict[case_name] = td.SimulationData.from_file( tsk_Name + '/Data/' + tsk_id + '.hdf5').renormalize
###end

batch_data = data_dict

#%%

#### extract flux components

flux_src = []
flux_fcl = []

for case_name, sim_data in batch_data.items():          ###         path_dir=tsk_Name + '/Data' 
    flux_fcl.append( sim_data['flux_at_focal'].flux   )
    flux_src.append( sim_data['flux_at_source'].flux  )
    print(case_name + '\n')
    # print(sim_data.log)
####end

#### extract lens simulation data

lens_data = batch_data[case_name_1]

This is full script to load data after simulation finished

**Comment by momchil-flex** [comment]
I see. Yeah you just need to remove `.renormalize` in this line `data_dict[case_name] = td.SimulationData.from_file( tsk_Name + '/Data/' + tsk_id + '.hdf5').renormalize`. I would also recommend considering using our in-built batch functionality: https://docs.flexcompute.com/projects/tidy3d/en/latest/notebooks/WebAPI.html?highlight=batch#Batch-Processing

**Comment by chenyudong92** [comment]
> 

Thanks for your help. Such data could be loaded. But seems FluxData.to_numpy is not working now? If I want to save fluxdata into .csv like below script. What should I do?
####################     Load a simulation from hdf5 file       #####################
# batch_data = batch.load(path_dir=tsk_Name + '/Data')

######## load the task id from txt file
data_dict = dict()
tsk_id_read = np.genfromtxt( tsk_Name + '/Data/' + 'Task_IDs.txt', delimiter='\t', dtype='str')
inf_dict = dict()
for ii in tsk_id_read:
    inf_dict[ii[0]] = ii[1]
####end

######## load data by task id 
for case_name in sim_dict.keys():
    tsk_id = inf_dict[case_name]
    data_dict[case_name] = td.SimulationData.from_file( tsk_Name + '/Data/' + tsk_id + '.hdf5')
###end

batch_data = data_dict

#%%

#### extract flux components

flux_src = []
flux_fcl = []

for case_name, sim_data in batch_data.items():          ###         path_dir=tsk_Name + '/Data' 
    flux_fcl.append( sim_data['flux_at_focal']   )
    flux_src.append( sim_data['flux_at_source'] )
    print(case_name + '\n')
    print(sim_data.log)
####end

#### extract lens simulation data

lens_data = batch_data[case_name_1]


################################################################################################################################
################################################################################################################################
################################################################################################################################


#%%


#### flux and wavelength data save

data_out_folder = tsk_Name + '/Data_Export/'
pd.DataFrame(  wavelengths   ).to_csv(data_out_folder + 'Data_Wavelength.csv', header=False, index=False)
#%%
# pd.DataFrame(   [mm.to_numpy() for mm in flux_drk]  ).to_csv(data_out_folder + 'Data_' + flux_2D_drk.name + '.csv', header=False, index=False)
pd.DataFrame(   [mm.to_numpy() for mm in flux_src]  ).to_csv(data_out_folder + 'Data_' + flux_2D_src.name + '.csv', header=False, index=False)
pd.DataFrame(   [mm.to_numpy() for mm in flux_fcl]  ).to_csv(data_out_folder + 'Data_' + flux_2D_fcl.name + '.csv', header=False, index=False)

error is AttributeError: 'FluxData' object has no attribute 'to_numpy'

**Comment by momchil-flex** [comment]
You are missing the `.flux` here `flux_fcl.append( sim_data['flux_at_focal'] )` again.

**Comment by chenyudong92** [comment]
> You are missing the `.flux` here `flux_fcl.append( sim_data['flux_at_focal'] )` again.

Thanks! All script working! I will follow your suggestion to use  in-built batch functionality in future
