### ISSUE TITLE
signal SIGSEGV (Address boundary error) with complex permittivity profiles in mode solver

### ISSUE THREAD

**Issue by simbilod** [flexcompute/tidy3d#502]
**Describe the bug**
I am trying to solve for the complex effective index of an arbitrary waveguide, where each entry in the permittivity matrix may be slightly different.

* For a uniform waveguide (e.g. core index 3.45 + 1j*x with x arbitrary but same everywhere), there is no problem
* For some arbitrary waveguide (some index matrix with 3.45 + 1j*x, with x < 10^-7 different everywhere), there is no problem. Everything works great with real numbers too.

As soon as I let my arbitrary index matrix have imaginary entries larger than 10^-7, I get `Job 1, 'my_script_name' terminated by signal SIGSEGV (Address boundary error)`

All numpy arrays have dtype np.complex128

**To Reproduce**
This is being developed at https://github.com/simbilod/gdsfactory/tree/tidy3D_imagModes , running script `gdsfactory/gdsfactory/simulation/devsim\get_simulation_xsection.py` on that branch after installing dependencies should give the error

**Expected behavior**
Solver should return an index, or have more detailed convergence failure

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by momchil-flex** [comment]
I tried to reproduce but I got the following error, even after `pip install devsim`: `ModuleNotFoundError: No module named 'devsim.python_packages'`

I don't see a requirements file for your specific fork?

More generally, it will probably be hard for me to get through several layers of wrappers to debug this problem. It would be great if you can provide a set of inputs for the tidy3d `compute_modes` function that produces the error. That would clarify whether the error is in Tidy3d, the gdsfactory wrapper for our mode solver, or your devsim wrapper for the gdswrapper.

**Comment by momchil-flex** [comment]
I tried adding `0.1j * np.random.rand(*eps.shape)` to each of the permittivity arrays in one example mode solve and it worked fine. Same with `1e-5j`. So yeah best would be if you could directly provide inputs that break `compute_modes`.

**Comment by simbilod** [comment]
Thanks for the quick reply -- yeah DEVSIM is not package-managed so it is troublesome

In the process of making a toy example, I found that saving the relevant problematic input arrays to disk (x,y, nx, ny, nz) and loading them in a different script to run `compute_modes` does work. So something else is going on in this wrapper hell.
