### ISSUE TITLE
Issue on page /_autosummary/tidy3d.GaussianBeam.html

### ISSUE THREAD

**Issue by chenyudong92** [flexcompute/tidy3d#508]
I want to use Gaussianbeam source. But I am confuse about source size, center and waist_radius  and waist_distance. Could you show me some examples to explain how is it woking? Thanks for your help!

**Comment by momchil-flex** [comment]
It is used for example [here](https://docs.flexcompute.com/projects/tidy3d/en/latest/notebooks/GratingCoupler.html). Also have a look at [this page](https://en.wikipedia.org/wiki/Gaussian_beam) and the first equation.

More practically, the source size should be big enough that the source fields decay by the edges of the source plane. The source center defines where the center of the beam is located in the source plane. The waist radius is the radius at the narrowest portion of the beam, and the waist distance along the propagation direction between the source plane and the point where the waist lies. By default, `waist_distance = 0`, which means that the source waist is at the position of the source plane (the beam will be expanding away from the source plane in either direction). However, maybe you want the beam waist (the "focus" of the beam) to lie somewhere differently than where you are injecting the source. In that case, you can use the `waist_distance` argument. For example if you place a source at z = -1, and set `waist_distance = -2`, the narrowest part of the beam will be at `z = 1`.

Does that clarify everything?

**Comment by chenyudong92** [comment]
Thanks for your help. One more question, If I have a gaussianbeam souce with given beam waist and divergency angle seperately. Could I generate a source related with the beam waist and divergency angle? I means for ideal guassian source, the given wasit will get a divergency angle. But, if the M2 parameter >1. Could I generate some gaussian beam source with it?

Sincerely,
Yudong Chen
M.S. of Electrical Engineering at SMU
Ph.D. Student of Electrical Engineering at UTA
Office at 2nd floor at Nano Fab in UTA
________________________________
发件人: momchil-flex ***@***.***>
发送时间: 2022年9月14日 22:12
收件人: flexcompute/tidy3d ***@***.***>
抄送: Chen, Yudong ***@***.***>; Author ***@***.***>
主题: Re: [flexcompute/tidy3d] Issue on page /_autosummary/tidy3d.GaussianBeam.html (Issue #508)


[External]

It is used for example here<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.flexcompute.com%2Fprojects%2Ftidy3d%2Fen%2Flatest%2Fnotebooks%2FGratingCoupler.html&data=05%7C01%7Cyudong.chen%40mavs.uta.edu%7C985a742132684b1f433d08da96c82526%7C5cdc5b43d7be4caa8173729e3b0a62d9%7C0%7C0%7C637988083608517311%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=g0I2wqJAU5Hp3MVlzKqUm4YY%2B3nbBfHiu%2F9KHKhARs0%3D&reserved=0>. Also have a look at this page<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FGaussian_beam&data=05%7C01%7Cyudong.chen%40mavs.uta.edu%7C985a742132684b1f433d08da96c82526%7C5cdc5b43d7be4caa8173729e3b0a62d9%7C0%7C0%7C637988083608517311%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DU69tSO3GLW6SxRuS22zd0WYGcN0t%2BsOuU4k9fg%2FGnU%3D&reserved=0> and the first equation.

More practically, the source size should be big enough that the source fields decay by the edges of the source plane. The source center defines where the center of the beam is located in the source plane. The waist radius is the radius at the narrowest portion of the beam, and the waist distance along the propagation direction between the source plane and the point where the waist lies. By default, waist_distance = 0, which means that the source waist is at the position of the source plane (the beam will be expanding away from the source plane in either direction). However, maybe you want the beam waist (the "focus" of the beam) to lie somewhere differently than where you are injecting the source. In that case, you can use the waist_distance argument. For example if you place a source at z = -1, and set waist_distance = -2, the narrowest part of the beam will be at z = 1.

Does that clarify everything?

―

**Comment by momchil-flex** [comment]
Sorry, currently only an ideal Gaussian beam with M2 = 1 is supported. We are however working on a feature to allow custom source fields as specified by the user. When this is available, you could put whatever source you like by providing the E and H fields at the source plane.
