### ISSUE TITLE
Issue on page /material_library.html

### ISSUE THREAD

**Issue by chenyudong92** [flexcompute/tidy3d#511]
Hi,
When I want to use c-Si library to generate a simulation structure. I always get the warning shows out of frequency range and the structure creating is fail. But, I am double check the range that match with the library frequency range. I put my script below, could you help me to figure it out?

#%%
# standard python imports
import numpy as np
import matplotlib.pyplot as plt

# tidy3D import
import tidy3d as td
from tidy3d import web
from tidy3d import material_library
# %%
Nfreq = 1000
wavelengths = np.linspace(0.4, 0.9, Nfreq)
freqs = td.constants.C_0 / wavelengths
freq0 = freqs[len(freqs)//2]
freqw = freqs[0] - freqs[-1]

# Define material properties
n_BaF2 = 1.45
n_air=1
n_Ge = 4
Si=material_library['cSi']['Green2008']
air = td.Medium(permittivity=n_air**2)
# BaF2 = td.Medium(permittivity=n_BaF2**2)
# Ge = td.Medium(permittivity=n_Ge**2)
# Ge = td.Medium(permittivity=n_Ge**2)
#%%
# space between resonators and source
spc = 8

# geometric parameters
Px = Py = P = 4.2
h = 2.53
L1 = 3.036
L2 = 2.024
w1 = w2 = w = 1.265

# resolution (should be commensurate with periodicity)
dl = 0.6 / 32
#%%
# total size in z and [x,y,z]
Lz = spc + h + h + spc
sim_size = [Px, Py, Lz]

# Define structure

cell1 = td.Structure(
    geometry=td.Box(
        center=[(L1/2)-L2, -w1/2, h/2],
        size=[td.inf, td.inf, h],
    ),
    medium=Si,
    name='cell1'
)

# cell2 = td.Structure(
#     geometry=td.Box(
#         center=[-L2/2, w2/2, h/2],
#         size=[L2, w2, h],
#     ),
#     medium=Ge,
#     name='cell2'
# )
cell2 = td.Structure(
            geometry=td.Cylinder(
                center =(0, 0, h/2),
                axis = 2,                       ######   axis (0,1,2) -> (x,y,z)
                radius = 0.1,
                length = h 
            ),
    medium=air,
    name='cell2'
)
#%%
# time dependence of source
gaussian = td.GaussianPulse(freq0=freq0, fwidth=freqw)

# plane wave source
source = td.PlaneWave(
        source_time=gaussian,
        size=(td.inf, td.inf, 0),
        center=(0,0,Lz/2 - spc + 2*dl),
        direction='-',
        pol_angle=0)

# Simulation run time.  Note you need to run a long time to calculate high Q resonances.
run_time = 3e-11
#%%
# monitor fields on other side of structure (substrate side) at range of frequencies
monitor = td.FluxMonitor(
        center=[0., 0., -Lz/2 + spc - 2 * dl],
        size=[td.inf, td.inf, 0],
        freqs=freqs,
        name='flux')
#%%
grid_spec = td.GridSpec(
    grid_x = td.UniformGrid(dl=dl),
    grid_y = td.UniformGrid(dl=dl),
    grid_z = td.AutoGrid(min_steps_per_wvl=32)
)

# normalizing run (no Ge) to get baseline transmission vs freq
# can be run for shorter time as there are no resonances
sim_empty = td.Simulation(size=sim_size,
                    grid_spec=grid_spec,
                    structures=[substrate],
                    sources=[source],
                    monitors=[monitor],
                    run_time=run_time/10,
                    boundary_spec=td.BoundarySpec.pml(z=True))

# run with Ge nanorod
sim_actual = td.Simulation(size=sim_size,
                    grid_spec=td.GridSpec.uniform(dl=dl),
                    # structures=[substrate,cell1,cell2],
                    structures=[cell1,cell2],
                    sources=[source],
                    monitors=[monitor],
                    run_time=run_time,
                    boundary_spec=td.BoundarySpec.pml(z=True))
# Structure visualization in various planes

fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(10, 6))
sim_actual.plot_eps(x=0, ax=ax1)
sim_actual.plot_eps(y=-0.1, ax=ax2)
sim_actual.plot_eps(z=0.1, ax=ax3)
plt.show()
#%%
# run all simulations, take about 2-3 minutes each with some download time
batch = web.Batch(
    simulations={
        'norm': sim_empty,
        'actual': sim_actual
    }
)
batch_data = batch.run(path_dir='data')
#%%
# batch_data = batch.load(path_dir='data')
# transmission = batch_data['actual']['flux'].flux / batch_data['norm']['flux'].flux
# reflection = 1 - transmission
# plot transmission, compare to paper results, look similar
fig, ax = plt.subplots(1, 1, figsize=(6, 4.5))
plt.plot(wavelengths, reflection, 'k', label='R')
plt.plot(wavelengths, transmission, 'r--', label='T')
plt.xlabel('wavelength ($\mu m$)')
plt.ylabel('Magnitude')
plt.xlim([8.8, 12])
plt.ylim([0.0, 1.0])
plt.legend()
plt.show()

**Comment by momchil-flex** [comment]
So the only error I get in your script is here:

```
sim_empty = td.Simulation(size=sim_size,
                    grid_spec=grid_spec,
                    structures=[substrate],
                    sources=[source],
                    monitors=[monitor],
                    run_time=run_time/10,
                    boundary_spec=td.BoundarySpec.pml(z=True))
```

There is no structure called `substrate`. 

The warnings about the frequency range of the dispersive medium are not blocking to your simulation. In fact they come from the `plot_eps` functions, which should be used with care for dispersive materials as they need to know at what frequecny to compute the permittivity. Ideally I would just recommend using `plot` instead, which shows different materials in different colors. If you do want to plot the permittivity specifically, I would recommend supplying `plot_eps(... , freq=freq0)`. Otherwise the function just gets the permittivity at infinite frequency, which produces the warnings, and also does not show the structure right, since `eps_infinity = 1` for this model.
