### ISSUE TITLE
Test Coverage: Polygon / RTree

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#524]
A good chunk of the Polygon stuff in viz.py and the various shapely RTree stuff are not covered by tests.
I'm not really sure how those bits work, could we add a few tests for them?
See #516 for more details.

**Comment by momchil-flex** [comment]
What RTree stuff lacks coverage? The only place it's used afaik (and I also searched) is in `grid/mesher.py` and it seems to be all covered already?

The stuff in `viz.py` that mostly lacks coverage is the code we copied from descartes, I can remove some bits that seem to not be needed.

**Comment by tylerflex** [comment]
Ok, hard to keep track of everything but yea does indeed seem like RTree is covered. And yea if you can remove any of the descartes stuff that's not required that would be great, thanks.
