### ISSUE TITLE
Issue on page /notebooks/RingResonator.html

### ISSUE THREAD

**Issue by chenyudong92** [flexcompute/tidy3d#556]
Hi,

I am a new user of Tidy3D. I just want to retrieve the Q-factor with different resonance frequency (or wavelength) of my structure. Are there any examples to help me learn how to get it.

**Comment by momchil-flex** [comment]
Hi!

Thanks for trying Tidy3D. We don't currently have an example about this, but some are in the works for our next release. There are two main approaches you can try meanwhile. One is to compute the spectrum on a dense enough grid in frequency, then use something like [scipy.signal.peak_widths](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.peak_widths.html#scipy.signal.peak_widths) to compute the widths of the peaks in the spectrum. The other is to compute the time series at a point inside the resonator, and use [harminv](https://github.com/aaren/pharminv) on the time series to extract the complex frequencies. We are developing a native Tidy3D function for the latter approach but it is not yet released.

For both approaches, my recommendation would be to work within a fairly narrow-bandwidth that contains only a few resonances. It can be hard to disentangle the Q's of many high-Q modes.
