### ISSUE TITLE
Change color for symmetry = -1 in plotting

### ISSUE THREAD

**Issue by momchil-flex** [flexcompute/tidy3d#558]
The original idea of this color was to be similar to gold as this symmetry is essentially a PEC, but it looks too similar to monitors:

![image](https://user-images.githubusercontent.com/92756559/199101087-f31b2292-3b2f-442c-84a9-3333a64b1069.png)

**Comment by tylerflex** [comment]
Let's just close it. For 3.0 we can reconsider all colors
