### ISSUE TITLE
Option for a "quiet" webapi

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#577]
It's kind of annoying that there's no way (that I know of) to disable progress bars / running man during `web.run()`.

One example is that calling web.run() repeatedly in a loop (ie optimization) erases any printed info each iteration.

Maybe a `quiet=True` kwarg would make sense in some of the webapi functions.

**Comment by momchil-flex** [comment]
Would this be part of An Li's complete web overhaul or is the rich printing not touched there and only deeper internal functionality is?

**Comment by tylerflex** [comment]
No, basically An made a "lower level" webapi that defines types of tasks and how to submit them. Then we use this low level webapi to construct our higher level one that the users interface with. Currently, that higher level one still uses the original rich progresbar and monitoring stuff.
