### ISSUE TITLE
Job running issue

### ISSUE THREAD

**Issue by chenyudong92** [flexcompute/tidy3d#578]
![image](https://user-images.githubusercontent.com/57641431/202292695-85406c11-0bda-4547-ba1e-41d2322b5526.png)

My job keeps in queue and didn't running. Is that my submission script issue or just need waiting?

Is there any time estimation for the queue? Thanks for your help!

**Comment by momchil-flex** [comment]
Hi, I see that the task was submitted at 12:44 and picked up less than 20 minutes later at 13:03. We cannot guarantee immediate start of the run, depending on the load that our servers are dealing with, especially for large tasks (yours has more than 1 billion grid points). In the future please let us know if you experience delays larger than 20 minutes by writing to support@flexcompute.com.
