### ISSUE TITLE
Internal Server Error  

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#596]
Something is happening on the server side

This was working before

```
import gdsfactory as gf
import gdsfactory.simulation.gtidy3d as gt

c = gf.components.taper()
s = gt.get_simulation(c, is_3d=False)
sp = gt.write_sparameters(c)
sim.plot.plot_sparameters(sp)
```

![image](https://user-images.githubusercontent.com/4514346/205513245-f6ad30c9-9d4c-499f-a0ae-557348215e98.png)

**Comment by momchil-flex** [comment]
Hmm. I can run fine, and other jobs were running at the time that you created this issue. May be something related to your account, or your internet connection. Are you consistently experiencing this? Can you successfully log into tidy3d.simulation.cloud and do you still have credits?

**Comment by momchil-flex** [comment]
@lei-flex ?

**Comment by joamatab** [comment]
works great now, thank you for the fast response
