### ISSUE TITLE
How to delete simulation files filter from the web storage ?

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#597]
How can i delete simulation files filter from the web storage using the python API?

I tried
```
from tidy3d import web

web.delete_old()
```
and I still see the same number of 90 tasks, current storage (72G)

![image](https://user-images.githubusercontent.com/4514346/205723465-40894863-5700-4edf-adc3-8b0d19dccd34.png)

something that would be nice is to be able to retrieve all tasks in a pandas dataframe

Also, on the webpage it would be great to filter jobs by size and be able to delete them all

![image](https://user-images.githubusercontent.com/4514346/205720329-77986e18-9536-45b1-b4d7-4f295fee70bc.png)

**Comment by momchil-flex** [comment]
I suspect that these tasks created in 2021 were done with our old client and for some reason `delete_old` in `tidy3d-beta` fails to operate on them. You can delete them from the GUI, or `pip install tidy3d` (still the name of our old client) and use that tidy3d version to try to `delete_old`.

You can retrieve all tasks as a simple dictionary using `web.get_tasks()`.

We'll look into your webpage request!

**Comment by momchil-flex** [comment]
Yeah, it seems like this has broken unfortunately (the time format has changed which breaks this function). We don't really support old tidy3d anymore... So I think your only option is to delete from the web GUI.

**Comment by momchil-flex** [comment]
But we'll look into why delete function in `tidy3d-beta` doesn't apply to those jobs. We may fix that, I'll keep you posted!

**Comment by momchil-flex** [comment]
@xin-flex can we close this?

**Comment by xin-flex** [comment]
Yes. @joamatab confirmed that the delete() and delete_old() function as expected, just need to refresh the UI to see the updated task list.
