### ISSUE TITLE
Creating GaussianBeam source with a set divergence angle

### ISSUE THREAD

**Issue by chenyudong92** [flexcompute/tidy3d#623]
How do I create a GaussianBeam source with different divergency angle? Could you send me some examples? Thanks for your help!

**Comment by momchil-flex** [comment]
The GaussianBeam source uses the paraxial approximation, for which there's a [fixed relationship between the divergence angle and the waist radius](https://en.wikipedia.org/wiki/Gaussian_beam#Beam_divergence).

P.S. When opening issues directly from our docs, please edit the issue title to provide more concrete information about your specific question - I updated the title here. Thanks!
