### ISSUE TITLE
What's the best way to fit nk data?

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#625]
Fit nk data

```
import tidy3d as td

freq = [3e8/1.55, 3e8/1.31]
k = [0, 0]
n = [2., 3]
mat2 = td.Medium.from_nk(n=n, k=k, freq=freq)
```

https://github.com/gdsfactory/gdsfactory/issues/1006

**Comment by momchil-flex** [comment]
`from_nk` can only be used for a single value of n and k if you're interested in one frequency only or the material is weakly dispersive. Unfortunately things are a bit more complicated if you want to [fit dispersive data](https://docs.flexcompute.com/projects/tidy3d/en/latest/notebooks/Fitting.html) - you need to run our fitter as explained here (ideally the [stable fitter](https://docs.flexcompute.com/projects/tidy3d/en/latest/notebooks/Fitting.html#Stable-fitter) for higher chance of avoiding divergence), and make sure that the fit matches the data sufficiently well to your standards (e.g. some media may need many poles to fit, but more poles also make the simulation slower and the cost higher). It is hard to fully automate this beyond what we provide, but we do have a pre-fit [material library](https://docs.flexcompute.com/projects/tidy3d/en/latest/material_library.html?highlight=material%20library).

**Comment by tylerflex** [comment]
closing as question seems answered
