### ISSUE TITLE
test gdsfactory tidy3d plugin in GitHub actions

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#626]
tidy3d is evolving fast, which is great, 
How can we make sure the gdsfactory tidy3d plugin is always working?

How about running?

```
git clone https://github.com/gdsfactory/gdsfactory.git
pip install -e .[tidy3d]
make test-tidy3d
```
as part of the tidy3d Github actions?

**Comment by joamatab** [comment]
https://github.com/gdsfactory/gdsfactory/pull/1022

**Comment by tylerflex** [comment]
@joamatab perhaps it makes more sense to add a test to gdsfactory? We aren't planning any API breaking changes except on major releases, so in principle the gdsfactory plugin should still work for a while. Any breaking changes will be precluded by deprecation warnings until the major release.

**Comment by joamatab** [comment]
Sounds good Tyler, we already have tests for tidy3d plug-in in gdsfactory
