### ISSUE TITLE
Always call simulation updater instead of only in `Simulation.from_file`

### ISSUE THREAD

**Issue by momchil-flex** [flexcompute/tidy3d#630]
Best would be if we have a validator type of thing which calls the updater on the Simulation `values` dictionary before anything else is done. Pydantic validators support `pre=True` argument, in which case the validator gets called before other validation. However, it's not clear to me how to use this on the entire simulation dictionary. Maybe there is some other way that what we need can be done in pydantic.

**Comment by tylerflex** [comment]
I think we could do this through `pd.root_validator(pre=True)`
https://docs.pydantic.dev/usage/validators/#root-validators

**Comment by momchil-flex** [comment]
Ah yeah sounds perfect

**Comment by tylerflex** [comment]
Yea, I wonder can we just completely remove [`Simulation.from_file()`](https://github.com/flexcompute/tidy3d/blob/develop/tidy3d/components/simulation.py#L2018-L2044) in favor of this root validator? That would be great

**Comment by momchil-flex** [comment]
Does it do anything different than the base from_file apart from calling the updater?

**Comment by tylerflex** [comment]
I dont think so.
