### ISSUE TITLE
Postprocessing errors when colocate=True in FieldMonitor

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#631]
When making a notebook, I realized that when colocate is set to True in a FieldMonitor, an error occurs in the postprocessing after the simulation run. No data is downloaded from the server. When setting colocate to False, no error occurs. 

<img width="890" alt="image" src="https://user-images.githubusercontent.com/116006359/209719229-fec11e25-6870-4243-b4c8-626d6334bfae.png">

Links to the job:

https://admin.simulation.cloud/monitoring/tidy3d/tasks/AIDAXWCOWJGJJK765CKFL/18243585-7ad9-4dde-917b-0f1ac18e338b

https://tidy3d.simulation.cloud/workbench?taskId=5702f2dd-8646-4561-8878-eb9b2590d690

**Comment by tylerflex** [comment]
fixed by #636
