### ISSUE TITLE
non uniform grid for mode solver

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#652]
How can we add non uniform grid  to the open source local mode solver?

Something similar to this
https://docs.flexcompute.com/projects/tidy3d/en/latest/notebooks/AutoGrid.html

**Comment by momchil-flex** [comment]
This is related to gdsfactory issue https://github.com/gdsfactory/gdsfactory/issues/1056

Ideally we should use the higher-level ModeSolver class. However, currently this does not support arbitrary permittivity distribution, which is needed in some cases in gdsfactory. We are working on supporting that in Tidy3D 1.9 though.
