### ISSUE TITLE
Gaussian beam power normalization in 2D

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#664]
Currently in Tidy3D, Gaussian beam's power normalization is off in 2D simulations. This is likely the reason why Joaquin's [2D grating coupler](https://github.com/flexcompute/tidy3d/issues/627) result is incorrect. 

In general, when the simulation domain size is smaller than the Gaussian beam waist, not 100% of the power is injected but the normalization still assumes 100% of the power. In a 3D simulation, this is probably fine. It's the user's responsibility to make sure the domain size is considerably larger than the beam waist. However, we can also consider throwing a warning when the domain size is not a few times larger than the beam waist for example. 

In a 2D simulation, the normalization should work completely differently by assuming the Gaussian beam in uniform in the zero dimension. This seems to be the case in both Lumerical and Meep so the normalization works out correctly. 

Details can be found in the attached notebook.

[2D_Gaussian_Beam_Test.zip](https://github.com/flexcompute/tidy3d/files/10457292/2D_Gaussian_Beam_Test.zip)

**Comment by momchil-flex** [comment]
We will look at that, but I'm curious about one thing: is the gaussian beam actually normalized in Meep, or is a normalization run needed? I thought that you always needed normalization runs in Meep. Having a normalization run could be a way to get around this in Tidy3D too, for now.

**Comment by tomflexcompute** [comment]
Oh yeah that's a good point. I think it actually might be the case.

**Comment by momchil-flex** [comment]
@shashwat-sh do you think you can look into this?

**Comment by shashwat-sh** [comment]
Yep, it's on my list, but I can bump up priority and work on it over the
next day or two.

**Comment by shashwat-sh** [comment]
Normalization is already correct; added a warning when absorbing / PML boundaries are used in a 2D simulation along the zero dimenion; see [this PR](https://github.com/flexcompute/tidy3d/pull/693).
