### ISSUE TITLE
`CustomCurrentSource`

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#680]
Would be nice to have an alternative to `CustomFieldSource` that lets one set the Jx, Jy, Jz, Mx, My, Mz component directly.
Could also be considered as a classmethod constructor for `CustomFieldSource` that invokes the equivalence principle?

Needed for `JaxFieldData` in adjoint plugin.

**Comment by momchil-flex** [comment]
Included in 2.3
