### ISSUE TITLE
DC Component in Source Spectrum

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#690]
Currently our source spectrum doesn't contain DC component. As a result, source power is low close to zero frequency, which could lead to noisy results in a broadband simulation. Would be good to have, for example, an option in `GaussianPulse` that adds DC component to the spectrum.

**Comment by momchil-flex** [comment]
@caseyflex I've assigned you here but it is low priority compared to STL and 2D materials. You can work with Tom to figure out how to set things up, probably just an extra kwarg in `GaussianPulse`.

**Comment by tylerflex** [comment]
what's the status on this?

**Comment by caseyflex** [comment]
Was a relatively low priority, but it’s on my to do list on the what’s new
for this month. Should be easy.
