### ISSUE TITLE
Medium2D with inhomogeneous substrate / superstrate

### ISSUE THREAD

**Issue by caseyflex** [flexcompute/tidy3d#691]
Currently, Medium2D requires a homogeneous medium as a substrate / superstrate. It would be good to allow inhomogeneous media.

One possibility is to use CustomMedium for the volumetric equivalent of the Medium2D in this scenario. This would take some more effort because we'd have to use the detailed geometric information of the neighboring media.

**Comment by tylerflex** [comment]
where are we at with this?

**Comment by caseyflex** [comment]
We could discuss how to handle this elegantly. In the case of a handful of
media, could just split up the 2D medium. In the case of many or custom
medium, it’s more complicated, but might be possible using the new custom
dispersive medium

**Comment by dmarek-flex** [comment]
@tylerflex @caseyflex I think this issue was addressed in this [PR](https://github.com/flexcompute/tidy3d/pull/1395). It is possible to treat it more elegantly, but I think the fundamental issue was addressed.
