### ISSUE TITLE
Losses in bent waveguide modes [mode solver]

### ISSUE THREAD

**Issue by mdecea** [flexcompute/tidy3d#697]
Hello,

I'm trying to obtain radiation losses of modes in bent waveguides, but no matter how tight I make the bend, I always get 0 for the imaginary part of the effective index of the mode.

Is there a way to obtain the radiation loss using the mode solver? I know it can be done with FDTD, but what about just using the mode solver?

Thanks!

**Comment by momchil-flex** [comment]
The default boundaries in the mode solver are PEC. Thus, if the materials are lossless, the modes will also always be lossless. You can add pml boundaries by adding e.g. `num_pml = (12, 12)` in the `ModeSpec`. This should capture the bend losses, with the only caveat being that it will probably also create a number of spurious modes inside the pml regions, so filtering your desired mode may be a bit harder - but it should work!
