### ISSUE TITLE
Tidy3d + Jax + Sax Demo

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#721]
I'd like to do the following demo for the docs:

Circuit simulation using Sax with one or more components simulated with Tidy3d adjoint plugin.
Optimize a circuit-level objective function w.r.t. a CustomMedium in the Tidy3d simulations.

Eg. Inverse design a wavelength-division multiplexer component within a larger circuit simulation.

Use jax to pass gradients from the circuit level objective to the pixel-level permittivity grid and do gradient descent.

**Comment by tylerflex** [comment]
Might be good to include @e-g-melo as well. Maybe we can first brainstorm some ideas for a demo that involves
1. setting up a circuit as a function of a few parameters (or maybe as a function of the data in a JaxCustomMedium).
2. using `sax` to get the circuit parameters and make a figure of merit over these parameters.
3. using `jax` to differentiate the FOM through the circuit parameters, and tidy3d simulation to get gradients with respect to the geometry.

I don't have many good ideas for the application / demo, but can help out with setting things up maybe once we have a basic setup.

**Comment by lucas-flexcompute** [comment]
Do we want it to be very large scale? The [cascaded MZI example](https://gdsfactory.github.io/gdsfactory/notebooks/workflow_3_cascaded_mzi.html) I created for gdsfactory comes to mind as a possibility. We could replace the coupling regions with optimized MMI's (parametric or adjoint optimization).

**Comment by tylerflex** [comment]
That could be interesting, I think it should be adjoint optimization to make use of the automatic differentiation. guess we just need to figure out what parameters it should have.

**Comment by e-g-melo** [comment]
Optimizing the device for robustness under fabrication variability to obtain maximum yield would be interesting in these large circuits. Lukas Chrostowski has some works on this subject: https://doi.org/10.1364/OE.381921. However, the optimization can be quite challenging as the cost function would require some variations of the device, e.g. dilated, eroded, thicker, and thinner.

**Comment by tylerflex** [comment]
Note for later: might be best to have #1112 completed first.

**Comment by tylerflex** [comment]
fixed by https://github.com/flexcompute-readthedocs/tidy3d-docs/pull/313
