### ISSUE TITLE
Git friendly notebooks

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#722]
Could be worth investing some time to install these hooks to this repo to streamline our docs workflow a bit, eg allow merging changes into notebooks without needing to do an overwrite.

**Comment by lucas-flexcompute** [comment]
I tried [nbdev](https://nbdev.fast.ai/) from the original post, but it did not work for merging conflicts. It also requires nbdev to be installed system-wide if using a system Jupyter instal and doesn't work outside of Jupyter (if anyone decides to edit notebooks on VSCode, for instance). In all, I'm not sure this is a good solution — looks like it's going to be more of a headache.

An alternative is to use [nbdime](https://nbdime.readthedocs.io/), which looks like a more focused tool. Here's the terminal output for diff:

![20230706-131834](https://github.com/flexcompute/tidy3d/assets/119979961/5547d3e1-ed54-4757-bafc-2c12653a970e)

And their web merge/diff viewer:

![20230706-131908](https://github.com/flexcompute/tidy3d/assets/119979961/473d5993-1b85-49d8-a5da-3f3e8a0f3cc1)

If a merge conflict happens, the diff driver creates a proper notebook with the conflict markup that can be opened in Jupyter for resolution:

![20230706-132457](https://github.com/flexcompute/tidy3d/assets/119979961/513e2660-75d7-479c-bd53-8c8bc3f13ac8)

**Comment by tylerflex** [comment]
seems pretty awesome!
