### ISSUE TITLE
Immediately return data for identical simulation uploaded

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#728]
Say a user has run a simulation `S` and has the data still stored on our servers.

At a later time, the user uploads an identical simulation `S`, it would be great if we could immediately identify that the data for `S` exists stored in the user's database and return it immediately, without running a new simulation.

We can hash `Simulation` objects and look up the corresponding `SimulationData` if it exists.

**Comment by momchil-flex** [comment]
This could be pretty cool, the only objection I can see is that we know that the hash can be somewhat slow in some cases, so do we want to accept this overhead for all simulations given that most will be new.

Also, we probably want a way to override this for dev purposes as we may be e.g. rebuilding the solver for testing, and would like to see new results.

**Comment by joamatab** [comment]
yes, we have something in gdsfactory where we run `cache=None` and won't look at the cached results

**Comment by tylerflex** [comment]
closing this as already being discussed in #936
