### ISSUE TITLE
tags in example notebooks

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#744]
Would be great to have a system where we can "tag" notebooks with various keywords and have them be nicely searchable in our docs. Eg.

#metalens, #field_projections, #small_simulations

**Comment by tylerflex** [comment]
@tomflexcompute if you think this would be useful, maybe we can coordinate with MC to display eg the metadata tags near the title and make them selectable or searchable?

**Comment by tylerflex** [comment]
or maybe introduce new "tags" metadata that are more user-facing than the metadata itself.  Probably this would have to be a knowledge base feature rather than a readthedocs feature, not sure how to set it up there.

**Comment by tomflexcompute** [comment]
@tylerflex I think this can be handled in the [marketing site](https://www.flexcompute.com/tidy3d/examples/). Currently they are designing the new layout. Once it's done we can see what features to add and how to handle them.

**Comment by tomflexcompute** [comment]
All tagging has been completed and deployed to production in the Learning Center.
