### ISSUE TITLE
Make monitors colocate to grid boundaries by default

### ISSUE THREAD

**Issue by momchil-flex** [flexcompute/tidy3d#756]
Currently, by default monitors return fields sampled on the Yee lattice, which is not a big issue when working in our python client as xarray makes it very convenient to interpolate anywhere we want. However, it is not that convenient if the user looks at the raw data from the hdf5 file, or for analysis in our web GUI. It is probably most intuitive to return fields colocated on the primal grid, i.e. at the cell boundaries. Colocating makes sense as users can e.g. compute quantities that depend on multiple fields directly, without worrying about interpolating first - which can be tripping. And colocating on the primal grid probably makes more sense than colocating at grid centers if you consider e.g. cases with a symmetry (even if it is not explicitly defined), in which case you'd expect the fields to go to 0 at the symmetry plane, and there is always a cell boundary there, rather than a cell center.

**Comment by tylerflex** [comment]
I forget, does this introduce some additional error to the fields? eg if the user is interpolating using these grid boundary values, they are essentially interpolating twice right? is it significant?

**Comment by momchil-flex** [comment]
Yeah, if they want to interpolate to some particular locations, it will be more accurate to set `colocate=False` and then do the interpolation. The reasoning behind this change though is that in most cases users just work with the raw fields and expect them to be colocated, that is to say they expect to be able to do something like `E x H` directly.

**Comment by tylerflex** [comment]
Makes sense. I'd also think eventually a `CustomFieldMonitor` might be nice, in which the user specifies the points directly (which would basically be us doing the interpolation server side) this could come in handy for adjoint down the line too.

**Comment by momchil-flex** [comment]
Fixed in #851
