### ISSUE TITLE
Enhanced GDS Import functionality

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#757]
Some users get confused about how to do gds imports when there are many cells and layers in the gds file and they want to import specific ones. Could we improve the existing gds import to make it more intuitive in terms of selecting cells and layers @lucas-flexcompute ? If you don't think there is too much room for improvement, we should certainly have an example demonstrating importing structures from a more complex gds file. 

@xin-flex please share if you have design any ideas.

**Comment by lucas-flexcompute** [comment]
I've improved the GDSII example in our docs. On Tidy3d's side, we're working on improving the whole workflow, so that should also happen at some point in the future.

**Comment by tylerflex** [comment]
Closing due to https://github.com/flexcompute-readthedocs/tidy3d-docs/pull/148
