### ISSUE TITLE
Decreasing time step size in the presence of materials with eps_inf < 1

### ISSUE THREAD

**Issue by weiliangjin2021** [flexcompute/tidy3d#761]
The maximal time step size for a stable simulation is constrained to a factor that scales with sqrt(eps_inf). So to determine the time step size, we'll need to loop through all structures to find out the minimal eps_inf.

@tylerflex I can think of two ways to obtain eps_inf: 1) `.eps_model(td.inf)`, but it will warn about frequency out of range; 2) add an attribute in `AbstractMedium` to record `eps_inf`. How do you think?

**Comment by tylerflex** [comment]
How would #2 store the attribute? would it also have to call `.eps_model`?  Maybe we can do #1 but temporarily set the logging level to error to suppress warnings?

**Comment by weiliangjin2021** [comment]
For the 2nd option, I'm thinking of adding eps_inf in each type of medium. E.g. for dispersiveless medium, it's just the permittivity; and for PoleResidue model, eps_inf is already defined.

**Comment by tylerflex** [comment]
I see, that could work as well. Either one is fine with me

**Comment by tylerflex** [comment]
@weiliangjin2021 are we able to close this issue?
