### ISSUE TITLE
Adjoint Plugin That is Compatible with More Geometries, Sources, and Monitors

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#777]
Recently quite a few customers have been requesting an adjoint plugin that is compatible with more geometries, sources, and monitors. More specifically, one customer wants to optimize the field on a field monitor. The other customer wants to use a dipole source for a photonic crystal cavity design as well as use cylinders in their device. 

I know @tylerflex  is currently busy with various tasks related to the release. Developing the adjoint plugin might be something that we can put a higher priority on after the release?

**Comment by tylerflex** [comment]
This is quite general. I will break up the remaining adjoint features into their own distinct issues later.
