### ISSUE TITLE
Convenience method for `ModeSolver` to export `Simulation` with mode source added.

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#807]
the method would look very similar to this one, in fact it might call it internally.
https://github.com/flexcompute/tidy3d/blob/develop/tidy3d/plugins/mode/mode_solver.py#L500-L532

## Checklist:

a PR in this repository (into develop branch) containing
- [ ] The new method
- [ ] Test coverage in tests/test_plugins/test_mode.py
- [ ] Add line to CHANGELOG.md explaining what was added.

a PR to the tidy3d-docs repository (develop branch)
- [ ] Add a cell showing this method in use in the [mode solver tutorial notebook](https://github.com/flexcompute-readthedocs/tidy3d-docs/blob/develop/docs/source/notebooks/ModeSolver.ipynb)

**Comment by momchil-flex** [comment]
This is done right? Closing, reopen if not.
