### ISSUE TITLE
`nan` values in field projection

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#808]
I noticed that the projected fields in the `Metalens.ipynb` notebook have `nan` values corresponding to these "holes" in the field. Could we look into this after 2.0?

![Image](https://user-images.githubusercontent.com/92756888/228645268-0d00e962-3dea-44e3-815c-4ad33d36e816.png)

```
>>> np.any(np.isnan(proj_fields.Ez.values))
True
```

**Comment by shashwat-sh** [comment]
See this PR for a fix: https://github.com/flexcompute/tidy3d-core/pull/276
