### ISSUE TITLE
Better handling for "no sources" validator in Simulation

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#813]
Right now, we get this validator twice when constructing a sim for the mode solver and plotting the mode solver results.

It's unnecessary to print this warning in these cases as we really only want to warn the user if they are running the simulation.

We could add as a pre-upload validator (which errors) but we'd still want the user to be able to submit a simulation without sources if (for some reason) they want to view ModeMonitorData or PermittivityData results.

Not sure what the best approach is, but I might even suggest moving it from WARNING to INFO for now as a short term solution?

**Comment by tylerflex** [comment]
Referenced in #978, possibly duplicate and we can close.

**Comment by lucas-flexcompute** [comment]
I'm not so sure our solution for #978 will help much here. I'm proposing another solution specifically for this, just in case.

**Comment by tylerflex** [comment]
perhaps we can move this to a "pre-upload" validator (and make it error) that way it doesn't get triggered for mode stuff
