### ISSUE TITLE
2D Simulation plots lack PML

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#823]
Encountered an issue where the `sim.plot()` was missing PMLs for a 2D simulation. Inspecting the `Simulation._make_pml_boxes()`, it seems the boxes have size 0 in the normal direction, so they probably are just not being found. We can put a condition to expand the PML boxes to infinity if any of the Simulation.size is 0 along that dimension perhaps.

**Comment by tylerflex** [comment]
Fixes https://github.com/flexcompute/tidy3d/issues/823

**Comment by momchil-flex** [comment]
Sorry, I'm confused, you mean PML along the dimension where the size is 0? That's not a good setup, in fact I think we even warn about it?

**Comment by momchil-flex** [comment]
https://github.com/flexcompute/tidy3d/pull/693

**Comment by momchil-flex** [comment]
Oh ok.
