### ISSUE TITLE
tries to decode string

### ISSUE THREAD

**Issue by tonysong1111** [flexcompute/tidy3d#832]
**Describe the bug**
File ~\AppData\Roaming\Python\Python38\site-packages\tidy3d\components\data\data_array.py:149, in <listcomp>(.0)
    147 for key, val in coords.items():
    148     if val.dtype == "O":
--> 149         coords[key] = [byte_string.decode() for byte_string in val.tolist()]
    150 return cls(values, coords=coords)

Seems there are parts of code that tries to decode a string - a bit of searching suggests that this is not needed for python 3.x? This prevents code from running further and spits out the above error when running job.

**To Reproduce**
See grating coupler example, exciting grating coupler using Gaussian beam at an angle:
sim_data2 = job2.run(path="data/grating_coupler.hdf5")

**Comment by tylerflex** [comment]
Hi @tonysong1111 what version of tidy3d are you using? you can `print(td.__version__)`

**Comment by tylerflex** [comment]
Can you also print your versions of `h5py` and `xarray`? eg `pip show xarray`?

**Comment by tylerflex** [comment]
Also, if you could print the error in full that would be helpful too, thanks. I just ran the grating coupler example with latest version (2.0.2) and it ran fine for me on python 3.10, xarray 2023.2.0, and h5py of 3.7.0

**Comment by tonysong1111** [comment]
Hi Tyler,

  Thanks for the response. Indeed I had a bit of trouble with a (probably) incompatible versions of previous packages. I previously followed the instructions for installing tidy3d in a virtual environment with python3.8, and had a lot of trouble including the one above. Anyways, starting from a fresh python 3.10 venv fixed everything. Thanks for your help :)
