### ISSUE TITLE
simplify serialization

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#834]
I propose the following:
1. overwrite `.json()` in `Tidy3DBaseModel` to just use internal `._json_string()`. Don't see a reason to have two methods here and it has led to confusion, eg in the webapi release.
2. get rid of `TidyNDArray` or whatever it's called, which implements hash for `np.ndarray`. Seems gdsfactory at least hashes the json string, not the component itself, which makes sense. So maybe being able to hash components is unnecessary if the json string is already hashable.

**Comment by momchil-flex** [comment]
Sounds good to me.

**Comment by lucas-flexcompute** [comment]
Yes, to me it makes sense as well. We'll continue to have validation on the array types, it's just not subclassed any longer, right?

**Comment by tylerflex** [comment]
Yes, it will be validated, but not subclassed. Tidy3d objects will no longer be hashable but I think it's ok. Also, I decided to just not mess with the json_string thing. Too many bits can break and it doesn't seem worth it.
