### ISSUE TITLE
update error for self intersecting PolySlab

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#845]
in line 2125 of (current state of) geometry.py we have
```
        if not isinstance(poly_offset, Polygon) or len(poly_offset.interiors) > 0:
            raise SetupError(
                "Dilation/Erosion value is too large, resulting in "
                "polygon splitting or generation of holes/islands. "
                "A general treatment to self-intersecting polygon will be available "
                "in future releases."
            )
```

I think we should update this message to provide user a more helpful message, including some syntax for defining a complex polyslab.

**Comment by weiliangjin2021** [comment]
For polygon that is self-intersecting on the reference plane, we don't have any treatment at the moment. A complex polyslab can be used if the polygon is simple on the reference plane but self-intersecting when offsetted. The error message is here:https://github.com/flexcompute/tidy3d/blob/c713fd8d133934c88512b608e4b1b8defe2beddf/tidy3d/components/geometry.py#L2189-L2195

Are you suggesting to add an example to this error message?

**Comment by tylerflex** [comment]
no that's fine, I forgot that at the reference frame it's still not supported. I will just close this, thanks for clarifying!
