### ISSUE TITLE
callback_url not called

### ISSUE THREAD

**Issue by venkatkorapaty** [flexcompute/tidy3d#854]
When using `web.Job` with a `callback_url`, it doesn't seem to trigger it upon simulation completion.
We haven't changed the way we generate/provide the URL.

This occurs with tidy3d 2.x. Previously, using 1.9, it was fine.
We provide a `td.Simulation`, `task_name` and `callback_url` to `td.web.Job` and `start` the job.

Upon completion, it should send us the simulation report to the URL, but it does not.

Is there something that changed with this feature in 2.x?

**Comment by tylerflex** [comment]
Hi @venkatkorapaty sorry for the inconvenience, there was some internal refactoring for 2.x so it's possible something is not working correctly. I will look into it today and let you know.

**Comment by venkatkorapaty** [comment]
Hey @tylerflex , thanks for the response.

I tried this branch in our build, but it seems that the `callback_url` still isn't being triggered.

**Comment by tylerflex** [comment]
Can you pull from that branch and try one more time? one of our engineers took a look and pushed a commit to that branch a couple of minutes ago that should fix it. Sorry about this, should be able to get it worked out soon

**Comment by venkatkorapaty** [comment]
It is triggering now with the json, thanks for the change!

**Comment by tylerflex** [comment]
No problem, we will release 2.1.1 today with this fix. thanks for bringing it to our attention

**Comment by tylerflex** [comment]
2.1.1 is released now, so you can just use that version now. @venkatkorapaty
