### ISSUE TITLE
Enhanced batch task and result management 

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#857]
Currently a batch doesn't contain the task ids of its individual task. If the internet or computer is interrupted during a batch run, it is cumbersome to download result data from each task. Would it be possible to attach a batch id to a batch such that it enables functionalities such as downloading batch data from batch id, rerunning or editing individual tasks in the batch without affecting others?

**Comment by tomflexcompute** [comment]
Thanks for the information. It would certainly be great to have such infrastructure to simplify batch manipulations. Corresponding JIRA ticket is [here](https://flow360.atlassian.net/jira/software/c/projects/SCEM/issues/INFR-482?jql=project%20IN%20%28%22infrastructure-%22%29%20ORDER%20BY%20created%20DESC).

**Comment by tylerflex** [comment]
Assigning @lei-flex just to keep track of this as he's on the jira ticket
