### ISSUE TITLE
Write simulation plane to gds cell

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#883]
eg wrapping `filter_structures_plane`, the following would be convenient

```py
sim.to_gds(gds_cell, z=0)
```

**Comment by tylerflex** [comment]
@lucas-flexcompute this is probably low priority but assigning you to try at some point if you think it's potentially useful. We had a user trying to generate a gds file from their Simulation and was trying to do it by hand. In general, if there was some interface to make gds cells more simply from the Simulation itself, it might be useful.

**Comment by xin-flex** [comment]
Two situations need to be considered:
1. regular structures
2. structures with custom medium (e.g. used in adjoint optimization)

**Comment by tylerflex** [comment]
Also, I thought we had a demo of 2 in our level set [notebook](https://docs.flexcompute.com/projects/tidy3d/en/latest/notebooks/AdjointPlugin10YBranchLevelSet.html) but it seems not.

**Comment by lucas-flexcompute** [comment]
I was on the planning phase for this and I just wanted to share my thoughts to make sure I'm going in the right direction with the UI. I'm thinking of 3 interface functions:

- `Geometry.to_gds(filename: str, layer: Tuple[NonNegativeInt, NonNegativeInt])`
- `Structure.to_gds(filename: str, layer: Tuple[NonNegativeInt, NonNegativeInt], permittivity_threshold: PositiveFloat = None)`
- `Simulation.to_gds(filename: str, layer_map: Dict[MediumType, Tuple[NonNegativeInt, NonNegativeInt]] = {}, permittivity_threshold: PositiveFloat = None)`

For the geometry, it seems quite straightforward to just use `Geometry.intersections_plane`. For structures with custom medium, we use threshold parameter and intersect the actual geometry shape with the contour from `AbstractCustomMedium.eps_diagonal_on_grid` (using the coordinates from geometry bounds and the maximum value in the diagonal).

**Comment by tylerflex** [comment]
This sounds good to me, so as an edge case, how do we treat geometry group / clip operations? as a single layer?

**Comment by lucas-flexcompute** [comment]
Groups and clip operations also implement `intersections_plane`, so there's no need to treat them as special cases. And because they have a single medium (when used in a structure), all generated shapes will belong to the same layer.

**Comment by lucas-flexcompute** [comment]
Implemented in https://github.com/flexcompute/tidy3d/pull/1194
