### ISSUE TITLE
Change "structure completely outside of simulation domain" from error to warning

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#885]
If a Structure is totally outside of the simulation domain, it will be considered as an error. It causes inconvenience especially when doing gds import where the simulation is only done on part of the layout. We can consider making it a warning and if a structure is totally outside of the domain, it will be ignored.

**Comment by momchil-flex** [comment]
Is this gonna stay for after 2.2 @tylerflex ?

**Comment by tylerflex** [comment]
I’d say so. I’d like to test it doesn’t break anything and don’t want to
rush it in ideally

**Comment by momchil-flex** [comment]
Seems like we should do a better job of tracking issues, they seem to fall through the cracks.

**Comment by tylerflex** [comment]
Assigning @lei-flex just to keep track of this as he's on the jira ticket
