### ISSUE TITLE
Consistent plot_field colormaps

### ISSUE THREAD

**Issue by momchil-flex** [flexcompute/tidy3d#893]
It seems like after some of the field plottig refactoring, plotting the "real" part of the field can come out with inconsistent colormap depending on whether the field has negative values or not - see for example cell 11 in the grating coupler notebook. I feel like we should always use the RdBu map for real/imaginary part.

![image](https://github.com/flexcompute/tidy3d/assets/92756559/d31a1e0b-9eba-4e56-8a8b-54eb9e4548c6)

**Comment by lucas-flexcompute** [comment]
That's xarray's behavior. This cell is not using our plotting functions. It should be
```python
ms.plot_field("Ex", val="real", robust=False, ax=ax1)
ms.plot_field("Ey", val="real", robust=False, ax=ax2)
ms.plot_field("Ez", val="real", robust=False, ax=ax3)
```
![20230522-074346](https://github.com/flexcompute/tidy3d/assets/119979961/2c0f02ea-bf58-4ef7-acf1-f068de9870d7)

**Comment by momchil-flex** [comment]
Oh I see, thanks, sorry I didn't pay too close attention when I made the issue. :)
