### ISSUE TITLE
Show "to cancel the simulation, use the web.delete() method or visit simulation.cloud" when a job starts running

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#921]
Some users are confused about terminating the notebook and terminating the simulation run. Could we add a message to the current messages along the line of "to cancel the simulation, use the web.delete() method or visit simulation.cloud" when a job is run?

**Comment by tylerflex** [comment]
@tomflexcompute could you take a stab at this? I think we could throw in the `console.log` call right [here](https://github.com/flexcompute/tidy3d/blob/develop/tidy3d/web/webapi.py#L377), which is at the first point that the job is detected as running.
