### ISSUE TITLE
wrong API key message

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#941]
I updated my key recently

how can we make a better error message when the key is wrong?

![image](https://github.com/flexcompute/tidy3d/assets/4514346/6689cb81-5084-4233-8344-1a3380db3135)

**Comment by tylerflex** [comment]
We will make the error more descriptive. @xin-flex I will assign you to this but please reassign to the relevant MC team member and have them close the issue once it's addressed. Should be a very simple fix. Thanks!

**Comment by xin-flex** [comment]
Thanks Tyler. Will do.

**Comment by momchil-flex** [comment]
@xin-flex is this on MC's schedule? Let's get it in as it should be very simple.

**Comment by xin-flex** [comment]
This has already been implemented.
