### ISSUE TITLE
add links to FDTD 101 in examples in docs?

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#946]
what do you think @tomflexcompute ? seems there are a lot of examples there that might be useful for users to know about.

**Comment by tomflexcompute** [comment]
I think that's a good idea. We can add links to simpler examples that beginners are likely to see.

**Comment by tylerflex** [comment]
Or just links to them without copying over i think would be ok too. And
could avoid us having to update them both later
