### ISSUE TITLE
Field projection result has strange plateaus

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#986]
I'm using this notebook to simulate metalens with a certain radius. A `FieldProjectionCartesianMonitor` is used to project the near field to areas around the focus. What I found strange is that when the lens radius is large, the projected field shows strange discontinuity. 

For radius = 50 lambda, the projected field is smooth as expected. 
<img width="434" alt="image" src="https://github.com/flexcompute/tidy3d/assets/116006359/de01f1b6-db6c-41fc-a21a-31137a639eaa">

For radius = 200 lambda, the projected field has some strange "plateaus" at the center. 
<img width="429" alt="image" src="https://github.com/flexcompute/tidy3d/assets/116006359/68b9ddfc-4aec-4803-97ad-adcd8d0d0de9">

For radius = 250 lambda, more "plateaus" are observed. 
<img width="436" alt="image" src="https://github.com/flexcompute/tidy3d/assets/116006359/a6a754f2-cd98-4a2e-9572-27b462473f5b">

In all simulations, the projected x and y in the `FieldProjectionCartesianMonitor` are the same so the  "plateaus" are not due to under-sampling. @shashwat-sh could you take a look and see if you see anything wrong? I also attach the notebook here if you want to try. Running the notebook at a large radius does take a significant amount of time tho. 

[MidIRMetalens.zip](https://github.com/flexcompute/tidy3d/files/11938472/MidIRMetalens.zip)

**Comment by momchil-flex** [comment]
Yeah zooming in on the 2D plot, it definitely looks strange. @shashwat-sh note that the projection distance increases as the diameter of the metalens increases - if I had to guess, it's probably again something related to overflow/numerical precision as the distance becomes large?

![image](https://github.com/flexcompute/tidy3d/assets/92756559/11e4aebc-d98e-4836-aa63-178c855bb8fc)

**Comment by tylerflex** [comment]
what's the status of this?
